import type { Prisma, PrismaClient } from "@prisma/client";

import { prisma } from "@/server/db";

/**
 * Append-only audit action keys used in Phase 2B (identity lifecycle).
 * Stored in AuditLog.action (String). Extend as later phases add actions.
 */
export const AUDIT = {
  USER_REGISTERED: "USER_REGISTERED",
  REGISTRATION_APPROVED: "REGISTRATION_APPROVED",
  REGISTRATION_REJECTED: "REGISTRATION_REJECTED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_RESTORED: "USER_RESTORED",
  USER_ROLE_ASSIGNED: "USER_ROLE_ASSIGNED",
  USER_ROLE_REMOVED: "USER_ROLE_REMOVED",
  LOGIN_BLOCKED_PENDING: "LOGIN_BLOCKED_PENDING",
  LOGIN_BLOCKED_REJECTED: "LOGIN_BLOCKED_REJECTED",
  LOGIN_BLOCKED_INACTIVE: "LOGIN_BLOCKED_INACTIVE",
  LOGIN_BLOCKED_SUSPENDED: "LOGIN_BLOCKED_SUSPENDED",
  LOGIN_RATE_LIMITED: "LOGIN_RATE_LIMITED",
  REGISTRATION_RATE_LIMITED: "REGISTRATION_RATE_LIMITED",
  // Immutability (Layer 5) sanctioned change paths.
  DECISION_SUPERSEDED: "DECISION_SUPERSEDED",
  DECISION_REOPENED: "DECISION_REOPENED",
  MEASUREMENT_SUPERSEDED: "MEASUREMENT_SUPERSEDED",
  MEASUREMENT_REOPENED: "MEASUREMENT_REOPENED",
  // Ideas (governance 5.23.3 — Phase 3A).
  IDEA_CREATED: "IDEA_CREATED",
  IDEA_UPDATED: "IDEA_UPDATED",
  IDEA_SUBMITTED: "IDEA_SUBMITTED",
  IDEA_WITHDRAWN: "IDEA_WITHDRAWN",
  IDEA_ARCHIVED: "IDEA_ARCHIVED",
  IDEA_RESTORED: "IDEA_RESTORED",
  STRATEGIC_OBJECTIVE_CREATED: "STRATEGIC_OBJECTIVE_CREATED",
  STRATEGIC_OBJECTIVE_UPDATED: "STRATEGIC_OBJECTIVE_UPDATED",
  STRATEGIC_OBJECTIVE_ARCHIVED: "STRATEGIC_OBJECTIVE_ARCHIVED",
  COMPLIANCE_ASSIGNMENT_CREATED: "COMPLIANCE_ASSIGNMENT_CREATED",
  COMPLIANCE_ASSIGNMENT_UPDATED: "COMPLIANCE_ASSIGNMENT_UPDATED",
  COMPLIANCE_ASSIGNMENT_ARCHIVED: "COMPLIANCE_ASSIGNMENT_ARCHIVED",
  STRATEGY_DOCUMENT_UPLOADED: "STRATEGY_DOCUMENT_UPLOADED",
  STRATEGY_DOCUMENT_UPDATED: "STRATEGY_DOCUMENT_UPDATED",
  STRATEGY_DOCUMENT_ARCHIVED: "STRATEGY_DOCUMENT_ARCHIVED",
  ACTIVITY_CREATED: "ACTIVITY_CREATED",
  ACTIVITY_UPDATED: "ACTIVITY_UPDATED",
  ACTIVITY_ARCHIVED: "ACTIVITY_ARCHIVED",
  COMMITTEE_CREATED: "COMMITTEE_CREATED",
  COMMITTEE_UPDATED: "COMMITTEE_UPDATED",
  COMMITTEE_ARCHIVED: "COMMITTEE_ARCHIVED",
  COMMITTEE_MEMBER_ADDED: "COMMITTEE_MEMBER_ADDED",
  COMMITTEE_MEMBER_UPDATED: "COMMITTEE_MEMBER_UPDATED",
  COMMITTEE_MEMBER_REMOVED: "COMMITTEE_MEMBER_REMOVED",
  COMMITTEE_MEETING_CREATED: "COMMITTEE_MEETING_CREATED",
  COMMITTEE_MEETING_UPDATED: "COMMITTEE_MEETING_UPDATED",
  COMMITTEE_MEETING_ARCHIVED: "COMMITTEE_MEETING_ARCHIVED",
  CHALLENGE_CREATED: "CHALLENGE_CREATED",
  CHALLENGE_UPDATED: "CHALLENGE_UPDATED",
  CHALLENGE_ARCHIVED: "CHALLENGE_ARCHIVED",
  CHALLENGE_SOLUTION_LINKED: "CHALLENGE_SOLUTION_LINKED",
  CHALLENGE_SOLUTION_UNLINKED: "CHALLENGE_SOLUTION_UNLINKED",
  // Idea evaluation / review (Phase 3B).
  IDEA_REVIEW_STARTED: "IDEA_REVIEW_STARTED",
  IDEA_EVALUATION_SUBMITTED: "IDEA_EVALUATION_SUBMITTED",
  IDEA_ADVANCED_TO_TECHNICAL: "IDEA_ADVANCED_TO_TECHNICAL",
  IDEA_MORE_INFO_REQUESTED: "IDEA_MORE_INFO_REQUESTED",
  IDEA_INFO_RESUBMITTED: "IDEA_INFO_RESUBMITTED",
  // Final decisions & conversion (Phase 3C).
  IDEA_DECISION_APPROVED: "IDEA_DECISION_APPROVED",
  IDEA_DECISION_REJECTED: "IDEA_DECISION_REJECTED",
  IDEA_CONVERTED: "IDEA_CONVERTED",
  // Solutions registry (5.24.1 — Phase 4A).
  SOLUTION_CREATED: "SOLUTION_CREATED",
  SOLUTION_UPDATED: "SOLUTION_UPDATED",
  SOLUTION_ARCHIVED: "SOLUTION_ARCHIVED",
  SOLUTION_PARTNER_UPDATED: "SOLUTION_PARTNER_UPDATED",
  // Lifecycle, publishing, sharing & participation (Phase 4B).
  SOLUTION_STATUS_CHANGED: "SOLUTION_STATUS_CHANGED",
  SOLUTION_MATURITY_CHANGED: "SOLUTION_MATURITY_CHANGED",
  SOLUTION_IMPLEMENTATION_CHANGED: "SOLUTION_IMPLEMENTATION_CHANGED",
  SOLUTION_PUBLISHED: "SOLUTION_PUBLISHED",
  SOLUTION_UNPUBLISHED: "SOLUTION_UNPUBLISHED",
  SOLUTION_SHARE_GRANTED: "SOLUTION_SHARE_GRANTED",
  SOLUTION_SHARE_UPDATED: "SOLUTION_SHARE_UPDATED",
  SOLUTION_SHARE_REVOKED: "SOLUTION_SHARE_REVOKED",
  SOLUTION_ORG_ADDED: "SOLUTION_ORG_ADDED",
  SOLUTION_ORG_REMOVED: "SOLUTION_ORG_REMOVED",
  IMPACT_INDICATOR_SAVED: "IMPACT_INDICATOR_SAVED",
  IMPACT_MEASUREMENT_RECORDED: "IMPACT_MEASUREMENT_RECORDED",
  // Evidence management (Phase 5A).
  EVIDENCE_UPLOADED: "EVIDENCE_UPLOADED",
  EVIDENCE_UPDATED: "EVIDENCE_UPDATED",
  EVIDENCE_SUBMITTED: "EVIDENCE_SUBMITTED",
  EVIDENCE_REVIEW_STARTED: "EVIDENCE_REVIEW_STARTED",
  EVIDENCE_APPROVED: "EVIDENCE_APPROVED",
  EVIDENCE_REJECTED: "EVIDENCE_REJECTED",
  EVIDENCE_ARCHIVED: "EVIDENCE_ARCHIVED",
  EVIDENCE_LINKED: "EVIDENCE_LINKED",
  EVIDENCE_UNLINKED: "EVIDENCE_UNLINKED",
  // Binary storage & secure access (Phase 5A.1).
  EVIDENCE_DOWNLOADED: "EVIDENCE_DOWNLOADED",
  EVIDENCE_DOWNLOAD_DENIED: "EVIDENCE_DOWNLOAD_DENIED",
  EVIDENCE_FILE_REPLACED: "EVIDENCE_FILE_REPLACED",
  // AI document analysis (Phase 5B) — the AI only ever proposes.
  ANALYSIS_QUEUED: "ANALYSIS_QUEUED",
  ANALYSIS_STARTED: "ANALYSIS_STARTED",
  ANALYSIS_COMPLETED: "ANALYSIS_COMPLETED",
  ANALYSIS_FAILED: "ANALYSIS_FAILED",
  SUGGESTION_ACCEPTED: "SUGGESTION_ACCEPTED",
  SUGGESTION_EDITED: "SUGGESTION_EDITED",
  SUGGESTION_REJECTED: "SUGGESTION_REJECTED",
  // Compliance readiness engine (Phase 6) — configuration, governed N/A, export.
  // The engine never sets readiness; it reads real records + APPROVED evidence.
  COMPLIANCE_SECTION_CREATED: "COMPLIANCE_SECTION_CREATED",
  COMPLIANCE_SECTION_UPDATED: "COMPLIANCE_SECTION_UPDATED",
  COMPLIANCE_REQUIREMENT_CREATED: "COMPLIANCE_REQUIREMENT_CREATED",
  COMPLIANCE_REQUIREMENT_UPDATED: "COMPLIANCE_REQUIREMENT_UPDATED",
  COMPLIANCE_REQUIREMENT_ACTIVATED: "COMPLIANCE_REQUIREMENT_ACTIVATED",
  COMPLIANCE_REQUIREMENT_DEACTIVATED: "COMPLIANCE_REQUIREMENT_DEACTIVATED",
  COMPLIANCE_NA_REQUESTED: "COMPLIANCE_NA_REQUESTED",
  COMPLIANCE_NA_APPROVED: "COMPLIANCE_NA_APPROVED",
  COMPLIANCE_NA_REJECTED: "COMPLIANCE_NA_REJECTED",
  COMPLIANCE_NA_REVOKED: "COMPLIANCE_NA_REVOKED",
  COMPLIANCE_EXPORTED: "COMPLIANCE_EXPORTED",
} as const;

export type AuditAction = (typeof AUDIT)[keyof typeof AUDIT];

export interface AuditInput {
  actorUserId?: string | null;
  action: AuditAction | string;
  entityType?: Prisma.AuditLogCreateInput["entityType"];
  entityId?: string | null;
  organizationId?: string | null;
  departmentId?: string | null;
  summary?: string | null;
  before?: Prisma.InputJsonValue | null;
  after?: Prisma.InputJsonValue | null;
  metadata?: Prisma.InputJsonValue | null;
  ipAddress?: string | null;
  userAgent?: string | null;
}

type Db = PrismaClient | Prisma.TransactionClient;

/**
 * Minimal append-only audit writer. NEVER pass passwords, password hashes, or
 * session tokens in before/after/metadata. Accepts an optional transaction
 * client so audit rows are written atomically with the action they record.
 */
export async function writeAudit(input: AuditInput, db: Db = prisma): Promise<void> {
  await db.auditLog.create({
    data: {
      actorUserId: input.actorUserId ?? null,
      action: input.action,
      entityType: input.entityType ?? null,
      entityId: input.entityId ?? null,
      organizationId: input.organizationId ?? null,
      departmentId: input.departmentId ?? null,
      summary: input.summary ?? null,
      beforeData: input.before ?? undefined,
      afterData: input.after ?? undefined,
      metadata: input.metadata ?? undefined,
      ipAddress: input.ipAddress ?? null,
      userAgent: input.userAgent ?? null,
    },
  });
}
