"use client";
import { useFormState, useFormStatus } from "react-dom";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { createIntakeLinkAction, submitIntakeAction, type IntakeActionState } from "../intake-actions";
const field="w-full rounded-xl border border-border bg-surface px-3 py-2 text-sm";
function Submit({children}:{children:string}){const {pending}=useFormStatus();return <Button disabled={pending}>{pending?"جارٍ الحفظ…":children}</Button>}
function State({state}:{state:IntakeActionState}){return <>{state.error?<p role="alert" className="rounded-xl bg-danger-bg p-3 text-sm text-danger">{state.error}</p>:null}{state.success?<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><p>{state.success}</p>{state.url?<p className="mt-1 break-all font-mono text-xs">{state.url}</p>:null}</div>:null}</>}
export function IntakeLinkForm(){const[state,action]=useFormState(createIntakeLinkAction,{});return <form action={action} className="space-y-4"><State state={state}/><div><Label htmlFor="nameAr">اسم رابط الحصر</Label><Input id="nameAr" name="nameAr" required placeholder="حصر المبادرات الابتكارية لعام 2026"/></div><div><Label htmlFor="purpose">الغرض</Label><textarea className={field} id="purpose" name="purpose" required rows={3}/></div><div><Label htmlFor="closesAt">تاريخ الإغلاق (اختياري)</Label><Input id="closesAt" name="closesAt" type="date"/></div><div><Label htmlFor="instructions">تعليمات المشارك</Label><textarea className={field} id="instructions" name="instructions" rows={3}/></div><Submit>إنشاء رابط استقبال حلول</Submit></form>}
export function PublicSolutionIntakeForm({token}:{token:string}){const bound=submitIntakeAction.bind(null,token);const[state,action]=useFormState(bound,{});return <form action={action} className="space-y-5"><State state={state}/><section className="space-y-3"><h2 className="font-semibold">بيانات مقدم الحل</h2><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="submitterName">الاسم</Label><Input id="submitterName" name="submitterName" required/></div><div><Label htmlFor="submitterEmail">البريد</Label><Input id="submitterEmail" name="submitterEmail" type="email"/></div><div><Label htmlFor="departmentName">الإدارة / الجهة</Label><Input id="departmentName" name="departmentName"/></div></div></section><section className="space-y-3"><h2 className="font-semibold">الحل</h2><div><Label htmlFor="nameAr">اسم الحل</Label><Input id="nameAr" name="nameAr" required/></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="description">وصف الفكرة / الحل</Label><textarea className={field} id="description" name="description" rows={4}/></div><div><Label htmlFor="problemStatement">المشكلة</Label><textarea className={field} id="problemStatement" name="problemStatement" rows={4}/></div></div><div className="grid gap-3 sm:grid-cols-3"><div><Label htmlFor="targetBeneficiaries">الفئة المستهدفة</Label><Input id="targetBeneficiaries" name="targetBeneficiaries"/></div><div><Label htmlFor="beneficiaryCount">عدد المستفيدين</Label><Input id="beneficiaryCount" name="beneficiaryCount" type="number" min="0"/></div><div><Label htmlFor="durationMonths">مدة الإنجاز (أشهر)</Label><Input id="durationMonths" name="durationMonths" type="number" min="0"/></div><div><Label htmlFor="cost">التكلفة</Label><Input id="cost" name="cost" type="number" min="0"/></div><div><Label htmlFor="technologies">التقنيات</Label><Input id="technologies" name="technologies"/></div><div><Label htmlFor="maturityStage">المرحلة الحالية</Label><select className={field} id="maturityStage" name="maturityStage"><option>مفهوم</option><option>إثبات مفهوم PoC</option><option>نموذج أولي Prototype</option><option>تجربة Pilot</option><option>تشغيل فعلي</option></select></div></div><div><Label htmlFor="expectedImpact">الأثر المتوقع</Label><textarea className={field} id="expectedImpact" name="expectedImpact" rows={3}/></div><div><Label htmlFor="achievedImpact">الأثر المحقق (إن توفر)</Label><textarea className={field} id="achievedImpact" name="achievedImpact" rows={3}/></div></section><p className="text-xs text-muted">الإرسال ينشئ طلب حصر للمراجعة فقط، ولا يعني اعتماد الحل أو نشره في المحفظة.</p><Submit>إرسال الحل للمراجعة</Submit></form>}
