"use client";

import { useState, type FormEvent } from "react";
import { ArrowLeft, CheckCircle2, Clock3, FileText, Link2, MessageSquare, Plus, Send, UserRound } from "lucide-react";

import { PreviewLink as Link } from "@/components/layout/preview-link";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { PreviewPersonaKey } from "@/lib/ux-preview";
import { PREVIEW_IDEA_SUBMISSIONS as submissions, PREVIEW_INTAKE_PAGES as intakePages, type PreviewSubmissionState as SubmissionState } from "../intake-preview-data";

const fieldClass = "mt-1.5 w-full rounded-xl border border-border bg-white px-3 py-2 text-sm";
const statusVariant = (status: SubmissionState) => status === "مقبولة" ? "success" : status.includes("استكمال") || status.includes("مكرر") ? "warning" : "neutral";

export function IntakeHomePreview({ persona }: { persona: PreviewPersonaKey }) {
  const canManage = persona === "admin" || persona === "internal";
  return <div className="space-y-5">
    <PageHeader title="استقبال الأفكار والحلول" description="استقبال منظم يسبق محفظة الحلول: تقديم ← مراجعة ← قرار ← إضافة للمحفظة عند القبول." action={canManage ? <Button asChild><Link href="/solutions/intake/new"><Plus className="h-4 w-4"/>إنشاء صفحة استقبال</Link></Button> : undefined}/>
    <div className="flex flex-wrap gap-2">
      {canManage ? <Button asChild variant="outline"><Link href="/solutions/intake/manual"><Plus className="h-4 w-4"/>إضافة فكرة/حل يدويًا</Link></Button> : null}
      {canManage ? <Button asChild variant="outline"><Link href="/solutions/intake/inbox">الوارد من الأفكار والحلول</Link></Button> : null}
      {canManage ? <Button asChild variant="outline"><Link href="/solutions/intake/decisions">التقييم والقرارات</Link></Button> : null}
      <Button asChild variant="outline"><Link href="/solutions/intake/my-submissions"><UserRound className="h-4 w-4"/>تجربة «مشاركاتي» للمبتكر</Link></Button>
    </div>
    <div className="grid gap-4 lg:grid-cols-3">{intakePages.map(page=><Card key={page.id}><CardHeader><div className="flex items-start justify-between gap-3"><CardTitle>{page.name}</CardTitle><Badge variant="success">{page.status}</Badge></div></CardHeader><CardContent className="space-y-3 text-xs"><p><span className="text-muted">الجمهور:</span> {page.audience}</p><p><span className="text-muted">المالك:</span> {page.owner}</p><div className="flex justify-between rounded-xl bg-slate-50 p-3"><span>{page.submissions} مشاركة</span><span>{page.created}</span></div><Button asChild className="w-full" size="sm" variant="outline"><Link href={page.id === "public" ? "/submit/innovation-ideas" : "/solutions/intake/inbox"}>فتح الصفحة <ArrowLeft className="h-4 w-4"/></Link></Button></CardContent></Card>)}</div>
    <Card className="border-primary/20"><CardContent className="grid gap-3 p-5 text-center text-sm md:grid-cols-4"><div>الاستقبال</div><div>المراجعة والإحالة</div><div>التقييم والقرار</div><div className="font-semibold text-primary">محفظة الحلول الابتكارية</div></CardContent></Card>
  </div>;
}

export function IntakeDecisionsPreview() {
  const rows=submissions.filter(row=>["قيد التقييم","بانتظار القرار","مقبولة","غير مناسبة حاليًا"].includes(row.status));
  return <div className="space-y-5"><PageHeader title="التقييم والقرارات" description="المشاركات المحالة للجهات المختصة، وتوصيات المقيمين، والقرارات المسجلة قبل إدراج الحل المقبول في المحفظة."/><div className="grid gap-4 lg:grid-cols-3">{[["قيد تقييم الإدارة",rows.filter(row=>row.status==="قيد التقييم").length],["بانتظار القرار",rows.filter(row=>row.status==="بانتظار القرار").length],["مقبولة ومرتبطة بالمحفظة",rows.filter(row=>row.status==="مقبولة").length]].map(([label,value])=><Card key={label}><CardContent className="p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></CardContent></Card>)}</div><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-xs"><thead><tr className="border-b">{["الحل","الجهة المختصة","المقيّم","الحالة","الإجراء التالي"].map(label=><th key={label} className="p-3 text-start">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-3 font-semibold">{row.name}</td><td className="p-3">{row.department}</td><td className="p-3">{row.owner}</td><td className="p-3"><Badge variant={statusVariant(row.status)}>{row.status}</Badge></td><td className="p-3"><Link className="text-primary" href={row.status==="مقبولة"?"/solutions/manual-service":`/solutions/intake/evaluation/${row.id}`}>{row.status==="مقبولة"?"فتح نفس السجل في المحفظة":"فتح التقييم والقرار"}<ArrowLeft className="inline h-3.5 w-3.5"/></Link></td></tr>)}</tbody></table></div></CardContent></Card></div>;
}

export function CreateIntakePagePreview() {
  const [created,setCreated]=useState(false);
  const submit=(event:FormEvent)=>{event.preventDefault();setCreated(true);};
  if(created)return <div className="mx-auto max-w-2xl space-y-5"><Card className="border-emerald-200"><CardContent className="space-y-4 p-8 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600"/><h1 className="text-xl font-bold">تم إنشاء صفحة الاستقبال في المعاينة</h1><p className="text-sm text-muted">الرابط تجريبي ولا ينشئ سجلًا على الخادم.</p><div className="rounded-xl bg-slate-50 p-4 font-mono text-sm" dir="ltr">/submit/innovation-ideas</div><div className="flex justify-center gap-2"><Button asChild><Link href="/submit/innovation-ideas">معاينة الصفحة العامة</Link></Button><Button asChild variant="outline"><Link href="/solutions/intake">العودة إلى الاستقبال</Link></Button></div></CardContent></Card></div>;
  return <div className="space-y-5"><PageHeader title="إنشاء صفحة استقبال أفكار" description="إعداد واجهة استقبال محددة الجمهور والغرض. الحفظ هنا مرئي داخل المعاينة فقط."/><form onSubmit={submit}><Card><CardContent className="grid gap-5 p-6 md:grid-cols-2">
    <Field label="اسم الصفحة"><Input required defaultValue="بوابة الابتكار العامة"/></Field><Field label="الجمهور المستهدف"><select required className={fieldClass}><option>الجمهور والموظفون</option><option>موظفو الجهة</option><option>المستفيدون</option></select></Field>
    <Field label="وصف/غرض الصفحة" wide><textarea required className={fieldClass} rows={3} defaultValue="استقبال الأفكار والحلول التي تحسن خدمات الجهة وتجربة المستفيد."/></Field>
    <Field label="الإدارة المالكة"><Input required defaultValue="إدارة الابتكار المؤسسي"/></Field><Field label="المسؤول"><Input required defaultValue="نورة العتيبي"/></Field>
    <Field label="تاريخ البداية"><Input required type="date" defaultValue="2026-09-01"/></Field><Field label="تاريخ الإغلاق (اختياري)"><Input type="date"/></Field>
    <Field label="نوع الاستقبال"><select className={fieldClass}><option>كلاهما</option><option>فكرة ابتكارية</option><option>حل ابتكاري</option></select></Field><Field label="الرابط المخصص"><div className="mt-1.5 flex items-center rounded-xl border bg-slate-50 px-3 text-sm" dir="ltr"><span>/submit/</span><input className="min-w-0 flex-1 bg-transparent p-2 outline-none" defaultValue="innovation-ideas"/></div></Field>
    <Field label="تعليمات للمشارك" wide><textarea className={fieldClass} rows={3} defaultValue="اشرح المشكلة والحل المقترح بوضوح، وأرفق ما يتوفر من وثائق داعمة."/></Field>
    <label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" defaultChecked/> الاستقبال مفتوح بشكل دائم</label>
    <div className="flex gap-2 md:col-span-2"><Button type="submit">إنشاء الصفحة التجريبية</Button><Button asChild variant="outline"><Link href="/solutions/intake">إلغاء</Link></Button></div>
  </CardContent></Card></form></div>;
}

export function PublicIdeaSubmissionPreview() {
  const [submitted,setSubmitted]=useState(false);
  if(submitted)return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-12"><Card className="mx-auto max-w-2xl"><CardContent className="space-y-4 p-10 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><h1 className="text-xl font-bold">تم استلام مشاركتك</h1><p className="text-sm text-muted">الرقم المرجعي: INN-2026-041. يمكنك متابعة الحالة من صفحة «مشاركاتي».</p><Button asChild><Link href="/solutions/intake/my-submissions">فتح مشاركاتي</Link></Button></CardContent></Card></main>;
  return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-4xl"><div className="mb-6 text-center"><p className="text-sm font-semibold text-primary">بوابة الابتكار العامة</p><h1 className="mt-2 text-2xl font-bold">شارك فكرتك أو حلك الابتكاري</h1><p className="mt-2 text-sm text-muted">نراجع كل مشاركة ونطلعك على حالتها والإجراء المطلوب.</p></div><form onSubmit={event=>{event.preventDefault();setSubmitted(true);}} className="space-y-5">
    <PublicSection title="بيانات المشارك"><Field label="اسم صاحب الفكرة"><Input required defaultValue="هند الشمري"/></Field><Field label="البريد"><Input required type="email" defaultValue="hind@example.sa"/></Field><Field label="الجهة/الإدارة"><Input defaultValue="إدارة تجربة المستفيد"/></Field></PublicSection>
    <PublicSection title="الفكرة أو الحل"><Field label="اسم الفكرة/الحل" wide><Input required defaultValue="مسار رقمي موحد لطلبات المستفيد"/></Field><Field label="وصف الفكرة"><textarea required className={fieldClass} rows={4}/></Field><Field label="المشكلة التي تعالجها"><textarea required className={fieldClass} rows={4}/></Field><Field label="الفئة المستهدفة"><Input/></Field><Field label="عدد المستفيدين المتوقع"><Input type="number"/></Field></PublicSection>
    <PublicSection title="التنفيذ والأثر"><Field label="التكلفة التقديرية"><Input type="number"/></Field><Field label="مدة الإنجاز"><Input placeholder="مثال: 6 أشهر"/></Field><Field label="التقنيات المستخدمة"><Input placeholder="مثال: أتمتة، تحليل بيانات"/></Field><Field label="المرحلة الحالية"><select className={fieldClass}><option>فكرة أولية</option><option>نموذج أولي</option><option>إثبات مفهوم PoC</option><option>حل قائم</option></select></Field><Field label="الأثر المتوقع" wide><textarea className={fieldClass} rows={3}/></Field><div className="grid gap-3 md:col-span-2 sm:grid-cols-3">{["يوجد نموذج أولي","يوجد PoC","توجد دراسة جدوى"].map(label=><label key={label} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox"/>{label}</label>)}</div></PublicSection>
    <PublicSection title="المرفقات والملاحظات"><Field label="المرفقات"><Input type="file" multiple/></Field><Field label="ملاحظات إضافية"><textarea className={fieldClass} rows={3}/></Field></PublicSection>
    <p className="text-xs text-muted">الإرسال لا يعني قبول الفكرة أو إضافتها تلقائيًا إلى محفظة الحلول.</p><Button type="submit" size="lg"><Send className="h-4 w-4"/>إرسال للمراجعة</Button>
  </form></div></main>;
}

export function IntakeInboxPreview() {
  return <div className="space-y-5"><PageHeader title="الوارد من الأفكار والحلول" description="مشاركات تنتظر فرز فريق الابتكار أو إحالتها إلى الإدارة المختصة."/><Card><CardHeader><CardTitle>البحث والتصفية</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><select className={fieldClass}><option>كل الحالات</option><option>قيد المراجعة</option><option>يحتاج استكمال</option><option>قيد التقييم</option></select><select className={fieldClass}><option>كل الإدارات</option><option>تقنية المعلومات</option><option>إدارة المرافق</option></select><Input className="mt-1.5" type="date"/><select className={fieldClass}><option>كل مصادر الاستقبال</option>{intakePages.map(page=><option key={page.id}>{page.name}</option>)}</select></CardContent></Card><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-xs"><thead><tr className="border-b">{["الفكرة/الحل","مقدم الطلب","الإدارة","تاريخ الاستلام","المرحلة","حالة المراجعة","الجهة المختصة","المسؤول","الإجراء التالي"].map(x=><th className="p-3 text-start" key={x}>{x}</th>)}</tr></thead><tbody>{submissions.map(row=><tr className="border-b last:border-0" key={row.id}><td className="p-3"><Link className="font-semibold text-primary" href={`/solutions/intake/submissions/${row.id}`}>{row.name}</Link></td><td className="p-3">{row.submitter}</td><td className="p-3">{row.department}</td><td className="p-3">{row.received}</td><td className="p-3">{row.stage}</td><td className="p-3"><Badge variant={statusVariant(row.status)}>{row.status}</Badge></td><td className="p-3">{row.department}</td><td className="p-3">{row.owner}</td><td className="p-3"><Link className="text-primary" href={`/solutions/intake/submissions/${row.id}`}>{row.next} <ArrowLeft className="inline h-3 w-3"/></Link></td></tr>)}</tbody></table></div></CardContent></Card></div>;
}

export function MySubmissionsPreview() {
  const [resubmitted,setResubmitted]=useState(false);
  const own=submissions.slice(0,2);
  return <div className="space-y-5"><PageHeader title="مشاركاتي" description="متابعة الأفكار والحلول التي قدمتها، وملاحظات فريق الابتكار والإجراء المطلوب منك." action={<Button asChild><Link href="/submit/innovation-ideas"><Plus className="h-4 w-4"/>مشاركة جديدة</Link></Button>}/>{resubmitted?<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">أعيد إرسال المشاركة بعد الاستكمال — الحالة الآن «قيد المراجعة».</p>:null}<div className="space-y-4">{own.map((row,index)=><Card key={row.id}><CardContent className="grid gap-4 p-5 md:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{row.name}</h2><Badge variant={statusVariant(index===1&&!resubmitted?"يحتاج استكمال":"قيد المراجعة")}>{index===1&&!resubmitted?"يحتاج استكمال":"قيد المراجعة"}</Badge></div><div className="mt-3 grid gap-2 text-xs text-muted sm:grid-cols-3"><span>تاريخ التقديم: {row.received}</span><span>آخر تحديث: اليوم 10:20</span><span>الرقم: INN-2026-0{index+40}</span></div><div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>ملاحظات الفريق:</b> {index===1&&!resubmitted?"نحتاج إرفاق دراسة الجدوى وتحديد العدد المتوقع للمستفيدين.":"تم الاستلام وستصلك نتيجة المراجعة هنا."}</div></div><div className="flex flex-col justify-center gap-2"><Button asChild size="sm" variant="outline"><Link href={`/solutions/intake/my-submissions/${row.id}`}>فتح المشاركة</Link></Button>{index===1&&!resubmitted?<Button size="sm" onClick={()=>setResubmitted(true)}>استكمال وإعادة إرسال</Button>:null}</div></CardContent></Card>)}</div></div>;
}

export function SubmissionReviewPreview({ id, innovatorView=false }: { id: string; innovatorView?: boolean }) {
  const source=submissions.find(item=>item.id===id)??submissions[0];
  const [status,setStatus]=useState<SubmissionState>(source.status);
  const [notice,setNotice]=useState("");
  const [messages,setMessages]=useState(["فريق الابتكار: تم استلام المشاركة وبدء مراجعتها.", "هند الشمري: أرفقت وصفًا محدثًا للفئة المستهدفة."]);
  const act=(next:SubmissionState,message:string)=>{setStatus(next);setNotice(message);setMessages(current=>[...current,`تحديث الحالة: ${message}`]);};
  return <div className="space-y-5"><Link href={innovatorView?"/solutions/intake/my-submissions":"/solutions/intake/inbox"} className="text-xs text-muted">العودة</Link><PageHeader title={source.name} description={`المشاركة INN-2026-${source.id === "new-service" ? "040" : "041"} · ${source.submitter}`} action={<Badge variant={statusVariant(status)}>{status}</Badge>}/>{notice?<p className="rounded-xl bg-primary-50 p-4 text-sm text-primary-700">{notice} — تحديث معاينة فقط.</p>:null}
    <nav className="flex gap-2 overflow-x-auto" aria-label="أقسام المشاركة">{["نظرة عامة","بيانات الفكرة/الحل","المرفقات","ملاحظات فريق الابتكار","تقييم الجهة المختصة","القرار","المتابعة","السجل"].map((x,i)=><a key={x} href={`#intake-${i}`} className="whitespace-nowrap rounded-full border px-3 py-1.5 text-xs">{x}</a>)}</nav>
    <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><Card id="intake-0"><CardHeader><CardTitle>نظرة عامة</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{[["مقدم الطلب",source.submitter],["الإدارة",source.department],["المصدر",source.source],["تاريخ الاستلام",source.received],["المسؤول",source.owner],["الإجراء التالي",source.next]].map(([a,b])=><div className="rounded-xl border p-3" key={a}><p className="text-xs text-muted">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p></div>)}</CardContent></Card>
      <Card id="intake-1"><CardHeader><CardTitle>بيانات الفكرة/الحل</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><b>المشكلة:</b> تعدد القنوات وصعوبة معرفة مسار الطلب المناسب.</p><p><b>القيمة المقترحة:</b> نقطة دخول موحدة تقلل الوقت وتوضح حالة الطلب.</p><div className="grid gap-3 sm:grid-cols-3"><Info label="التكلفة" value="180,000 ر.س"/><Info label="المدة" value="6 أشهر"/><Info label="المستفيدون" value="3,200 مستفيد"/><Info label="التقنية" value="أتمتة وتحليل بيانات"/><Info label="المرحلة" value={source.stage}/><Info label="الأثر المتوقع" value="خفض زمن المعالجة 25%"/></div></CardContent></Card>
      <Card id="intake-2"><CardHeader><CardTitle>المرفقات</CardTitle></CardHeader><CardContent className="space-y-2">{["وصف الفكرة.pdf","مخطط النموذج الأولي.png"].map(x=><div key={x} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><FileText className="h-4 w-4 text-primary"/>{x}<Badge className="ms-auto" variant="neutral">مرفق</Badge></div>)}</CardContent></Card>
      <Card id="intake-3"><CardHeader><CardTitle>الملاحظات والمتابعة</CardTitle></CardHeader><CardContent className="space-y-3">{messages.map((message,index)=><div key={`${message}-${index}`} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-sm"><MessageSquare className="mt-0.5 h-4 w-4 text-primary"/><div><p>{message}</p><p className="mt-1 text-xs text-muted">اليوم، {10+index}:20</p></div></div>)}{!innovatorView?<Button size="sm" variant="outline" onClick={()=>setMessages(current=>[...current,"فريق الابتكار: يرجى توضيح آلية قياس الأثر المتوقع."])}>إضافة ملاحظة</Button>:null}</CardContent></Card>
      {!innovatorView?<DepartmentEvaluationPanel onRecommend={()=>act("بانتظار القرار","سُجلت توصية الإدارة وأحيلت لصاحب القرار")}/>:null}
      {!innovatorView?<Card id="intake-5"><CardHeader><CardTitle>القرار</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><select className={fieldClass}><option>قبول وإضافة للمحفظة</option><option>يحتاج تطوير</option><option>يحتاج استكمال</option><option>غير مناسب حاليًا</option><option>مكرر / موجود مسبقًا</option></select><Input className="mt-1.5" placeholder="سبب القرار" defaultValue="الحل قابل للتجربة ومرتبط باحتياج واضح"/></div><div className="text-xs text-muted">صاحب القرار: مدير إدارة الابتكار · التاريخ: 5 سبتمبر 2026</div><Button onClick={()=>act("مقبولة","قُبلت المشاركة وربطت بمحفظة الحلول دون إنشاء سجل مكرر")}>تسجيل القبول وربطها بالمحفظة</Button>{status==="مقبولة"?<p className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="h-4 w-4"/>أصبحت المشاركة مرتبطة بسجل «بوابة المواعيد الاستباقية» في محفظة الحلول.</p>:null}</CardContent></Card>:null}
    </div><aside className="space-y-4">{!innovatorView?<Card><CardHeader><CardTitle>إجراءات المراجعة</CardTitle></CardHeader><CardContent className="space-y-2"><Button className="w-full" variant="outline" onClick={()=>act("يحتاج استكمال","أُرسل طلب استكمال إلى المبتكر")}>طلب استكمال</Button><Button className="w-full" variant="outline" onClick={()=>act("محالة للإدارة المختصة","أُحيلت إلى إدارة تقنية المعلومات")}>إحالة للإدارة المختصة</Button><Button className="w-full" variant="outline" onClick={()=>act("قيد التقييم","عُيّن ماجد السالم مقيّمًا")}>تعيين مقيّم</Button><Button className="w-full" variant="outline" onClick={()=>setNotice("سُجلت توصية فريق الابتكار")}>تسجيل توصية</Button></CardContent></Card>:null}<Card><CardHeader><CardTitle>مسار المشاركة</CardTitle></CardHeader><CardContent className="space-y-3 text-xs">{["تم الاستلام","مراجعة فريق الابتكار",status,status==="مقبولة"?"مرتبطة بالمحفظة":"القرار التالي"].map((x,i)=><div className="flex gap-2" key={`${x}-${i}`}><Clock3 className="h-4 w-4 text-primary"/><span>{x}</span></div>)}</CardContent></Card></aside></div>
  </div>;
}

function DepartmentEvaluationPanel({onRecommend}:{onRecommend:()=>void}) {
  return <Card id="intake-4"><CardHeader><CardTitle>تقييم الجهة المختصة</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2">{["الملاءمة مع احتياج الجهة","قابلية التنفيذ","القيمة المتوقعة","مستوى الجاهزية"].map(label=><Field label={label} key={label}><select className={fieldClass}><option>مرتفع</option><option>متوسط</option><option>منخفض</option></select></Field>)}<Field label="ملاحظات" wide><textarea className={fieldClass} rows={3} defaultValue="يمكن تنفيذ تجربة محدودة خلال ستة أشهر بعد استكمال تكامل البيانات."/></Field><Field label="التوصية" wide><select className={fieldClass}><option>موصى بالقبول للتجربة</option><option>يحتاج تطوير</option><option>غير موصى به حاليًا</option></select></Field></div><Button onClick={onRecommend}>حفظ التقييم التجريبي</Button><p className="text-xs text-muted">لا توجد أوزان أو درجة آلية، والتقييم لا يستخدم الذكاء الاصطناعي.</p></CardContent></Card>;
}

function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}) { return <label className={wide?"md:col-span-2":""}><Label>{label}</Label>{children}</label>; }
function PublicSection({title,children}:{title:string;children:React.ReactNode}) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="grid gap-5 md:grid-cols-2">{children}</CardContent></Card>; }
function Info({label,value}:{label:string;value:string}) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
