import { AlertTriangle, ArrowLeft, Download, FileSpreadsheet, Link2, Plus, Route } from "lucide-react";
import { PreviewLink as Link } from "@/components/layout/preview-link";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { PreviewPersonaKey } from "@/lib/ux-preview";
import { PREVIEW_PORTFOLIO_SOLUTIONS } from "../portfolio";

const summaries = [
  ["إجمالي الحلول", "7", "all"], ["تشغيلية", "1", "operational"], ["قيد التنفيذ", "2", "active"],
  ["PoC / Prototype", "2", "poc"], ["تحتاج استكمال", "2", "incomplete"], ["مهام متأخرة", "2", "overdue"],
  ["حلول محتملة التكرار", "1", "duplicates"],
] as const;

function IntakeSubmissions({ editable }: { editable: boolean }) {
  const rows = [
    ["INT-026", "منصة متابعة طلبات الدعم الموحدة", "تقنية المعلومات", "رابط حصر الحلول", "بانتظار المراجعة", "فتح ومراجعة"],
    ["IMP-014", "لوحة مراقبة جودة البيانات", "إدارة البيانات", "استيراد Excel", "يحتاج استكمال", "استكمال الحقول"],
    ["INT-031", "مساعد المستفيد الرقمي", "إدارة القنوات الرقمية", "رابط حصر الحلول", "تكرار محتمل", "مقارنة وربط"],
  ];
  return <Card><CardHeader><CardTitle>الحلول المستلمة</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead><tr className="border-b text-muted">{["رقم","اسم الحل","الإدارة","المصدر","الحالة","الإجراء"].map(x=><th key={x} className="p-3 text-start">{x}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row[0]} className="border-b last:border-0">{row.map((cell,i)=><td key={cell} className="p-3">{i===5&&editable?<Link href={`/solutions/${index===2?"duplicate-assistant":index===1?"excel-import":"intake-queue"}`} className="font-semibold text-primary">{cell}<ArrowLeft className="inline h-3.5 w-3.5"/></Link>:cell}</td>)}</tr>)}</tbody></table></div></CardContent></Card>;
}

export function SolutionPortfolioPreview({ persona }: { persona: PreviewPersonaKey }) {
  const editable = persona === "admin" || persona === "internal";
  const rows = persona === "partner" ? PREVIEW_PORTFOLIO_SOLUTIONS.slice(4,5) : persona === "viewer" ? PREVIEW_PORTFOLIO_SOLUTIONS.filter(x=>x.status==="تشغيلي") : PREVIEW_PORTFOLIO_SOLUTIONS;
  return <div className="flex flex-col gap-5">
    <PageHeader title="حصر الحلول الابتكارية" description="محفظة مؤسسية تشغيلية لجمع الحلول وتصنيفها وتحديد ملكيتها ومتابعتها ومنع التكرار. الجاهزية المعروضة داخلية تقديرية وليست اعتمادًا رسميًا." action={editable?<Button asChild><Link href="/solutions/new"><Plus className="h-4 w-4"/>إضافة حل ابتكاري</Link></Button>:undefined}/>
    {editable?<div className="flex flex-wrap gap-2">
      <Button asChild size="sm" variant="outline"><Link href="/solutions/intake-links"><Link2 className="h-4 w-4"/>إنشاء رابط حصر الحلول</Link></Button>
      <Button asChild size="sm" variant="outline"><Link href="/solutions/import"><FileSpreadsheet className="h-4 w-4"/>استيراد من Excel</Link></Button>
      <Button asChild size="sm" variant="outline"><Link href="/solutions/from-existing"><Route className="h-4 w-4"/>إضافة من مخرجات سابقة</Link></Button>
      <Button asChild size="sm" variant="outline"><Link href="/solutions/export"><Download className="h-4 w-4"/>تصدير سجل الحلول</Link></Button>
    </div>:null}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{summaries.map(([label,value,filter])=><Link key={label} href={`/solutions?portfolioFilter=${filter}`}><Card className="h-full transition hover:border-primary/50"><CardContent className="p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></CardContent></Card></Link>)}</div>
    <Card><CardHeader><CardTitle>البحث والتصفية</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><input className="rounded-xl border px-3 py-2 text-sm" placeholder="ابحث باسم الحل أو الإدارة…"/><select className="rounded-xl border px-3 py-2 text-sm"><option>كل الإدارات</option><option>إدارة تجربة المستفيد</option><option>إدارة المرافق</option></select><select className="rounded-xl border px-3 py-2 text-sm"><option>كل مراحل النضج</option><option>إثبات مفهوم PoC</option><option>نموذج أولي Prototype</option><option>تشغيل فعلي</option></select><select className="rounded-xl border px-3 py-2 text-sm"><option>كل الحالات</option><option>قيد المراجعة</option><option>قيد التنفيذ</option><option>تشغيلي</option></select></CardContent></Card>
    <Card><CardHeader><CardTitle>محفظة الحلول الابتكارية</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-xs"><thead><tr className="border-b text-muted">{["اسم الحل","الإدارة","المالك","المصدر","المرحلة","الحالة","المستفيدون","اكتمال البيانات","المهام المفتوحة","الإجراء التالي"].map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-3"><Link href={`/solutions/${row.id}`} className="font-semibold text-primary hover:underline">{row.nameAr}</Link>{row.duplicateOf?<p className="mt-1 flex items-center gap-1 text-amber-700"><AlertTriangle className="h-3 w-3"/>قد يكون هذا الحل مسجلًا مسبقًا</p>:null}</td><td className="p-3">{row.department}</td><td className="p-3">{row.owner}</td><td className="p-3">{row.source}</td><td className="p-3"><Badge variant="neutral">{row.maturity}</Badge></td><td className="p-3">{row.status}</td><td className="p-3">{row.beneficiaries}</td><td className="p-3"><Progress value={row.readiness}/><span>{row.readiness}%</span></td><td className="p-3">{row.tasks}</td><td className="p-3"><Link href={`/solutions/${row.id}#next-action`} className="text-primary">{row.nextAction}<ArrowLeft className="inline h-3.5 w-3.5"/></Link></td></tr>)}</tbody></table></div></CardContent></Card>
    {persona!=="viewer"?<IntakeSubmissions editable={editable}/>:null}
  </div>;
}

export function SolutionWorkspacePreview({ id, persona }: { id: string; persona: PreviewPersonaKey }) {
  const solution=PREVIEW_PORTFOLIO_SOLUTIONS.find(x=>x.id===id)??PREVIEW_PORTFOLIO_SOLUTIONS[0];
  const editable=persona==="admin"||persona==="internal";
  const sections=["نظرة عامة","بيانات الحل","الارتباط الاستراتيجي","المستفيدون","التقنية","النضج والتنفيذ","التكلفة والمدة","مراحل التنفيذ","الأثر","المهام والمساهمون","الأدلة والوثائق","السجل"];
  return <div className="flex flex-col gap-5"><Link href="/solutions" className="text-xs text-muted">العودة إلى محفظة الحلول</Link><PageHeader title={solution.nameAr} description={`${solution.department} · ${solution.source}`} action={editable?<Button asChild><Link href="/solutions/new">تحديث بيانات الحل</Link></Button>:<Badge variant="neutral">للقراءة فقط</Badge>}/>
    {solution.duplicateOf?<Card className="border-amber-300 bg-amber-50"><CardContent className="flex flex-wrap items-center gap-3 p-4"><AlertTriangle className="h-5 w-5 text-amber-700"/><div className="flex-1"><p className="font-semibold">قد يكون هذا الحل مسجلًا مسبقًا</p><p className="text-xs text-muted">تطابق حتمي مع «المساعد الرقمي لخدمات المستفيدين». لن يُنشأ سجل مؤسسي نشط آخر تلقائيًا.</p></div><Button asChild size="sm" variant="outline"><Link href="/solutions/citizen-assistant">فتح السجل الموجود</Link></Button><Button asChild size="sm"><Link href="/solutions/citizen-assistant?linkedSubmission=duplicate-assistant">ربط الطلب بالسجل الموجود</Link></Button></CardContent></Card>:null}
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="أقسام الحل">{sections.map((s,i)=><Link key={s} href={`#section-${i}`} className="whitespace-nowrap rounded-full border px-3 py-1.5 text-xs hover:border-primary">{s}</Link>)}</nav>
    <div className="grid gap-5 lg:grid-cols-3"><div className="space-y-5 lg:col-span-2">
      <Card id="section-0"><CardHeader><CardTitle>نظرة عامة</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{[["مرحلة النضج",solution.maturity],["الحالة التشغيلية",solution.status],["مالك الحل",solution.owner],["الإجراء التالي",solution.nextAction],["المستفيدون",solution.beneficiaries],["التقنيات الناشئة",solution.technology.join("، ")]].map(([label,value])=><div key={label} className="rounded-xl border p-3"><p className="text-xs text-muted">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>)}</CardContent></Card>
      <Card id="section-2"><CardHeader><CardTitle>مصدر ومنهجية الابتكار والارتباط الاستراتيجي</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>هاكاثون/مبادرة مؤسسية ← التفكير التصميمي ← جلسة توليد الحلول ← الحل الحالي</p><div className="rounded-xl bg-slate-50 p-3 text-xs">الحل ← هدف الابتكار: تحسين تجربة المستفيد ← الهدف الاستراتيجي: رفع جودة الخدمات ← هدف التحول الرقمي: خدمات رقمية استباقية</div></CardContent></Card>
      <Card id="section-3"><CardHeader><CardTitle>الفئات والمستفيدون</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-3"><p className="font-semibold">المستفيدون الخارجيون</p><p className="text-xs text-muted">أفراد يستخدمون الخدمات الرقمية · {solution.beneficiaries}</p></div><div className="rounded-xl border p-3"><p className="font-semibold">موظفو مراكز الاتصال</p><p className="text-xs text-muted">استخدام تشغيلي داخلي · 86 موظفًا</p></div></CardContent></Card>
      <Card id="section-7"><CardHeader><CardTitle>تقرير مراحل التنفيذ</CardTitle></CardHeader><CardContent className="space-y-3">{[["فهم المشكلة","15 يناير 2026","اعتماد نطاق المشكلة"],["إثبات المفهوم","20 مارس 2026","نجاح اختبار المسار"],["التجربة التشغيلية","10 يونيو 2026","إطلاق محدود"],["التشغيل","1 أغسطس 2026","متابعة الاستخدام والرضا"]].map(([stage,date,result],index)=><div key={stage} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary text-xs text-white">{index+1}</span><div><p className="text-sm font-semibold">{stage}</p><p className="text-xs text-muted">{date} · {result}</p></div></div>)}</CardContent></Card>
      <Card id="section-9"><CardHeader><CardTitle>المهام والمساهمون</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-xl border p-3"><p className="text-sm font-semibold">{solution.nextAction}</p><p className="text-xs text-muted">المسؤول: {solution.owner} · الموعد: 30 سبتمبر 2026</p></div>{editable?<div className="flex flex-wrap gap-2"><Button asChild size="sm"><Link href={`/my-tasks?solutionId=${solution.id}`}>إضافة مهمة / فتح مهامي</Link></Button><Button asChild size="sm" variant="outline"><Link href={`/solutions/${solution.id}?delegate=beneficiaries`}>إسناد جزء لمساهم</Link></Button></div>:null}</CardContent></Card>
      <Card id="section-10"><CardHeader><CardTitle>الأدلة والوثائق</CardTitle></CardHeader><CardContent className="space-y-2">{["مفهوم الحل — معتمد داخليًا","إثبات المفهوم — قيد المراجعة","تقرير التنفيذ — إصدار 2","قياس رضا المستفيدين — يحتاج تحديث"].map(item=><div key={item} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{item}</span><Button asChild size="sm" variant="outline"><Link href={`/solutions/${solution.id}/evidence`}>فتح</Link></Button></div>)}</CardContent></Card>
    </div><aside className="space-y-5"><Card><CardHeader><CardTitle>الجاهزية الداخلية التقديرية</CardTitle></CardHeader><CardContent><Progress value={solution.readiness}/><p className="mt-2 text-xs text-muted">{solution.readiness}% — بيانات وملكية وربط ومستفيدون ووثائق ومهام؛ ليست اعتمادًا رسميًا.</p></CardContent></Card><Card id="next-action"><CardHeader><CardTitle>وش المطلوب مني الآن؟</CardTitle></CardHeader><CardContent><p className="text-sm font-semibold">{solution.nextAction}</p>{editable?<Button asChild className="mt-3" size="sm"><Link href={`/my-tasks?solutionId=${solution.id}`}>فتح الإجراء</Link></Button>:null}</CardContent></Card><Card><CardHeader><CardTitle>مصدر السجل</CardTitle></CardHeader><CardContent className="text-xs"><p>{solution.source}</p><p className="mt-2 text-muted">سلسلة التتبع محفوظة دون نسخ سجل المصدر.</p></CardContent></Card></aside></div>
  </div>;
}

export function SolutionPortfolioUtilityPreview({ kind, persona }: { kind: "links"|"import"|"existing"|"export"; persona: PreviewPersonaKey }) {
  const editable=persona==="admin"||persona==="internal";
  if(!editable)return <div className="py-16 text-center"><p className="font-semibold">هذه الأداة متاحة للمخولين داخل الجهة فقط.</p><Button asChild className="mt-4" variant="outline"><Link href="/solutions">العودة إلى المحفظة</Link></Button></div>;
  const config={links:["روابط حصر الحلول","إنشاء روابط محددة النطاق واستعراض الحلول المستلمة دون منح وصول للمنصة."],import:["استيراد حلول من Excel / CSV","رفع الملف ثم معاينة الصفوف وربط الأعمدة والتحقق من النواقص والتكرار قبل التأكيد."],existing:["إضافة من مخرجات سابقة","اختيار نشاط أو منهجية أو نموذج أولي موجود وربطه بسجل حل واحد دون إعادة إدخال البيانات."],export:["تصدير سجل الحلول","تصدير البيانات المؤسسية المسموح بها وفق المرشحات الحالية دون بيانات الدعوات الخاصة."]}[kind];
  return <div className="flex flex-col gap-5"><PageHeader title={config[0]} description={config[1]}/>
    {kind==="links"?<Card><CardContent className="space-y-3 p-5">{[["حصر حلول إدارة تقنية المعلومات","نشط","4 حلول مستلمة"],["حصر المبادرات الابتكارية لعام 2026","نشط","7 حلول مستلمة"],["حصر مخرجات هاكاثونات الجهة","مغلق","3 حلول مستلمة"]].map(row=><div key={row[0]} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-semibold">{row[0]}</p><p className="text-xs text-muted">{row[1]} · {row[2]}</p></div><Button asChild size="sm" variant="outline"><Link href="/solution-intake/preview-2026">فتح نموذج الاستقبال</Link></Button></div>)}<Button asChild><Link href="/preview-form/solution"><Plus className="h-4 w-4"/>إعداد رابط جديد</Link></Button></CardContent></Card>:null}
    {kind==="import"?<Card><CardContent className="space-y-4 p-5"><div className="rounded-xl border border-dashed p-8 text-center"><FileSpreadsheet className="mx-auto text-primary"/><p className="mt-2 font-semibold">ملف solutions-2026.xlsx</p><p className="text-xs text-muted">تمت قراءة 6 صفوف. لن تُحفظ قبل التأكيد.</p></div><div className="grid gap-2 sm:grid-cols-4">{[["Solution Name","اسم الحل"],["Department","الإدارة المالكة"],["Stage","مرحلة النضج"],["Beneficiaries","عدد المستفيدين"]].map(([source,target])=><div key={source} className="rounded-xl border p-3 text-xs"><p>{source}</p><p className="mt-1 text-primary">← {target}</p></div>)}</div><p className="text-xs text-amber-700">4 صالحة · 1 تحتاج مراجعة · 1 تكرار محتمل. لن يُستورد صف غير صالح بصمت.</p><Button asChild><Link href="/solutions?portfolioFilter=imported">تأكيد استيراد الصفوف الصالحة</Link></Button></CardContent></Card>:null}
    {kind==="existing"?<Card><CardContent className="space-y-3 p-5">{[["هاكاثون المدن المستدامة 2026","فعالية ابتكارية","3 مخرجات"],["تطبيق التفكير التصميمي لتحسين الخدمة","منهجية ابتكار","2 نماذج أولية"],["مبادرة إدارة الطاقة","مبادرة مؤسسية","حل واحد"]].map((row,index)=><div key={row[0]} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-semibold">{row[0]}</p><p className="text-xs text-muted">{row[1]} · {row[2]}</p></div><Button asChild size="sm"><Link href={`/solutions/${index===0?"hackathon-transfer":"energy-poc"}`}>اختيار وربط</Link></Button></div>)}</CardContent></Card>:null}
    {kind==="export"?<Card><CardContent className="flex flex-wrap gap-3 p-5"><Button asChild><Link href="/solutions?exported=csv"><Download className="h-4 w-4"/>تنزيل CSV</Link></Button><Button asChild variant="outline"><Link href="/solutions?exported=xlsx"><Download className="h-4 w-4"/>تنزيل XLSX</Link></Button><Button asChild variant="outline"><Link href="/solutions?print=1">عرض مهيأ للطباعة</Link></Button></CardContent></Card>:null}
  </div>;
}
