import { AlertTriangle, ArrowLeft, Download, FileSpreadsheet, Link2, Plus, Route, Users } from "lucide-react";
import { PreviewLink as Link } from "@/components/layout/preview-link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { PageHeader } from "@/components/shared/page-header";
import { PREVIEW_PORTFOLIO_SOLUTIONS } from "../portfolio";
import type { PreviewPersonaKey } from "@/lib/ux-preview";

const summary = [["إجمالي الحلول","6"],["تشغيلية","1"],["قيد التطوير","2"],["تحتاج استكمال","2"],["مهام متأخرة","2"],["بدون مالك","1"],["بدون أثر","3"],["تكرار محتمل","1"]];

export function SolutionPortfolioPreview({ persona }: { persona: PreviewPersonaKey }) {
  const editable = persona === "admin" || persona === "internal";
  const rows = persona === "partner" ? PREVIEW_PORTFOLIO_SOLUTIONS.slice(4,5) : persona === "viewer" ? PREVIEW_PORTFOLIO_SOLUTIONS.filter(x=>x.status==="تشغيلي") : PREVIEW_PORTFOLIO_SOLUTIONS;
  return <div className="flex flex-col gap-5">
    <PageHeader title="محفظة الحلول الابتكارية — 5.24.1" description="حصر مؤسسي تشغيلي يجمع الحلول من مصادرها، يمنع التكرار، يحدد الملكية ويتابع اكتمالها. الجاهزية المعروضة داخلية تقديرية وليست اعتمادًا رسميًا." action={editable?<Button asChild><Link href="/solutions/new"><Plus className="h-4 w-4"/>إضافة حل ابتكاري</Link></Button>:undefined}/>
    {editable?<div className="flex flex-wrap gap-2"><Button asChild variant="outline" size="sm"><Link href="/solutions/intake-links"><Link2 className="h-4 w-4"/>إنشاء رابط استقبال حلول</Link></Button><Button asChild variant="outline" size="sm"><Link href="/solutions/import"><FileSpreadsheet className="h-4 w-4"/>استيراد Excel / CSV</Link></Button><Button asChild variant="outline" size="sm"><Link href="/solutions/from-existing"><Route className="h-4 w-4"/>إضافة من مخرجات سابقة</Link></Button><Button asChild variant="outline" size="sm"><Link href="/solutions/export"><Download className="h-4 w-4"/>تصدير السجل</Link></Button></div>:null}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{summary.map(([label,value],index)=><Link key={label} href={`/solutions?portfolioFilter=${index}`}><Card className="h-full transition hover:border-primary/40"><CardContent className="p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></CardContent></Card></Link>)}</div>
    <Card><CardHeader><CardTitle>سجل الحلول</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-xs"><thead><tr className="border-b text-muted">{["الحل","الإدارة والمالك","المصدر","مرحلة النضج","الحالة التشغيلية","المستفيدون","الجاهزية","المهام","الإجراء التالي"].map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-3"><Link href={`/solutions/${row.id}`} className="font-semibold text-primary hover:underline">{row.nameAr}</Link>{row.duplicateOf?<p className="mt-1 flex items-center gap-1 text-amber-700"><AlertTriangle className="h-3 w-3"/>قد يكون مسجلًا مسبقًا</p>:null}</td><td className="p-3"><p>{row.department}</p><p className="text-muted">{row.owner}</p></td><td className="p-3">{row.source}</td><td className="p-3"><Badge variant="neutral">{row.maturity}</Badge></td><td className="p-3">{row.status}</td><td className="p-3">{row.beneficiaries}</td><td className="p-3"><Progress value={row.readiness}/><span>{row.readiness}%</span></td><td className="p-3">{row.tasks}</td><td className="p-3"><Link href={`/solutions/${row.id}#next-action`} className="text-primary">{row.nextAction}<ArrowLeft className="inline h-3.5 w-3.5"/></Link></td></tr>)}</tbody></table></div></CardContent></Card>
  </div>;
}

export function SolutionWorkspacePreview({ id, persona }: { id: string; persona: PreviewPersonaKey }) {
  const solution=PREVIEW_PORTFOLIO_SOLUTIONS.find(x=>x.id===id)??PREVIEW_PORTFOLIO_SOLUTIONS[0]; const editable=persona==="admin"||persona==="internal";
  const sections=["نظرة عامة","بيانات الحل","الارتباط الاستراتيجي","المستفيدون","التقنية","النضج والتنفيذ","التكلفة والمدة","مراحل التنفيذ","الأثر","المهام والمساهمون","الأدلة والوثائق","السجل"];
  return <div className="flex flex-col gap-5"><Link href="/solutions" className="text-xs text-muted">العودة إلى المحفظة</Link><PageHeader title={solution.nameAr} description={`${solution.department} · ${solution.source}`} action={editable?<Button asChild><Link href="/preview-form/solution">تحديث السجل</Link></Button>:<Badge variant="neutral">للقراءة فقط</Badge>}/>
    {solution.duplicateOf?<Card className="border-amber-300 bg-amber-50"><CardContent className="flex flex-wrap items-center gap-3 p-4"><AlertTriangle className="h-5 w-5 text-amber-700"/><div className="flex-1"><p className="font-semibold">قد يكون هذا الحل مسجلًا مسبقًا</p><p className="text-xs text-muted">تطابق عنوانه بعد التطبيع مع «المساعد الرقمي لخدمات المستفيدين». لا يُنشأ سجل نشط آخر تلقائيًا.</p></div>{editable?<><Button asChild size="sm" variant="outline"><Link href="/solutions/citizen-assistant">فتح السجل الموجود</Link></Button><Button asChild size="sm"><Link href="/solutions/duplicate-assistant?decision=link">ربط الطلب بالسجل</Link></Button></>:null}</CardContent></Card>:null}
    <div className="flex gap-2 overflow-x-auto pb-1">{sections.map((s,i)=><Link key={s} href={`#section-${i}`} className="whitespace-nowrap rounded-full border px-3 py-1.5 text-xs hover:border-primary">{s}</Link>)}</div>
    <div className="grid gap-5 lg:grid-cols-3"><div className="space-y-5 lg:col-span-2">
      <Card id="section-0"><CardHeader><CardTitle>نظرة عامة</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{[["مرحلة النضج",solution.maturity],["الحالة التشغيلية",solution.status],["مالك الحل",solution.owner],["الإجراء التالي",solution.nextAction],["المستفيدون",solution.beneficiaries],["التقنيات",solution.technology.join("، ")]].map(([l,v])=><div key={l} className="rounded-xl border p-3"><p className="text-xs text-muted">{l}</p><p className="mt-1 text-sm font-medium">{v}</p></div>)}</CardContent></Card>
      <Card id="section-2"><CardHeader><CardTitle>مصدر ومنهجية الابتكار والارتباط الاستراتيجي</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>هاكاثون/مبادرة مؤسسية ← تطبيق التفكير التصميمي ← مخرج قابل للتنفيذ ← الحل الحالي</p><div className="rounded-xl bg-slate-50 p-3 text-xs">الحل ← هدف الابتكار: تحسين تجربة المستفيد ← الهدف الاستراتيجي: رفع جودة الخدمات ← هدف التحول الرقمي: خدمات رقمية استباقية</div></CardContent></Card>
      <Card id="section-3"><CardHeader><CardTitle>الفئات والمستفيدون</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-3"><p className="font-semibold">المستفيدون الخارجيون</p><p className="text-xs text-muted">أفراد يستخدمون الخدمات الرقمية · {solution.beneficiaries}</p></div><div className="rounded-xl border p-3"><p className="font-semibold">موظفو مراكز الاتصال</p><p className="text-xs text-muted">استخدام تشغيلي داخلي · 86 موظفًا</p></div></div></CardContent></Card>
      <Card id="section-7"><CardHeader><CardTitle>تقرير مراحل التنفيذ</CardTitle></CardHeader><CardContent className="space-y-3">{[["فهم المشكلة","15 يناير 2026","اعتماد نطاق المشكلة"],["إثبات المفهوم","20 مارس 2026","نجاح اختبار المسار"],["التجربة التشغيلية","10 يونيو 2026","إطلاق محدود"],["التشغيل","1 أغسطس 2026","متابعة الاستخدام والرضا"]].map(([stage,date,result],i)=><div key={stage} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary text-xs text-white">{i+1}</span><div><p className="text-sm font-semibold">{stage}</p><p className="text-xs text-muted">{date} · {result}</p></div></div>)}</CardContent></Card>
      <Card id="section-9"><CardHeader><CardTitle>المهام والمساهمون</CardTitle></CardHeader><CardContent className="space-y-2"><div className="rounded-xl border p-3 text-sm"><p className="font-semibold">{solution.nextAction}</p><p className="text-xs text-muted">المسؤول الحالي: {solution.owner} · الموعد: 30 سبتمبر 2026</p></div>{editable?<div className="flex gap-2"><Button asChild size="sm"><Link href={`/my-tasks?solutionId=${solution.id}`}>إضافة مهمة</Link></Button><Button asChild size="sm" variant="outline"><Link href={`/solutions/${solution.id}?delegate=beneficiaries`}>إسناد جزء لشخص آخر</Link></Button></div>:null}</CardContent></Card>
      <Card id="section-10"><CardHeader><CardTitle>الأدلة والوثائق</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{["مفهوم الحل — معتمد داخليًا","إثبات المفهوم — قيد المراجعة","تقرير التنفيذ — إصدار 2","قياس رضا المستفيدين — يحتاج تحديث"].map(x=><div key={x} className="flex items-center justify-between rounded-xl border p-3"><span>{x}</span><Button asChild size="sm" variant="outline"><Link href={`/solutions/${solution.id}/evidence`}>فتح</Link></Button></div>)}</CardContent></Card>
    </div><div className="space-y-5"><Card><CardHeader><CardTitle>الجاهزية الداخلية التقديرية</CardTitle></CardHeader><CardContent><Progress value={solution.readiness}/><p className="mt-2 text-xs text-muted">{solution.readiness}% — مبنية على اكتمال البيانات والملكية والارتباط والمستفيدين والوثائق والمهام.</p></CardContent></Card><Card id="next-action"><CardHeader><CardTitle>وش المطلوب الآن؟</CardTitle></CardHeader><CardContent><p className="text-sm font-semibold">{solution.nextAction}</p>{editable?<Button asChild className="mt-3" size="sm"><Link href={`/my-tasks?solutionId=${solution.id}`}>فتح الإجراء</Link></Button>:null}</CardContent></Card><Card><CardHeader><CardTitle>مصدر السجل</CardTitle></CardHeader><CardContent className="text-xs"><p>{solution.source}</p><p className="mt-2 text-muted">حُفظت سلسلة التتبع دون نسخ سجل المصدر.</p></CardContent></Card></div></div>
  </div>;
}

export function SolutionPortfolioUtilityPreview({ kind, persona }: { kind: "links"|"import"|"existing"|"export"; persona: PreviewPersonaKey }) {
 const editable=persona==="admin"||persona==="internal"; if(!editable)return <div className="py-16 text-center"><Users className="mx-auto"/><p className="mt-3 font-semibold">هذه الأداة متاحة للمخولين داخل الجهة فقط.</p></div>;
 const config={links:["روابط حصر الحلول","إنشاء روابط محددة النطاق واستعراض الحلول المستلمة دون منح وصول للمنصة."],import:["استيراد حلول من Excel / CSV","رفع الملف ثم معاينة الصفوف وربط الأعمدة والتحقق من النواقص والتكرار قبل التأكيد."],existing:["إضافة من مخرجات سابقة","اختيار نشاط أو منهجية أو نموذج أولي موجود وربطه بسجل حل واحد دون إعادة إدخال البيانات."],export:["تصدير سجل الحلول","تصدير البيانات المؤسسية المسموح بها وفق المرشحات الحالية دون بيانات الدعوات الخاصة."]}[kind];
 return <div className="flex flex-col gap-5"><PageHeader title={config[0]} description={config[1]}/>{kind==="links"?<Card><CardContent className="space-y-3 p-5">{[["حصر حلول إدارة تقنية المعلومات","نشط","4 حلول مستلمة"],["حصر المبادرات الابتكارية لعام 2026","نشط","7 حلول مستلمة"],["حصر مخرجات هاكاثونات الجهة","مغلق","3 حلول مستلمة"]].map(r=><div key={r[0]} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-semibold">{r[0]}</p><p className="text-xs text-muted">{r[1]} · {r[2]}</p></div><Button asChild size="sm" variant="outline"><Link href="/solution-intake/preview-2026">فتح الرابط والاستجابات</Link></Button></div>)}<Button asChild><Link href="/solutions/intake-links?create=1"><Plus className="h-4 w-4"/>إنشاء رابط</Link></Button></CardContent></Card>:kind==="import"?<Card><CardContent className="space-y-4 p-5"><div className="rounded-xl border border-dashed p-8 text-center"><FileSpreadsheet className="mx-auto text-primary"/><p className="mt-2 font-semibold">اختر ملف XLSX أو CSV</p><p className="text-xs text-muted">لن تُحفظ أي صفوف قبل المعاينة والتأكيد.</p></div><div className="grid gap-2 sm:grid-cols-4">{[["اسم الحل","اسم الحل"],["Department","الإدارة المالكة"],["Stage","مرحلة النضج"],["Beneficiaries","عدد المستفيدين"]].map(([a,b])=><div key={a} className="rounded-xl border p-3 text-xs"><p>{a}</p><p className="mt-1 text-primary">← {b}</p></div>)}</div><p className="text-xs text-amber-700">المعاينة: 4 صالحة · 1 تحتاج مراجعة · 1 تكرار محتمل. لن تُستورد الصفوف غير الصالحة بصمت.</p><Button>تأكيد استيراد الصفوف الصالحة</Button></CardContent></Card>:kind==="existing"?<Card><CardContent className="space-y-3 p-5">{[["هاكاثون المدن المستدامة 2026","فعالية ابتكارية","3 مخرجات"],["تطبيق التفكير التصميمي لتحسين الخدمة","منهجية ابتكار","2 نماذج أولية"],["مبادرة إدارة الطاقة","مبادرة مؤسسية","حل واحد"]].map(r=><div key={r[0]} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-semibold">{r[0]}</p><p className="text-xs text-muted">{r[1]} · {r[2]}</p></div><Button asChild size="sm"><Link href="/solutions/from-existing?select=1">اختيار وربط</Link></Button></div>)}</CardContent></Card>:<Card><CardContent className="flex flex-wrap gap-3 p-5"><Button><Download className="h-4 w-4"/>CSV</Button><Button variant="outline"><Download className="h-4 w-4"/>XLSX</Button><Button asChild variant="outline"><Link href="/solutions?print=1">عرض مهيأ للطباعة</Link></Button></CardContent></Card>}</div>;
}
