"use server";
import { revalidatePath } from "next/cache";
import type { RaciResponsibility, RequirementWorkflowState, WorkPriority } from "@prisma/client";
import { getAccessContext } from "@/server/authz";
import { addCollaborationEntry, configureOwnership, transitionRequirement } from "./service";
export interface GovernanceActionState{error?:string;success?:string}
const refresh=(path:string)=>{revalidatePath(path);revalidatePath("/my-tasks");revalidatePath("/reviews");revalidatePath("/dashboard");revalidatePath("/readiness-check");};
export async function transitionAction(_:GovernanceActionState,fd:FormData):Promise<GovernanceActionState>{try{const actor=await getAccessContext();if(!actor)return{error:"يلزم تسجيل الدخول"};await transitionRequirement(actor,{assignmentId:String(fd.get("assignmentId")),to:String(fd.get("to")) as RequirementWorkflowState,comment:String(fd.get("comment")||""),reason:String(fd.get("reason")||""),assigneeUserId:String(fd.get("assigneeUserId")||"")||undefined,dueDate:fd.get("dueDate")?new Date(String(fd.get("dueDate"))):null,priority:(fd.get("priority")||undefined) as WorkPriority|undefined});refresh(String(fd.get("path")));return{success:"تم تنفيذ الإجراء وتسجيله"};}catch(e){return{error:e instanceof Error&&e.message==="AMENDMENT_FIELDS_REQUIRED"?"سبب الإعادة والمسؤول والموعد والأولوية مطلوبة":"تعذر تنفيذ الانتقال"};}}
export async function ownershipAction(_:GovernanceActionState,fd:FormData):Promise<GovernanceActionState>{try{const actor=await getAccessContext();if(!actor)return{error:"يلزم تسجيل الدخول"};const raci=([["RESPONSIBLE","raciResponsible"],["ACCOUNTABLE","raciAccountable"],["CONSULTED","raciConsulted"],["INFORMED","raciInformed"]] as const).flatMap(([responsibility,key])=>{const userId=String(fd.get(key)||"");return userId?[{responsibility:responsibility as RaciResponsibility,userId}]:[]});await configureOwnership(actor,{assignmentId:String(fd.get("assignmentId")),ownerUserId:String(fd.get("ownerUserId")||"")||undefined,responsibleUserId:String(fd.get("responsibleUserId")||"")||undefined,dueDate:fd.get("dueDate")?new Date(String(fd.get("dueDate"))):null,priority:String(fd.get("priority")) as WorkPriority,nextAction:String(fd.get("nextAction")||""),raci});refresh(String(fd.get("path")));return{success:"تم تحديث الملكية وRACI"};}catch{return{error:"تعذر تحديث الإسناد"};}}
export async function commentAction(_:GovernanceActionState,fd:FormData):Promise<GovernanceActionState>{try{const actor=await getAccessContext();if(!actor)return{error:"يلزم تسجيل الدخول"};await addCollaborationEntry(actor,{assignmentId:String(fd.get("assignmentId")),body:String(fd.get("body")),type:String(fd.get("type")) as "COMMENT"|"REVIEW_NOTE"|"INFORMATION_REQUEST"|"ASSIGNMENT"|"DUE_DATE_CHANGE",dueDate:fd.get("dueDate")?new Date(String(fd.get("dueDate"))):null});refresh(String(fd.get("path")));return{success:"أضيفت الملاحظة"};}catch{return{error:"تعذر إضافة الملاحظة"};}}
