import type { Prisma, RaciResponsibility, RequirementTaskType, RequirementWorkflowState, WorkPriority } from "@prisma/client";
import type { AccessContext } from "@/server/access-context";
import { effectiveScopes } from "@/server/authorization";
import { prisma } from "@/server/db";
import { AUDIT, writeAudit } from "@/server/audit";

export const WORKFLOW_LABELS:Record<RequirementWorkflowState,string>={DRAFT:"مسودة",IN_PROGRESS:"قيد التنفيذ",SUBMITTED_FOR_REVIEW:"أرسل للمراجعة",UNDER_REVIEW:"قيد المراجعة",RETURNED_FOR_AMENDMENT:"أعيد للتعديل",RESUBMITTED:"أعيد إرساله",PENDING_APPROVAL:"بانتظار الاعتماد",APPROVED:"معتمد",COMPLETED:"مكتمل",BLOCKED:"متعثر"};
const transitions:Record<RequirementWorkflowState,RequirementWorkflowState[]>={DRAFT:["IN_PROGRESS"],IN_PROGRESS:["SUBMITTED_FOR_REVIEW","BLOCKED"],SUBMITTED_FOR_REVIEW:["UNDER_REVIEW","RETURNED_FOR_AMENDMENT"],UNDER_REVIEW:["RETURNED_FOR_AMENDMENT","PENDING_APPROVAL"],RETURNED_FOR_AMENDMENT:["RESUBMITTED"],RESUBMITTED:["UNDER_REVIEW","RETURNED_FOR_AMENDMENT","PENDING_APPROVAL"],PENDING_APPROVAL:["APPROVED","RETURNED_FOR_AMENDMENT"],APPROVED:["COMPLETED","RETURNED_FOR_AMENDMENT"],COMPLETED:[],BLOCKED:["IN_PROGRESS"]};
export const canTransition=(from:RequirementWorkflowState,to:RequirementWorkflowState)=>transitions[from].includes(to);
const isAdmin=(actor:AccessContext)=>effectiveScopes(actor).platform&&actor.permissions.has("compliance.configure");
const canReview=(actor:AccessContext)=>actor.permissions.has("evidence.approve")||isAdmin(actor);

async function assignmentInScope(actor:AccessContext,assignmentId:string){const scopes=effectiveScopes(actor);const row=await prisma.complianceRequirementAssignment.findFirst({where:{id:assignmentId,archivedAt:null,...(scopes.platform?{}:{OR:[...(scopes.departmentIds.length?[{departmentId:{in:scopes.departmentIds}}]:[]),...(scopes.organizationIds.length?[{department:{organizationId:{in:scopes.organizationIds}}}]:[]) ]})},include:{requirement:true,department:true}});if(!row)throw new Error("OUT_OF_SCOPE");return row;}
async function evidenceSnapshot(assignmentId:string){return prisma.evidenceLink.findMany({where:{entityType:"REQUIREMENT_ASSIGNMENT",entityId:assignmentId,evidence:{archivedAt:null}},select:{evidenceId:true,evidence:{select:{classification:true,version:true,reviewStatus:true,approvedAt:true}}}});}

export async function configureOwnership(actor:AccessContext,input:{assignmentId:string;ownerUserId?:string;responsibleUserId?:string;dueDate?:Date|null;priority:WorkPriority;nextAction?:string;raci:{responsibility:RaciResponsibility;userId?:string;departmentId?:string;organizationalRole?:string}[]}){
  const assignment=await assignmentInScope(actor,input.assignmentId);if(!isAdmin(actor)&&!actor.permissions.has("compliance.configure"))throw new Error("FORBIDDEN");
  const candidateIds=[input.ownerUserId,input.responsibleUserId,...input.raci.map(x=>x.userId)].filter(Boolean) as string[];if(candidateIds.length){const count=await prisma.user.count({where:{id:{in:candidateIds},status:"ACTIVE",registrationStatus:"APPROVED"}});if(count!==new Set(candidateIds).size)throw new Error("INVALID_USER");}
  await prisma.$transaction(async tx=>{await tx.complianceRequirementAssignment.update({where:{id:assignment.id},data:{ownerUserId:input.ownerUserId||null,responsibleUserId:input.responsibleUserId||null,dueDate:input.dueDate,priority:input.priority,nextAction:input.nextAction||null}});await tx.requirementRaciAssignment.deleteMany({where:{assignmentId:assignment.id}});if(input.raci.length)await tx.requirementRaciAssignment.createMany({data:input.raci.map(x=>({...x,assignmentId:assignment.id,assignedById:actor.userId,userId:x.userId||null,departmentId:x.departmentId||null,organizationalRole:x.organizationalRole||null}))});await writeAudit({actorUserId:actor.userId,action:AUDIT.REQUIREMENT_OWNERSHIP_ASSIGNED,entityType:"REQUIREMENT_ASSIGNMENT",entityId:assignment.id,departmentId:assignment.departmentId,summary:"تحديث الملكية ومصفوفة RACI",after:{ownerUserId:input.ownerUserId,responsibleUserId:input.responsibleUserId,dueDate:input.dueDate,priority:input.priority,raci:input.raci}},tx);});
}

function taskForState(state:RequirementWorkflowState):RequirementTaskType|null{return state==="SUBMITTED_FOR_REVIEW"||state==="UNDER_REVIEW"?"REVIEW":state==="PENDING_APPROVAL"?"APPROVE":state==="RETURNED_FOR_AMENDMENT"?"AMEND":null;}
export async function transitionRequirement(actor:AccessContext,input:{assignmentId:string;to:RequirementWorkflowState;comment?:string;reason?:string;assigneeUserId?:string;dueDate?:Date|null;priority?:WorkPriority}){
  const assignment=await assignmentInScope(actor,input.assignmentId);if(!canTransition(assignment.workflowState,input.to))throw new Error("INVALID_TRANSITION");if(["UNDER_REVIEW","RETURNED_FOR_AMENDMENT","PENDING_APPROVAL","APPROVED"].includes(input.to)&&!canReview(actor))throw new Error("FORBIDDEN");if(input.to==="RETURNED_FOR_AMENDMENT"&&(!input.reason?.trim()||!input.assigneeUserId||!input.dueDate||!input.priority))throw new Error("AMENDMENT_FIELDS_REQUIRED");
  const evidence=await evidenceSnapshot(assignment.id);const versioned=["SUBMITTED_FOR_REVIEW","RESUBMITTED","APPROVED"].includes(input.to);
  await prisma.$transaction(async tx=>{const version=versioned?await tx.requirementWorkspaceVersion.count({where:{assignmentId:assignment.id}})+1:null;if(version)await tx.requirementWorkspaceVersion.create({data:{assignmentId:assignment.id,version,workspaceData:assignment.workspaceData as Prisma.InputJsonValue,evidenceSnapshot:evidence as unknown as Prisma.InputJsonValue,workflowState:input.to,authorUserId:actor.userId,reviewComment:input.comment,approvalUserId:input.to==="APPROVED"?actor.userId:null,approvedAt:input.to==="APPROVED"?new Date():null}});await tx.complianceRequirementAssignment.update({where:{id:assignment.id},data:{workflowState:input.to,nextAction:input.to==="RETURNED_FOR_AMENDMENT"?"استكمال التعديلات وإعادة الإرسال":input.to==="PENDING_APPROVAL"?"قرار المعتمد":input.to==="APPROVED"?"استكمال الأدلة والجاهزية":null}});await tx.requirementWorkflowEvent.create({data:{assignmentId:assignment.id,actorUserId:actor.userId,previousState:assignment.workflowState,newState:input.to,comment:input.comment,reason:input.reason,assigneeUserId:input.assigneeUserId,dueDate:input.dueDate,priority:input.priority}});const taskType=taskForState(input.to);if(taskType&&input.assigneeUserId){await tx.requirementTask.create({data:{assignmentId:assignment.id,type:taskType,title:`${WORKFLOW_LABELS[input.to]} — ${assignment.requirement.titleAr}`,requestedById:actor.userId,assignedToUserId:input.assigneeUserId,dueDate:input.dueDate,priority:input.priority??assignment.priority,nextAction:input.to==="RETURNED_FOR_AMENDMENT"?"تعديل المتطلب وإعادة إرساله":"فتح المتطلب واتخاذ الإجراء"}});await tx.notification.create({data:{userId:input.assigneeUserId,title:`مهمة جديدة: ${WORKFLOW_LABELS[input.to]}`,message:input.reason||input.comment||assignment.requirement.titleAr,type:input.to==="RETURNED_FOR_AMENDMENT"?"WARNING":"INFO"}});}await tx.requirementTask.updateMany({where:{assignmentId:assignment.id,assignedToUserId:actor.userId,status:{in:["OPEN","IN_PROGRESS"]}},data:{status:"COMPLETED",completedAt:new Date()}});await writeAudit({actorUserId:actor.userId,action:AUDIT.REQUIREMENT_WORKFLOW_TRANSITION,entityType:"REQUIREMENT_ASSIGNMENT",entityId:assignment.id,departmentId:assignment.departmentId,summary:`${WORKFLOW_LABELS[assignment.workflowState]} ← ${WORKFLOW_LABELS[input.to]}`,before:{state:assignment.workflowState},after:{state:input.to,reason:input.reason,assigneeUserId:input.assigneeUserId}},tx);});
}

export async function addCollaborationEntry(actor:AccessContext,input:{assignmentId:string;body:string;type:"COMMENT"|"REVIEW_NOTE"|"INFORMATION_REQUEST"|"ASSIGNMENT"|"DUE_DATE_CHANGE";dueDate?:Date|null}){const assignment=await assignmentInScope(actor,input.assignmentId);if(!input.body.trim())throw new Error("VALIDATION");await prisma.$transaction(async tx=>{await tx.requirementCollaborationEntry.create({data:{...input,body:input.body.trim(),authorUserId:actor.userId}});await writeAudit({actorUserId:actor.userId,action:AUDIT.REQUIREMENT_COMMENT_ADDED,entityType:"REQUIREMENT_ASSIGNMENT",entityId:assignment.id,departmentId:assignment.departmentId,summary:"إضافة ملاحظة تعاون",metadata:{type:input.type}},tx);});}

export async function listMyTasks(actor:AccessContext){if(!actor.permissions.has("compliance.view"))throw new Error("FORBIDDEN");return prisma.requirementTask.findMany({where:{assignedToUserId:actor.userId,status:{in:["OPEN","IN_PROGRESS","WAITING"]}},orderBy:[{dueDate:"asc"},{createdAt:"desc"}],include:{sectionContribution:{select:{id:true,sectionKey:true}},assignment:{include:{requirement:true,department:true}}}});}
export async function listReviewQueue(actor:AccessContext){if(!canReview(actor))return[];const scopes=effectiveScopes(actor);return prisma.complianceRequirementAssignment.findMany({where:{archivedAt:null,workflowState:{in:["SUBMITTED_FOR_REVIEW","RESUBMITTED","UNDER_REVIEW","PENDING_APPROVAL"]},...(scopes.platform?{}:{departmentId:{in:scopes.departmentIds}})},include:{requirement:true,department:true,tasks:{where:{assignedToUserId:actor.userId,status:{in:["OPEN","IN_PROGRESS"]}}}},orderBy:{updatedAt:"asc"}});}
export async function getOperationalWorkCounts(actor:AccessContext){const now=new Date();const soon=new Date(now.getTime()+7*86400000);const openStatuses:("OPEN"|"IN_PROGRESS"|"WAITING")[]=["OPEN","IN_PROGRESS","WAITING"];const [mine,review,approve,returned,pendingEvidence,overdue,upcoming]=await Promise.all([prisma.requirementTask.count({where:{assignedToUserId:actor.userId,status:{in:openStatuses}}}),prisma.requirementTask.count({where:{assignedToUserId:actor.userId,type:"REVIEW",status:{in:["OPEN","IN_PROGRESS"]}}}),prisma.requirementTask.count({where:{assignedToUserId:actor.userId,type:"APPROVE",status:{in:["OPEN","IN_PROGRESS"]}}}),prisma.requirementTask.count({where:{assignedToUserId:actor.userId,type:"AMEND",status:{in:["OPEN","IN_PROGRESS"]}}}),prisma.evidence.count({where:{reviewStatus:"PENDING_APPROVAL",archivedAt:null}}),prisma.requirementTask.count({where:{assignedToUserId:actor.userId,status:{in:openStatuses},dueDate:{lt:now}}}),prisma.requirementTask.count({where:{assignedToUserId:actor.userId,status:{in:openStatuses},dueDate:{gte:now,lte:soon}}})]);return{mine,review,approve,returned,pendingEvidence,overdue,upcoming};}
