import {describe,expect,it} from "vitest";import fs from "node:fs";import path from "node:path";
import {cooperationActivationForPersona,PREVIEW_COOPERATION_ACTIVATION} from "../src/modules/dga/preview-cooperation-activation-fixture";import {getContributionDefinition} from "../src/modules/requirement-contributions/types";import {getWorkspaceConfig} from "../src/modules/dga/workspace-config";
const read=(file:string)=>fs.readFileSync(path.join(process.cwd(),file),"utf8");
describe("5.23.2 requirement 04 cooperation activation",()=>{
 it("reuses the 5.23.1 cooperation instead of creating another partner registry",()=>{const row=(PREVIEW_COOPERATION_ACTIVATION.cooperationActivations as any[])[0];expect(row.cooperationName).toBe("جامعة المجمعة");expect(row.agreementReference).toBe("COOP-2026-014");expect(read("src/modules/dga/components/requirement-route.tsx")).toContain('loadRequirementWorkspace(actor,"5-23-1-r3")');});
 it("tracks quarterly meetings deterministically",()=>{const row=(PREVIEW_COOPERATION_ACTIVATION.cooperationActivations as any[])[0];expect(row.meetings.map((m:any)=>m.quarter)).toEqual(["Q1","Q2","Q3","Q4"]);expect(row.meetings.filter((m:any)=>m.status==="مكتمل")).toHaveLength(2);expect(row.meetings.find((m:any)=>m.quarter==="Q3").minutesState).toBe("بانتظار المحضر");});
 it("maintains agreement-to-output traceability",()=>{const row=(PREVIEW_COOPERATION_ACTIVATION.cooperationActivations as any[])[0];expect(row.outputs[0].commitmentId).toBe("c1");expect(row.outputs[0].meetingId).toBe("q2");expect(row.commitments[0].outputId).toBe("o1");});
 it("supports tasks, corrections, reports and decisions",()=>{const row=(PREVIEW_COOPERATION_ACTIVATION.cooperationActivations as any[])[0];expect(row.tasks.length).toBeGreaterThan(0);expect(row.correctiveActions[0].source).toContain("Q3");expect(row.reports[0].approvalStatus).toBe("معتمد");expect(row.decisions[0].resultingCommitment).toBe("c2");});
 it("reuses contribution scopes and existing infrastructure",()=>{expect(getContributionDefinition("5-23-2-r4")?.sections).toContain("commitments");const service=read("src/modules/dga/workspace-service.ts");expect(service).toContain("syncCooperationActivationTasks");expect(service).toContain("cooperation-activation:${activationId}");expect(service).toContain("COOPERATION_ACTIVATION_MEETING_UPDATED");});
 it("keeps partner and viewer payloads scoped",()=>{const admin=(cooperationActivationForPersona("admin").cooperationActivations as any[])[0];const partner=(cooperationActivationForPersona("partner").cooperationActivations as any[])[0];const viewer=(cooperationActivationForPersona("viewer").cooperationActivations as any[])[0];expect(admin.tasks.length).toBe(2);expect(partner.tasks).toHaveLength(1);expect(partner.log).toHaveLength(0);expect(viewer.tasks).toHaveLength(0);expect(viewer.files).toHaveLength(0);expect(viewer.partnerEmail).toBe("");});
 it("separates operational details from official evidence",()=>{const config=getWorkspaceConfig("5-23-2-r4")!;expect(config.sections[0].key).toBe("cooperationActivations");expect(config.sections.slice(1).every(section=>section.contributionOnly)).toBe(true);expect(config.evidence[0].key).toBe("COOPERATION_ACTIVATION_DOCUMENTS");});
 it("provides a dedicated activation route and direct task link",()=>{expect(read("src/app/(app)/activities/requirements/[requirementId]/activations/[activationId]/page.tsx")).toContain("RequirementRoute");expect(read("src/app/(app)/my-tasks/page.tsx")).toContain("/activations/${cooperationActivation[1]}");});
});
