import {readFileSync} from "node:fs";import {describe,expect,it} from "vitest";
import {methodologyForPersona,PREVIEW_METHODOLOGY_WORKSPACE} from "../src/modules/dga/preview-methodology-fixture";import {getContributionDefinition} from "../src/modules/requirement-contributions/types";
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
describe("5.23.2 requirement 02 methodology workspace",()=>{
 it("demonstrates two connected cases and the official 2-session minimum",()=>{const cases=PREVIEW_METHODOLOGY_WORKSPACE.methodologyCases as Record<string,unknown>[];const sessions=cases.flatMap(item=>item.sessions as Record<string,unknown>[]);expect(cases).toHaveLength(2);expect(sessions.filter(item=>item.type==="عصف ذهني")).toHaveLength(2);expect((cases[0].prototypes as Record<string,unknown>[])[0].stages).toHaveLength(2);expect(cases[1].prototypes).toEqual([]);});
 it("preserves challenge to session to solution traceability",()=>{const first=(PREVIEW_METHODOLOGY_WORKSPACE.methodologyCases as Record<string,unknown>[])[0];const sessionIds=new Set((first.sessions as Record<string,unknown>[]).map(item=>item.id));for(const solution of first.solutions as Record<string,unknown>[])expect(sessionIds.has(solution.sessionId)).toBe(true);});
 it("removes private data before partner and viewer serialization",()=>{for(const role of ["partner","viewer"]){const first=(methodologyForPersona(role).methodologyCases as Record<string,unknown>[])[0];expect(first.participants).toEqual([]);expect(first.tasks).toEqual([]);expect(first.files).toEqual([]);}});
 it("reuses requirement contributions and RequirementTask",()=>{expect(getContributionDefinition("5-23-2-r2")?.sections).toContain("sessions");const service=read("src/modules/dga/workspace-service.ts");expect(service).toContain("syncMethodologyApplications");expect(service).toContain("methodologyApplicationId:record.id");expect(service).toContain("tx.requirementTask.upsert");});
 it("routes My Tasks to the exact methodology context",()=>{const page=read("src/app/(app)/my-tasks/page.tsx");expect(page).toContain("methodologyCaseId=${task.methodologyApplicationId}#methodology-task-context");});
 it("uses an additive non-destructive migration",()=>{const migration=read("prisma/migrations/20260819230000_methodology_application_cases/migration.sql");expect(migration).toContain('CREATE TABLE "methodology_applications"');expect(migration).toContain('ADD COLUMN "methodologyApplicationId"');expect(migration).not.toMatch(/DROP\s+(TABLE|COLUMN)/i);});
 it("exposes all requested progressive sections and closure guard",()=>{const component=read("src/modules/dga/components/methodology-workspace.tsx");for(const label of ["التحدي والمنهجية","الجلسات","المشاركون","المهام والتحضير","الحلول المقترحة","النماذج الأولية","المشاريع الناتجة","المؤشرات والأثر","الملفات والأدلة","السجل"])expect(component).toContain(label);expect(component).toContain("لا يمكن إغلاق الحالة");expect(component).toContain("brainstorming.length<2");});
});
