import {readFileSync} from "node:fs";import {describe,expect,it} from "vitest";
import {openInnovationForPersona,PREVIEW_OPEN_INNOVATION} from "../src/modules/dga/preview-open-innovation-fixture";import {getContributionDefinition} from "../src/modules/requirement-contributions/types";import {getWorkspaceConfig} from "../src/modules/dga/workspace-config";
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
describe("5.23.2 requirement 03 open innovation workspace",()=>{
 it("derives the representative event metrics from structured records",()=>{const event=(PREVIEW_OPEN_INNOVATION.openInnovationEvents as Record<string,any>[])[0];expect(event.participants).toHaveLength(84);expect(event.teams).toHaveLength(21);expect(event.challenges).toHaveLength(12);expect(event.solutions).toHaveLength(18);expect(event.prototypes).toHaveLength(6);expect(event.winners).toHaveLength(3);expect(event.projects).toHaveLength(2);});
 it("preserves challenge to team to solution to prototype to project lineage",()=>{const event=(PREVIEW_OPEN_INNOVATION.openInnovationEvents as Record<string,any>[])[0];const solution=event.solutions[0];expect(event.teams.find((row:any)=>row.id===solution.teamId)?.challengeId).toBe(solution.challengeId);expect(event.prototypes.find((row:any)=>row.id===solution.prototypeId)?.solutionId).toBe(solution.id);expect(event.projects.find((row:any)=>row.id===solution.projectId)?.solutionId).toBe(solution.id);});
 it("removes private participant and internal workflow data for limited personas",()=>{const partner=(openInnovationForPersona("partner").openInnovationEvents as Record<string,any>[])[0];const viewer=(openInnovationForPersona("viewer").openInnovationEvents as Record<string,any>[])[0];expect(partner.participants).toEqual([]);expect(partner.tasks).toEqual([]);expect(partner.log).toEqual([]);expect(viewer.participants).toEqual([]);expect(viewer.teams).toEqual([]);expect(viewer.judging).toEqual([]);expect(viewer.files).toEqual([]);});
 it("uses a structured event root and scoped contributor forms instead of the former flat giant form",()=>{const config=getWorkspaceConfig("5-23-2-r3")!;expect(config.sections[0].key).toBe("openInnovationEvents");expect(config.sections.slice(1).every(section=>section.contributionOnly)).toBe(true);expect(config.sections[0].fields.map(field=>field.key)).not.toContain("participantCount");expect(config.sections[0].fields.map(field=>field.key)).not.toContain("challenges");});
 it("reuses contributions, RequirementTask, evidence, and audit infrastructure",()=>{expect(getContributionDefinition("5-23-2-r3")?.sections).toContain("participants");const service=read("src/modules/dga/workspace-service.ts");expect(service).toContain("syncOpenInnovationTasks");expect(service).toContain("open-innovation:${eventId}");expect(service).toContain("OPEN_INNOVATION_EVENT_CREATED");expect(service).toContain("uploadRequirementEvidence");});
 it("deep-links event tasks and exposes the full event workspace",()=>{const tasks=read("src/app/(app)/my-tasks/page.tsx");expect(tasks).toContain("/activities/requirements/5-23-2-r3/events/${openInnovation[1]}");const component=read("src/modules/dga/components/open-innovation-workspace.tsx");for(const label of ["فعاليات الابتكار المفتوح","الجدول واللقاءات","التحديات","المشاركون والفرق","الحلول والمشاركات","التحكيم والفائزون","النماذج الأولية","المشاريع الناتجة","الأثر","الملفات والشهادات","الأدلة","المهام والتوكيلات","الإغلاق والسجل"])expect(component).toContain(label);});
 it("keeps operational closure separate from official evidence readiness",()=>{const component=read("src/modules/dga/components/open-innovation-workspace.tsx");expect(component).toContain("الإغلاق التشغيلي لا يعني اكتمال أو اعتماد أدلة DGA");expect(component).toContain("جاهزية أدلة المتطلب");expect(component).toContain("الملفات التشغيلية لا تصبح دليلًا رسميًا تلقائيًا");});
});
