import Link from "next/link";
import { Download } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getLiveReadiness } from "@/modules/dga/live-readiness";
import { getPlatformSummary } from "@/modules/reports/service";
import { can, getAccessContext, requirePermission } from "@/server/authz";
export const metadata={title:"التقارير"};
export default async function ReportsPage(){await requirePermission("compliance.view");const actor=(await getAccessContext())!;const [summary,readiness]=await Promise.all([getPlatformSummary(actor),getLiveReadiness(actor)]);const cards=[["تقرير الجاهزية العام",`${readiness.overall}% جاهزية تشغيلية`,"/compliance"],["تقرير الحلول",`${summary.solutions} حل ضمن النطاق`,"/solutions"],["تقرير قياس الأثر",`${readiness.units.find(x=>x.code==="5.24.2")?.total ?? 0} مؤشر مسجل`,"/impact"],["تقرير الأدلة الناقصة",`${readiness.missingEvidence} نقص يحتاج متابعة`,"/compliance"]];return <div className="flex flex-col gap-5 print:p-0"><PageHeader title="التقارير" description="تقارير تشغيلية حية ضمن نطاق صلاحيات المستخدم، مناسبة للعرض والطباعة." action={can(actor,"compliance.export")?<Button asChild variant="outline"><Link href="/reports/export/readiness"><Download className="h-4 w-4"/>تصدير CSV</Link></Button>:undefined}/><div className="grid gap-4 md:grid-cols-2">{cards.map(([title,detail,href])=><Link key={title} href={href}><Card className="h-full hover:border-primary/40"><CardContent className="p-5"><h2 className="font-bold">{title}</h2><p className="mt-2 text-sm text-muted">{detail}</p></CardContent></Card></Link>)}</div><Card><CardContent className="p-5"><h2 className="font-bold">ملخص الوحدات الخمس</h2><table className="mt-3 w-full text-xs"><tbody>{readiness.units.map(unit=><tr key={unit.code} className="border-b"><td className="py-2">{unit.code}</td><td>{unit.name}</td><td>{unit.readiness}%</td><td>{unit.missingEvidence} أدلة ناقصة</td></tr>)}</tbody></table></CardContent></Card><p className="text-xs text-muted">هذه التقارير تشغيلية داخلية ولا تمثل اعتماداً رسمياً من الهيئة. يمكن طباعة الصفحة من المتصفح.</p></div>}
