"use client";
import { useFormState } from "react-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { commentAction,ownershipAction,transitionAction,type GovernanceActionState } from "../actions";
export type GovernanceView={assignmentId:string;workflowState:string;priority:string;ownerUserId:string|null;responsibleUserId:string|null;dueDate:string|null;nextAction:string|null;raci:{responsibility:string;userId:string|null;departmentId:string|null;organizationalRole:string|null}[];events:{id:string;previousState:string;newState:string;comment:string|null;reason:string|null;actor:string;createdAt:string}[];versions:{id:string;version:number;workflowState:string;author:string;createdAt:string;reviewComment:string|null}[];comments:{id:string;type:string;body:string;author:string;createdAt:string}[];tasks:{id:string;type:string;title:string;status:string;priority:string;assignedTo:string;dueDate:string|null;nextAction:string|null}[];auditEntries:{id:string;action:string;actor:string;summary:string|null;createdAt:string}[];canViewAudit:boolean;users:{id:string;name:string;email:string}[];canConfigure:boolean;canReview:boolean};
const labels:Record<string,string>={DRAFT:"مسودة",IN_PROGRESS:"قيد التنفيذ",SUBMITTED_FOR_REVIEW:"أرسل للمراجعة",UNDER_REVIEW:"قيد المراجعة",RETURNED_FOR_AMENDMENT:"أعيد للتعديل",RESUBMITTED:"أعيد إرساله",PENDING_APPROVAL:"بانتظار الاعتماد",APPROVED:"معتمد",COMPLETED:"مكتمل",BLOCKED:"متعثر"};
const collabLabels:Record<string,string>={COMMENT:"تعليق",REVIEW_NOTE:"ملاحظة مراجعة",INFORMATION_REQUEST:"طلب معلومات",ASSIGNMENT:"تكليف",DUE_DATE_CHANGE:"تغيير موعد"};
const taskTypeLabels:Record<string,string>={PREPARE:"إعداد",REVIEW:"مراجعة",APPROVE:"اعتماد",AMEND:"تعديل",RESPOND:"رد",FOLLOW_UP:"متابعة"};
const taskStatusLabels:Record<string,string>={OPEN:"مفتوحة",IN_PROGRESS:"قيد التنفيذ",WAITING:"بانتظار رد",COMPLETED:"مكتملة",CANCELLED:"ملغاة"};
const priorityLabels:Record<string,string>={LOW:"منخفضة",MEDIUM:"متوسطة",HIGH:"عالية",URGENT:"عاجلة"};
const auditLabels:Record<string,string>={COMPLIANCE_ASSIGNMENT_UPDATED:"تحديث بيانات المتطلب",SECTION_CONTRIBUTION_ASSIGNED:"إسناد مساهمة",SECTION_CONTRIBUTION_OPENED:"فتح دعوة مساهمة",SECTION_CONTRIBUTION_SUBMITTED:"تسليم مساهمة",SECTION_CONTRIBUTION_RETURNED:"إعادة مساهمة للتعديل",SECTION_CONTRIBUTION_ACCEPTED:"قبول مساهمة",COOPERATION_RECORD_CREATED:"إنشاء سجل تعاون",COOPERATION_RECORD_UPDATED:"تحديث سجل تعاون",COOPERATION_CONTACT_ADDED:"إضافة جهة اتصال",COOPERATION_CONTACT_UPDATED:"تحديث جهة اتصال",COOPERATION_PRIMARY_CONTACT_CHANGED:"تغيير جهة الاتصال الرئيسية",COOPERATION_CONTACT_ARCHIVED:"أرشفة جهة اتصال",COOPERATION_AGREEMENT_LINKED:"ربط اتفاقية بسجل التعاون",COMMITTEE_CREATED:"تشكيل وحدة/لجنة",COMMITTEE_UPDATED:"تحديث بيانات وحدة/لجنة",COMMITTEE_DECISION_RECORDED:"توثيق قرار التشكيل",COMMITTEE_MEMBER_ADDED:"إضافة عضو",COMMITTEE_MEMBER_UPDATED:"تحديث بيانات عضو",COMMITTEE_MEMBER_ROLE_UPDATED:"تغيير دور عضو",COMMITTEE_MEMBER_REMOVED:"إنهاء/أرشفة عضوية عضو",COMMITTEE_TASK_ASSIGNED:"إسناد مهمة",COMMITTEE_TASK_COMPLETED:"إكمال مهمة"};
const actions:Record<string,[string,string,boolean?][]>= {DRAFT:[["IN_PROGRESS","بدء التنفيذ"]],IN_PROGRESS:[["SUBMITTED_FOR_REVIEW","إرسال للمراجعة"],["BLOCKED","تحديد كمتعثر"]],SUBMITTED_FOR_REVIEW:[["UNDER_REVIEW","بدء المراجعة",true],["RETURNED_FOR_AMENDMENT","إعادة للتعديل",true]],UNDER_REVIEW:[["RETURNED_FOR_AMENDMENT","إعادة للتعديل",true],["PENDING_APPROVAL","إرسال للاعتماد",true]],RETURNED_FOR_AMENDMENT:[["RESUBMITTED","إعادة الإرسال"]],RESUBMITTED:[["UNDER_REVIEW","بدء المراجعة",true],["PENDING_APPROVAL","إرسال للاعتماد",true]],PENDING_APPROVAL:[["APPROVED","اعتماد",true],["RETURNED_FOR_AMENDMENT","إعادة مع ملاحظات",true]],APPROVED:[["COMPLETED","إكمال المتطلب",true]],BLOCKED:[["IN_PROGRESS","استئناف التنفيذ"]],COMPLETED:[]};
const control="h-10 w-full rounded-lg border bg-transparent px-3 text-xs";
export function GovernancePanel({data,path,canEdit,preview=false}:{data:GovernanceView;path:string;canEdit:boolean;preview?:boolean}){
 const [ts,transition]=useFormState(transitionAction,{} as GovernanceActionState);const [os,ownership]=useFormState(ownershipAction,{} as GovernanceActionState);const [cs,comment]=useFormState(commentAction,{} as GovernanceActionState);const userName=(id:string|null)=>data.users.find(x=>x.id===id)?.name??"غير مسند";
 return <div className="space-y-5">
  <Card><CardHeader><CardTitle className="flex justify-between">الملكية وسير العمل <Badge variant="primary">{labels[data.workflowState]}</Badge></CardTitle></CardHeader><CardContent className="grid gap-3 text-xs md:grid-cols-3"><p><b>مالك المتطلب:</b> {userName(data.ownerUserId)}</p><p><b>مسؤول التنفيذ:</b> {userName(data.responsibleUserId)}</p><p><b>الموعد:</b> {data.dueDate?new Date(data.dueDate).toLocaleDateString("ar-SA"):"غير محدد"}</p><p><b>الأولوية:</b> {priorityLabels[data.priority]??data.priority}</p><p className="md:col-span-2"><b>الإجراء التالي:</b> {data.nextAction??"—"}</p></CardContent></Card>
  <Card><CardHeader><CardTitle>مصفوفة RACI</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{[["RESPONSIBLE","المسؤول عن التنفيذ"],["ACCOUNTABLE","المسؤول النهائي"],["CONSULTED","الجهات المستشارة"],["INFORMED","الجهات المطلوب إشعارها"]].map(([key,label])=><div key={key} className="rounded-lg border p-3"><p className="text-xs font-semibold">{label}</p><p className="mt-1 text-sm">{data.raci.filter(x=>x.responsibility===key).map(x=>userName(x.userId)).join("، ")||"غير مسند"}</p></div>)}</CardContent></Card>
  {data.canConfigure&&!preview&&<Card><CardHeader><CardTitle>تحديث الإسناد وRACI</CardTitle></CardHeader><CardContent><form action={ownership} className="grid gap-3 md:grid-cols-2"><Hidden data={data} path={path}/><UserSelect name="ownerUserId" label="مالك المتطلب" value={data.ownerUserId} users={data.users}/><UserSelect name="responsibleUserId" label="مسؤول التنفيذ" value={data.responsibleUserId} users={data.users}/><label className="text-xs">الموعد<input className={control} name="dueDate" type="date" defaultValue={data.dueDate?.slice(0,10)}/></label><label className="text-xs">الأولوية<select className={control} name="priority" defaultValue={data.priority}>{["LOW","MEDIUM","HIGH","URGENT"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs md:col-span-2">الإجراء التالي<input className={control} name="nextAction" defaultValue={data.nextAction??""}/></label>{[["raciResponsible","RESPONSIBLE","R — مسؤول"],["raciAccountable","ACCOUNTABLE","A — مسؤول نهائي"],["raciConsulted","CONSULTED","C — مستشار"],["raciInformed","INFORMED","I — يتم إشعاره"]].map(([field,key,label])=><UserSelect key={key} name={field} label={label} value={data.raci.find(x=>x.responsibility===key)?.userId??null} users={data.users}/>)}<Button className="md:col-span-2">حفظ الإسناد</Button></form><Message state={os}/></CardContent></Card>}
  {(canEdit||data.canReview)&&!preview&&<Card><CardHeader><CardTitle>الإجراء التالي</CardTitle></CardHeader><CardContent className="space-y-3">{(actions[data.workflowState]??[]).filter(x=>!x[2]||data.canReview).map(([to,label])=><form action={transition} key={to} className="grid gap-2 rounded-lg border p-3 md:grid-cols-4"><Hidden data={data} path={path}/><input type="hidden" name="to" value={to}/><textarea name={to==="RETURNED_FOR_AMENDMENT"?"reason":"comment"} required={to==="RETURNED_FOR_AMENDMENT"} placeholder={to==="RETURNED_FOR_AMENDMENT"?"سبب الإعادة والملاحظات":"تعليق الإجراء"} className="rounded-lg border bg-transparent p-2 text-xs md:col-span-2"/><select name="assigneeUserId" className={control} required={to==="RETURNED_FOR_AMENDMENT"}><option value="">المسؤول التالي</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><div className="flex gap-2"><input name="dueDate" type="date" className={control}/><select name="priority" className={control} defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></div><Button variant={to==="RETURNED_FOR_AMENDMENT"?"outline":"default"}>{label}</Button></form>)}<Message state={ts}/></CardContent></Card>}
  {!preview&&<Card><CardHeader><CardTitle>التعاون والنشاط</CardTitle></CardHeader><CardContent><form action={comment} className="flex flex-wrap gap-2"><Hidden data={data} path={path}/><select name="type" className={control+" max-w-44"}><option value="COMMENT">تعليق</option><option value="REVIEW_NOTE">ملاحظة مراجعة</option><option value="INFORMATION_REQUEST">طلب معلومات</option><option value="ASSIGNMENT">تكليف</option><option value="DUE_DATE_CHANGE">تغيير موعد</option></select><input required name="body" placeholder="اكتب الملاحظة أو الطلب" className="h-10 min-w-64 flex-1 rounded-lg border bg-transparent px-3 text-xs"/><Button>إضافة</Button></form><Message state={cs}/><div className="mt-3 divide-y">{data.comments.map(x=><div key={x.id} className="py-2 text-xs"><Badge variant={x.type==="COMMENT"?"neutral":"primary"} className="ml-2">{collabLabels[x.type]??x.type}</Badge><b>{x.author}</b> · {new Date(x.createdAt).toLocaleString("ar-SA")}<p className="mt-1">{x.body}</p></div>)}{data.events.map(x=><div key={x.id} className="py-2 text-xs"><b>{x.actor}</b>: {labels[x.previousState]} ← {labels[x.newState]}<p className="text-muted">{x.reason||x.comment} · {new Date(x.createdAt).toLocaleString("ar-SA")}</p></div>)}</div></CardContent></Card>}
  <Card><CardHeader><CardTitle className="flex items-center justify-between">مهام المتطلب<a href="/my-tasks" className="text-xs font-normal text-primary">عرض في مهامي</a></CardTitle></CardHeader><CardContent>{data.tasks.length?<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead><tr className="border-b text-muted">{["المهمة","المسؤول","الأولوية","الموعد","الحالة","الإجراء التالي"].map(h=><th key={h} className="p-2 text-start">{h}</th>)}</tr></thead><tbody>{data.tasks.map(t=><tr key={t.id} className="border-b"><td className="p-2"><Badge variant="primary">{taskTypeLabels[t.type]??t.type}</Badge><p className="mt-1 font-semibold">{t.title}</p></td><td className="p-2">{t.assignedTo}</td><td className="p-2">{priorityLabels[t.priority]??t.priority}</td><td className="p-2">{t.dueDate?new Date(t.dueDate).toLocaleDateString("ar-SA"):"—"}</td><td className="p-2">{taskStatusLabels[t.status]??t.status}</td><td className="p-2">{t.nextAction??"—"}</td></tr>)}</tbody></table></div>:<p className="text-xs text-muted">لا توجد مهام مرتبطة بهذا المتطلب حاليًا.</p>}</CardContent></Card>
  <Card><CardHeader><CardTitle>سجل الإصدارات</CardTitle></CardHeader><CardContent>{data.versions.map(x=><div key={x.id} className="mb-2 flex justify-between rounded-lg border p-3 text-xs"><span><b>الإصدار {x.version}</b> · {labels[x.workflowState]}</span><span>{x.author} · {new Date(x.createdAt).toLocaleString("ar-SA")}</span></div>)}{!data.versions.length&&<p className="text-xs text-muted">يُحفظ إصدار عند الإرسال وإعادة الإرسال والاعتماد.</p>}</CardContent></Card>
  {data.canViewAudit&&<Card><CardHeader><CardTitle>سجل التدقيق</CardTitle></CardHeader><CardContent>{data.auditEntries.length?<div className="divide-y">{data.auditEntries.map(x=><div key={x.id} className="py-2 text-xs"><Badge variant="neutral" className="ml-2">{auditLabels[x.action]??"حدث تشغيلي"}</Badge><b>{x.actor}</b> · {new Date(x.createdAt).toLocaleString("ar-SA")}{x.summary&&<p className="mt-1 text-muted">{x.summary}</p>}</div>)}</div>:<p className="text-xs text-muted">لا توجد أحداث مسجَّلة لهذا المتطلب بعد.</p>}</CardContent></Card>}
 </div>;
}
function Hidden({data,path}:{data:GovernanceView;path:string}){return <><input type="hidden" name="assignmentId" value={data.assignmentId}/><input type="hidden" name="path" value={path}/></>}
function UserSelect({name,label,value,users}:{name:string;label:string;value:string|null;users:GovernanceView["users"]}){return <label className="text-xs">{label}<select name={name} className={control} defaultValue={value??""}><option value="">غير مسند</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}
function Message({state}:{state:GovernanceActionState}){return state.error||state.success?<p className="mt-2 text-xs">{state.error||state.success}</p>:null}
