ALTER TYPE "EvidenceReviewStatus" ADD VALUE IF NOT EXISTS 'NEEDS_AMENDMENT';
ALTER TYPE "EvidenceReviewStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "EvidenceReviewStatus" ADD VALUE IF NOT EXISTS 'NEEDS_UPDATE';
CREATE TYPE "RequirementWorkflowState" AS ENUM ('DRAFT','IN_PROGRESS','SUBMITTED_FOR_REVIEW','UNDER_REVIEW','RETURNED_FOR_AMENDMENT','RESUBMITTED','PENDING_APPROVAL','APPROVED','COMPLETED','BLOCKED');
CREATE TYPE "RaciResponsibility" AS ENUM ('RESPONSIBLE','ACCOUNTABLE','CONSULTED','INFORMED');
CREATE TYPE "RequirementTaskType" AS ENUM ('PREPARE','REVIEW','APPROVE','AMEND','RESPOND','FOLLOW_UP');
CREATE TYPE "RequirementTaskStatus" AS ENUM ('OPEN','IN_PROGRESS','WAITING','COMPLETED','CANCELLED');
CREATE TYPE "WorkPriority" AS ENUM ('LOW','MEDIUM','HIGH','URGENT');
CREATE TYPE "CollaborationEntryType" AS ENUM ('COMMENT','REVIEW_NOTE','INFORMATION_REQUEST','ASSIGNMENT','DUE_DATE_CHANGE');
ALTER TABLE "compliance_requirement_assignments" ADD COLUMN "ownerUserId" TEXT, ADD COLUMN "workflowState" "RequirementWorkflowState" NOT NULL DEFAULT 'DRAFT', ADD COLUMN "priority" "WorkPriority" NOT NULL DEFAULT 'MEDIUM', ADD COLUMN "nextAction" TEXT;
ALTER TABLE "evidence" ADD COLUMN "ownerUserId" TEXT, ADD COLUMN "validUntil" TIMESTAMP(3);
CREATE TABLE "requirement_raci_assignments" ("id" TEXT PRIMARY KEY,"assignmentId" TEXT NOT NULL,"responsibility" "RaciResponsibility" NOT NULL,"userId" TEXT,"departmentId" TEXT,"organizationalRole" TEXT,"assignedById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "requirement_tasks" ("id" TEXT PRIMARY KEY,"assignmentId" TEXT NOT NULL,"type" "RequirementTaskType" NOT NULL,"title" TEXT NOT NULL,"status" "RequirementTaskStatus" NOT NULL DEFAULT 'OPEN',"priority" "WorkPriority" NOT NULL DEFAULT 'MEDIUM',"requestedById" TEXT NOT NULL,"assignedToUserId" TEXT,"assignedDepartmentId" TEXT,"dueDate" TIMESTAMP(3),"nextAction" TEXT,"completedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "requirement_workflow_events" ("id" TEXT PRIMARY KEY,"assignmentId" TEXT NOT NULL,"actorUserId" TEXT NOT NULL,"previousState" "RequirementWorkflowState" NOT NULL,"newState" "RequirementWorkflowState" NOT NULL,"comment" TEXT,"reason" TEXT,"assigneeUserId" TEXT,"dueDate" TIMESTAMP(3),"priority" "WorkPriority","createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "requirement_workspace_versions" ("id" TEXT PRIMARY KEY,"assignmentId" TEXT NOT NULL,"version" INTEGER NOT NULL,"workspaceData" JSONB NOT NULL,"evidenceSnapshot" JSONB NOT NULL,"workflowState" "RequirementWorkflowState" NOT NULL,"authorUserId" TEXT NOT NULL,"reviewComment" TEXT,"approvalUserId" TEXT,"approvedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "requirement_collaboration_entries" ("id" TEXT PRIMARY KEY,"assignmentId" TEXT NOT NULL,"type" "CollaborationEntryType" NOT NULL DEFAULT 'COMMENT',"authorUserId" TEXT NOT NULL,"body" TEXT NOT NULL,"mentionedUserIds" TEXT[] DEFAULT ARRAY[]::TEXT[],"dueDate" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "requirement_raci_assignments" ADD CONSTRAINT "requirement_raci_assignments_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "compliance_requirement_assignments"("id") ON DELETE CASCADE;
ALTER TABLE "requirement_tasks" ADD CONSTRAINT "requirement_tasks_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "compliance_requirement_assignments"("id") ON DELETE CASCADE;
ALTER TABLE "requirement_workflow_events" ADD CONSTRAINT "requirement_workflow_events_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "compliance_requirement_assignments"("id") ON DELETE CASCADE;
ALTER TABLE "requirement_workspace_versions" ADD CONSTRAINT "requirement_workspace_versions_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "compliance_requirement_assignments"("id") ON DELETE CASCADE;
ALTER TABLE "requirement_collaboration_entries" ADD CONSTRAINT "requirement_collaboration_entries_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "compliance_requirement_assignments"("id") ON DELETE CASCADE;
CREATE INDEX "requirement_raci_assignments_assignmentId_responsibility_idx" ON "requirement_raci_assignments"("assignmentId","responsibility");
CREATE INDEX "requirement_raci_assignments_userId_idx" ON "requirement_raci_assignments"("userId");
CREATE INDEX "requirement_tasks_assignedToUserId_status_dueDate_idx" ON "requirement_tasks"("assignedToUserId","status","dueDate");
CREATE INDEX "requirement_tasks_assignmentId_idx" ON "requirement_tasks"("assignmentId");
CREATE INDEX "requirement_workflow_events_assignmentId_createdAt_idx" ON "requirement_workflow_events"("assignmentId","createdAt");
CREATE UNIQUE INDEX "requirement_workspace_versions_assignmentId_version_key" ON "requirement_workspace_versions"("assignmentId","version");
CREATE INDEX "requirement_collaboration_entries_assignmentId_createdAt_idx" ON "requirement_collaboration_entries"("assignmentId","createdAt");
