"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { WorkspaceData } from "../workspace-status";

type Row = Record<string, unknown>;
type Activity = Row & { id: string; name: string; type: string; status: string; tasks?: Row[]; milestones?: Row[]; team?: Row[]; meetings?: Row[]; participants?: Row[]; files?: Row[]; deliverables?: Row[]; outputs?: Row[]; log?: Row[] };
const tabs = ["نظرة عامة","الخطة والجدول الزمني","الفريق والمسؤوليات","المهام","اللقاءات والاجتماعات","المشاركون / المستفيدون","الملفات والتصاميم","المخرجات","الأدلة والإغلاق","سجل النشاط"] as const;
const activityTypes=["هاكاثون","ورشة عمل","معسكر","لقاء","جلسة ابتكارية","مسابقة","فعالية توعوية","برنامج","نشاط آخر"];
const statusLabels:Record<string,string>={PLANNED:"قادمة",ONGOING:"قيد التنفيذ",COMPLETED:"مكتملة",DELAYED:"متأخرة",CANCELLED:"ملغاة"};
const taskLabels:Record<string,string>={NOT_STARTED:"لم تبدأ",IN_PROGRESS:"قيد التنفيذ",WAITING:"بانتظار طرف آخر",REVIEW:"بانتظار مراجعة",COMPLETED:"مكتملة",OVERDUE:"متأخرة",CANCELLED:"ملغاة"};
const newId=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const arr=(value:unknown)=>Array.isArray(value)?value as Row[]:[];
const EditContext=createContext(true);

function Text({label,value,onChange,area=false,type="text",disabled=false}:{label:string;value:unknown;onChange:(value:string)=>void;area?:boolean;type?:string;disabled?:boolean}){const editable=useContext(EditContext);const locked=disabled||!editable;return <label className="text-xs font-semibold">{label}{area?<textarea disabled={locked} value={String(value??"")} onChange={event=>onChange(event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border bg-transparent p-3 disabled:cursor-not-allowed disabled:opacity-70"/>:<input disabled={locked} type={type} value={String(value??"")} onChange={event=>onChange(event.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-transparent px-3 disabled:cursor-not-allowed disabled:opacity-70"/>}</label>}
function Select({label,value,values,onChange,disabled=false}:{label:string;value:unknown;values:string[];onChange:(value:string)=>void;disabled?:boolean}){const editable=useContext(EditContext);return <label className="text-xs font-semibold">{label}<select disabled={disabled||!editable} value={String(value??"")} onChange={event=>onChange(event.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-transparent px-3 disabled:cursor-not-allowed disabled:opacity-70"><option value="">اختر</option>{values.map(item=><option key={item} value={item}>{taskLabels[item]??item}</option>)}</select></label>}

export function AnnualPlanWorkspace({data,canEdit,onChange,personaKey="",users=[]}:{data:WorkspaceData;canEdit:boolean;onChange:(data:WorkspaceData)=>void;personaKey?:string;users?:{id:string;name:string;email:string}[]}){
  const plan=(data.annualPlan as Row)??{year:"2026",name:"الخطة السنوية للابتكار — 2026",owner:"إدارة الابتكار المؤسسي",status:"قيد التنفيذ"};
  const activities=useMemo(()=>(Array.isArray(data.activities)?data.activities:[]) as Activity[],[data.activities]);
  const [selected,setSelected]=useState(0);const [tab,setTab]=useState<(typeof tabs)[number]>(tabs[0]);const [notice,setNotice]=useState("");const [statusFilter,setStatusFilter]=useState("");const [typeFilter,setTypeFilter]=useState("");const [ownerFilter,setOwnerFilter]=useState("");
  useEffect(()=>{const activityId=new URLSearchParams(window.location.search).get("activityId");if(!activityId)return;const index=activities.findIndex(item=>item.activityId===activityId||item.id===activityId);if(index>=0){setSelected(index);setTab("المهام");}},[activities]);
  const activity=activities[selected];
  const allTasks=activities.flatMap(item=>arr(item.tasks));const completed=activities.filter(item=>item.status==="COMPLETED").length;const ongoing=activities.filter(item=>item.status==="ONGOING").length;const upcoming=activities.filter(item=>item.status==="PLANNED").length;const overdueTasks=allTasks.filter(task=>task.status==="OVERDUE").length;const missingEvidence=activities.filter(item=>!arr(item.files).some(file=>file.markedAsEvidence==="نعم")).length;
  const progress=activities.length?Math.round(activities.reduce((sum,item)=>sum+Number(item.progress||0),0)/activities.length):0;
  const availableTabs=personaKey==="viewer"?tabs.filter(item=>!["المشاركون / المستفيدون","الملفات والتصاميم","سجل النشاط"].includes(item)):personaKey==="partner"?tabs.filter(item=>!["المشاركون / المستفيدون","سجل النشاط"].includes(item)):tabs;
  const filteredActivities=activities.map((item,index)=>({item,index})).filter(({item})=>(!statusFilter||item.status===statusFilter)&&(!typeFilter||item.type===typeFilter)&&(!ownerFilter||String(item.manager||"")===ownerFilter));
  const updatePlan=(key:string,value:string)=>onChange({...data,annualPlan:{...plan,[key]:value}});
  const updateActivity=(key:string,value:unknown)=>onChange({...data,activities:activities.map((item,index)=>index===selected?{...item,[key]:value}:item)});
  const addActivity=()=>{const next:Activity={id:newId("activity"),name:"نشاط جديد",type:"ورشة عمل",status:"PLANNED",progress:0,year:String(plan.year||"2026"),tasks:[],milestones:[],team:[],meetings:[],participants:[],files:[],deliverables:[],outputs:[],log:[{date:new Date().toISOString(),action:"إنشاء مسودة النشاط"}]};onChange({...data,activities:[...activities,next]});setSelected(activities.length);setTab("نظرة عامة");setNotice("أضيف نشاط جديد إلى الخطة. أكمل معلوماته ثم احفظ التحديث.");};
  const addRecord=(key:string,row:Row)=>updateActivity(key,[...arr(activity?.[key]),row]);
  const updateRecord=(key:string,index:number,patch:Row)=>updateActivity(key,arr(activity?.[key]).map((row,rowIndex)=>rowIndex===index?{...row,...patch}:row));
  const closeActivity=()=>{if(!activity)return;const gaps=[arr(activity.tasks).some(row=>!["COMPLETED","CANCELLED"].includes(String(row.status))),!arr(activity.outputs).length,!arr(activity.files).some(row=>row.markedAsEvidence==="نعم")];if(gaps.some(Boolean)){setNotice("لا يمكن إغلاق النشاط: توجد مهام مفتوحة أو مخرجات/أدلة ناقصة.");return;}onChange({...data,activities:activities.map((item,index)=>index===selected?{...item,status:"COMPLETED",progress:100}:item)});setNotice("اكتملت قائمة الإغلاق داخل المنصة. لا يمثل ذلك اعتمادًا رسميًا من هيئة الحكومة الرقمية.");};
  const selectedMetrics=useMemo(()=>{if(!activity)return{done:0,total:0,overdue:0};const tasks=arr(activity.tasks);return{done:tasks.filter(row=>row.status==="COMPLETED").length,total:tasks.length,overdue:tasks.filter(row=>row.status==="OVERDUE").length};},[activity]);

  return <EditContext.Provider value={canEdit}><div className="space-y-5"><style>{`#workspace-data > div:first-child > div:first-child { display: none; }`}</style>
    <Card className="border-primary/20"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>{String(plan.name||"الخطة السنوية للابتكار")}</CardTitle><p className="mt-1 text-xs text-muted">سياق تشغيلي موحد لتخطيط الأنشطة وتنفيذها وتوثيقها وإغلاقها.</p></div>{canEdit?<Button size="sm" onClick={addActivity}><Plus className="h-4 w-4"/>إضافة نشاط / فعالية</Button>:null}</div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Text label="السنة" value={plan.year} onChange={value=>updatePlan("year",value)}/><Text label="مالك الخطة" value={plan.owner} onChange={value=>updatePlan("owner",value)}/><Text label="حالة الخطة" value={plan.status} onChange={value=>updatePlan("status",value)}/><div className="rounded-xl bg-primary-50 p-3 text-center"><p className="text-xs text-muted">الإنجاز التشغيلي</p><b className="text-2xl text-primary">{progress}%</b></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-center text-xs md:grid-cols-7">{[["الأنشطة",activities.length],["مكتملة",completed],["قيد التنفيذ",ongoing],["قادمة",upcoming],["متأخرة",activities.filter(item=>item.status==="DELAYED").length],["أدلة ناقصة",missingEvidence],["مهام متأخرة",overdueTasks]].map(([label,value])=><div key={String(label)} className="rounded-lg border p-2"><b>{value}</b><p className="text-muted">{label}</p></div>)}</div></CardContent></Card>
    <div className="grid gap-2 rounded-xl border p-3 sm:grid-cols-3"><select aria-label="تصفية حسب الحالة" value={statusFilter} onChange={event=>setStatusFilter(event.target.value)} className="h-10 rounded-lg border bg-transparent px-3 text-xs"><option value="">كل الحالات</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="تصفية حسب النوع" value={typeFilter} onChange={event=>setTypeFilter(event.target.value)} className="h-10 rounded-lg border bg-transparent px-3 text-xs"><option value="">كل الأنواع</option>{[...new Set(activities.map(item=>item.type))].map(value=><option key={value}>{value}</option>)}</select><select aria-label="تصفية حسب المسؤول" value={ownerFilter} onChange={event=>setOwnerFilter(event.target.value)} className="h-10 rounded-lg border bg-transparent px-3 text-xs"><option value="">كل المسؤولين</option>{[...new Set(activities.map(item=>String(item.manager||"")).filter(Boolean))].map(value=><option key={value}>{value}</option>)}</select></div>
    <div className="grid gap-3 lg:grid-cols-2">{filteredActivities.map(({item,index})=>{const tasks=arr(item.tasks);const next=arr(item.milestones).find(row=>row.status!=="مكتملة");return <button key={item.id} type="button" onClick={()=>{setSelected(index);setTab("نظرة عامة");}} className={`rounded-xl border p-4 text-start ${selected===index?"border-primary bg-primary-50/40":""}`}><div className="flex justify-between"><div><p className="font-bold">{item.name}</p><p className="text-xs text-muted">{item.type} · {String(item.manager||"مدير غير محدد")}</p></div><Badge variant={item.status==="COMPLETED"?"success":item.status==="DELAYED"?"danger":"warning"}>{statusLabels[item.status]??item.status}</Badge></div><Progress className="mt-3" value={Number(item.progress||0)}/><div className="mt-3 grid grid-cols-2 gap-1 text-xs"><p><b>الفترة:</b> {String(item.startDate||"—")} — {String(item.endDate||"—")}</p><p><b>المحطة التالية:</b> {String(next?.title||"—")}</p><p><b>مهام متأخرة:</b> {tasks.filter(row=>row.status==="OVERDUE").length}</p><p><b>الدليل:</b> {arr(item.files).some(row=>row.markedAsEvidence==="نعم")?"مرتبط":"ناقص"}</p></div></button>})}{!filteredActivities.length?<p className="col-span-full p-8 text-center text-sm text-muted">لا توجد أنشطة تطابق عوامل التصفية.</p>:null}</div>
    {activity?<Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>{activity.name}</CardTitle><p className="mt-1 text-xs text-muted">فريق النشاط ومهامه منفصلان عن مساهمي توثيق المتطلب.</p></div><Badge variant="primary">{statusLabels[activity.status]??activity.status}</Badge></div></CardHeader><CardContent><div className="flex gap-2 overflow-x-auto pb-2">{availableTabs.map(item=><Button key={item} size="sm" variant={tab===item?"default":"outline"} onClick={()=>setTab(item)}>{item}</Button>)}</div><div id="activity-tasks" className="mt-5">{tab==="نظرة عامة"?<Overview activity={activity} metrics={selectedMetrics} canEdit={canEdit} update={updateActivity}/>:tab==="الخطة والجدول الزمني"?<Milestones rows={arr(activity.milestones)} canEdit={canEdit} add={row=>addRecord("milestones",row)} update={(index,patch)=>updateRecord("milestones",index,patch)}/>:tab==="الفريق والمسؤوليات"?<Repeatable title="فريق النشاط" rows={arr(activity.team)} canEdit={canEdit} fields={[["name","الاسم"],["department","الإدارة"],["role","الدور في النشاط"],["responsibilities","المسؤوليات"]]} add={()=>addRecord("team",{id:newId("team"),name:"",department:"",role:"",responsibilities:""})} update={(index,patch)=>updateRecord("team",index,patch)}/>:tab==="المهام"?<Tasks rows={arr(activity.tasks)} canEdit={canEdit} team={arr(activity.team)} users={users} add={row=>addRecord("tasks",row)} update={(index,patch)=>updateRecord("tasks",index,patch)}/>:tab==="اللقاءات والاجتماعات"?<Meetings rows={arr(activity.meetings)} canEdit={canEdit} add={row=>addRecord("meetings",row)} createTask={row=>addRecord("tasks",row)} update={(index,patch)=>updateRecord("meetings",index,patch)}/>:tab==="المشاركون / المستفيدون"?<Repeatable title="المشاركون والمستفيدون" rows={arr(activity.participants)} canEdit={canEdit} fields={[["name","الاسم"],["organization","الجهة / الإدارة"],["category","الفئة / الدور"],["attendance","حالة الحضور"]]} add={()=>addRecord("participants",{id:newId("participant"),name:"",organization:"",category:"",attendance:"مسجل"})} update={(index,patch)=>updateRecord("participants",index,patch)}/>:tab==="الملفات والتصاميم"?<Files activity={activity} canEdit={canEdit} add={row=>addRecord("files",row)} update={(index,patch)=>updateRecord("files",index,patch)}/>:tab==="المخرجات"?<Repeatable title="مخرجات النشاط" rows={arr(activity.outputs)} canEdit={canEdit} fields={[["name","اسم المخرج"],["type","النوع"],["owner","المسؤول"],["status","الحالة"],["completedAt","تاريخ الإنجاز"]]} add={()=>addRecord("outputs",{id:newId("output"),name:"",type:"",owner:"",status:"قيد التنفيذ"})} update={(index,patch)=>updateRecord("outputs",index,patch)}/>:tab==="الأدلة والإغلاق"?<Closure activity={activity} canEdit={canEdit} onClose={closeActivity}/>:<ActivityLog rows={arr(activity.log)}/>}</div></CardContent></Card>:<Card><CardContent className="p-10 text-center text-sm text-muted">لا توجد أنشطة في الخطة. أضف أول نشاط للبدء.</CardContent></Card>}
    {notice?<p className="rounded-lg bg-primary-50 p-3 text-sm">{notice}</p>:null}
  </div></EditContext.Provider>;
}

function Overview({activity,metrics,canEdit,update}:{activity:Activity;metrics:{done:number;total:number;overdue:number};canEdit:boolean;update:(key:string,value:unknown)=>void}){return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border p-3"><p className="text-xs text-muted">التقدم</p><b>{String(activity.progress||0)}%</b></div><div className="rounded-xl border p-3"><p className="text-xs text-muted">المهام</p><b>{metrics.done}/{metrics.total} مكتملة</b></div><div className="rounded-xl border p-3"><p className="text-xs text-muted">المتأخر</p><b className={metrics.overdue?"text-danger":""}>{metrics.overdue}</b></div></div><div className="grid gap-4 md:grid-cols-2"><Select label="نوع النشاط" value={activity.type} values={activityTypes} onChange={value=>canEdit&&update("type",value)}/>{[["name","اسم النشاط"],["manager","مدير النشاط"],["owningDepartment","الإدارة المالكة"],["startDate","تاريخ البداية"],["endDate","تاريخ النهاية"],["location","الموقع / Online / Hybrid"],["audience","الجمهور المستهدف"],["objective","الهدف"],["description","الوصف"]].map(([key,label])=><Text key={key} label={label} value={activity[key]} area={["objective","description"].includes(key)} type={key.includes("Date")?"date":"text"} onChange={value=>canEdit&&update(key,value)}/>)}</div></div>}
function Milestones({rows,canEdit,add,update}:{rows:Row[];canEdit:boolean;add:(row:Row)=>void;update:(index:number,patch:Row)=>void}){return <div><div className="flex justify-between"><h3 className="font-bold">التسلسل الزمني والمحطات</h3>{canEdit?<Button size="sm" onClick={()=>add({id:newId("milestone"),title:"محطة جديدة",date:"",owner:"",status:"لم تبدأ",description:""})}><Plus className="h-4 w-4"/>إضافة محطة</Button>:null}</div><div className="mt-4 space-y-3">{rows.map((row,index)=><div key={String(row.id)} className="grid gap-3 rounded-xl border p-4 md:grid-cols-4"><Text label="العنوان" value={row.title} onChange={value=>update(index,{title:value})}/><Text label="الموعد" type="date" value={row.date} onChange={value=>update(index,{date:value})}/><Text label="المسؤول" value={row.owner} onChange={value=>update(index,{owner:value})}/><Select label="الحالة" value={row.status} values={["لم تبدأ","قيد التنفيذ","مكتملة","متأخرة"]} onChange={value=>update(index,{status:value})}/><div className="md:col-span-4"><Text label="الوصف / الاعتماديات / ملاحظات" value={row.description} area onChange={value=>update(index,{description:value})}/></div></div>)}</div></div>}
function Repeatable({title,rows,fields,canEdit,add,update}:{title:string;rows:Row[];fields:string[][];canEdit:boolean;add:()=>void;update:(index:number,patch:Row)=>void}){return <div><div className="flex justify-between"><h3 className="font-bold">{title}</h3>{canEdit?<Button size="sm" onClick={add}><Plus className="h-4 w-4"/>إضافة سجل</Button>:null}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{rows.map((row,index)=><div key={String(row.id||index)} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2">{fields.map(([key,label])=><Text key={key} label={label} value={row[key]} onChange={value=>update(index,{[key]:value})}/>)}</div>)}</div></div>}
function Tasks({rows,team,users,canEdit,add,update}:{rows:Row[];team:Row[];users:{id:string;name:string;email:string}[];canEdit:boolean;add:(row:Row)=>void;update:(index:number,patch:Row)=>void}){return <div><div className="flex justify-between"><div><h3 className="font-bold">توزيع المهام والمتابعة</h3><p className="text-xs text-muted">المهام المسندة لمستخدم منصة تظهر في «مهامي» بعد الحفظ.</p></div>{canEdit?<Button size="sm" onClick={()=>add({id:newId("task"),title:"مهمة جديدة",description:"",assignee:"",assignedUserId:"",priority:"MEDIUM",assignedAt:new Date().toISOString().slice(0,10),dueDate:"",status:"NOT_STARTED",nextAction:"فتح المهمة"})}><Plus className="h-4 w-4"/>إضافة مهمة</Button>:null}</div><div className="mt-4 space-y-3">{rows.map((row,index)=><div key={String(row.id)} className="grid gap-3 rounded-xl border p-4 md:grid-cols-4"><Text label="المهمة" value={row.title} onChange={value=>update(index,{title:value})}/><label className="text-xs font-semibold">مستخدم المنصة<select disabled={!canEdit} value={String(row.assignedUserId||"")} onChange={event=>{const user=users.find(item=>item.id===event.target.value);update(index,{assignedUserId:event.target.value,assignee:user?.name||row.assignee});}} className="mt-1 h-10 w-full rounded-lg border bg-transparent px-3"><option value="">مسؤول نصي فقط</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><Select label="المسؤول داخل فريق النشاط" value={row.assignee} values={team.map(item=>String(item.name||"")).filter(Boolean)} onChange={value=>update(index,{assignee:value})}/><Text label="الموعد النهائي" type="date" value={row.dueDate} onChange={value=>update(index,{dueDate:value})}/><Select label="الحالة" value={row.status} values={Object.keys(taskLabels)} onChange={value=>update(index,{status:value,completedAt:value==="COMPLETED"?new Date().toISOString():null})}/><div className="md:col-span-3"><Text label="الوصف / الملاحظات" value={row.description} area onChange={value=>update(index,{description:value})}/></div><div className="rounded-lg bg-slate-50 p-3 text-xs"><b>{taskLabels[String(row.status)]??row.status}</b><p>أُسندت: {String(row.assignedAt||"—")}</p><p>أُنجزت: {row.completedAt?new Date(String(row.completedAt)).toLocaleDateString("ar-SA"):"—"}</p></div></div>)}</div></div>}
function Meetings({rows,canEdit,add,createTask,update}:{rows:Row[];canEdit:boolean;add:(row:Row)=>void;createTask:(row:Row)=>void;update:(index:number,patch:Row)=>void}){return <div><div className="flex justify-between"><h3 className="font-bold">اللقاءات والاجتماعات</h3>{canEdit?<Button size="sm" onClick={()=>add({id:newId("meeting"),name:"لقاء جديد",type:"تحضيري",date:"",location:"",organizer:"",objective:"",decisions:""})}><Plus className="h-4 w-4"/>إضافة لقاء</Button>:null}</div><div className="mt-4 space-y-3">{rows.map((row,index)=><div key={String(row.id)} className="rounded-xl border p-4"><div className="grid gap-3 md:grid-cols-4"><Text label="اسم اللقاء" value={row.name} onChange={value=>update(index,{name:value})}/><Text label="النوع" value={row.type} onChange={value=>update(index,{type:value})}/><Text label="التاريخ" type="date" value={row.date} onChange={value=>update(index,{date:value})}/><Text label="المكان / الرابط" value={row.location} onChange={value=>update(index,{location:value})}/></div><div className="mt-3"><Text label="القرارات والملاحظات" value={row.decisions} area onChange={value=>update(index,{decisions:value})}/></div>{canEdit?<Button className="mt-3" size="sm" variant="outline" onClick={()=>createTask({id:newId("task"),title:`متابعة: ${String(row.name)}`,assignee:String(row.organizer||""),status:"NOT_STARTED",priority:"MEDIUM",assignedAt:new Date().toISOString().slice(0,10),dueDate:"",nextAction:"تنفيذ قرار الاجتماع"})}>إنشاء مهمة متابعة</Button>:null}</div>)}</div></div>}
function Files({activity,canEdit,add,update}:{activity:Activity;canEdit:boolean;add:(row:Row)=>void;update:(index:number,patch:Row)=>void}){const rows=arr(activity.files);const deliverables=arr(activity.deliverables);return <div className="space-y-5"><div><div className="flex justify-between"><div><h3 className="font-bold">ملفات العمل والتصاميم</h3><p className="text-xs text-muted">ملفات تشغيلية؛ لا تصبح دليل متطلب إلا بالربط الصريح.</p></div>{canEdit?<Button size="sm" onClick={()=>add({id:newId("file"),title:"ملف جديد",category:"تصميم",fileName:"",version:1,reviewState:"مسودة",markedAsEvidence:"لا"})}><Plus className="h-4 w-4"/>إضافة ملف</Button>:null}</div><div className="mt-3 grid gap-3 md:grid-cols-2">{rows.map((row,index)=><div key={String(row.id)} className="rounded-xl border p-4"><Text label="العنوان" value={row.title} onChange={value=>update(index,{title:value})}/><div className="mt-2 grid grid-cols-2 gap-2"><Text label="اسم الملف" value={row.fileName} onChange={value=>update(index,{fileName:value})}/><Text label="الإصدار" value={row.version} onChange={value=>update(index,{version:value})}/><Select label="حالة المراجعة" value={row.reviewState} values={["مسودة","قيد المراجعة","يحتاج تعديل","معتمد"]} onChange={value=>update(index,{reviewState:value})}/><Select label="ربطه كدليل" value={row.markedAsEvidence} values={["لا","نعم"]} onChange={value=>update(index,{markedAsEvidence:value})}/></div></div>)}</div></div><div><h3 className="font-bold">مراجعة التسليمات</h3><div className="mt-3 space-y-2">{deliverables.map(row=><div key={String(row.id)} className="rounded-lg bg-slate-50 p-3 text-xs"><b>{String(row.name)}</b> · الإصدار {String(row.version)} · {String(row.reviewState)}<p className="mt-1">{String(row.reviewNote||"")}</p></div>)}</div></div></div>}
function Closure({activity,canEdit,onClose}:{activity:Activity;canEdit:boolean;onClose:()=>void}){const checks=[["المهام الأساسية",!arr(activity.tasks).some(row=>!["COMPLETED","CANCELLED"].includes(String(row.status)))],["المواعيد والمحطات",!arr(activity.milestones).some(row=>row.status!=="مكتملة")],["اللقاءات",arr(activity.meetings).length>0],["المخرجات",arr(activity.outputs).length>0],["دليل المتطلب",arr(activity.files).some(row=>row.markedAsEvidence==="نعم")]] as const;return <div><h3 className="font-bold">قائمة إغلاق النشاط</h3><div className="mt-3 space-y-2">{checks.map(([label,done])=><p key={label} className="flex items-center gap-2 rounded-lg border p-3 text-sm">{done?<CheckCircle2 className="h-4 w-4 text-success"/>:<AlertTriangle className="h-4 w-4 text-warning"/>}{label}<Badge className="mr-auto" variant={done?"success":"warning"}>{done?"مكتمل":"ناقص"}</Badge></p>)}</div>{canEdit?<Button className="mt-4" onClick={onClose}>إغلاق النشاط</Button>:null}{activity.status==="COMPLETED"?<div className="mt-5 rounded-xl bg-primary-50 p-4 text-sm"><b>الملخص التشغيلي النهائي</b><p className="mt-2">{activity.name} · {String(activity.objective||"")}</p><p>الفريق: {arr(activity.team).length} · المحطات: {arr(activity.milestones).length} · اللقاءات: {arr(activity.meetings).length} · المخرجات: {arr(activity.outputs).length}</p></div>:null}</div>}
function ActivityLog({rows}:{rows:Row[]}){return <div><h3 className="font-bold">سجل النشاط</h3><div className="mt-3 space-y-2">{rows.map((row,index)=><p key={index} className="rounded-lg border p-3 text-xs"><Clock3 className="ml-2 inline h-4 w-4 text-primary"/>{String(row.action)} · {new Date(String(row.date)).toLocaleString("ar-SA")}</p>)}</div></div>}
