"use client";
import {useState} from "react";
import {AlertTriangle,ArrowLeft,CheckCircle2,ExternalLink,Link2,Plus,Search} from "lucide-react";
import {PreviewLink as Link} from "@/components/layout/preview-link";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Progress} from "@/components/ui/progress";
import type {ContributionView} from "@/modules/requirement-contributions/types";import type {WorkspaceData} from "../workspace-status";

type Row=Record<string,any>;type Tab="overview"|"plan"|"meetings"|"commitments"|"outputs"|"reports"|"decisions"|"corrective"|"files"|"team"|"readiness"|"log";
const arr=(v:unknown)=>Array.isArray(v)?v as Row[]:[];const makeId=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
const tabs:[Tab,string][]=[["overview","نظرة عامة"],["plan","خطة التفعيل"],["meetings","الاجتماعات الدورية"],["commitments","الالتزامات والمهام"],["outputs","المخرجات"],["reports","التقارير الدورية"],["decisions","القرارات"],["corrective","الإجراءات التصحيحية"],["files","الملفات والأدلة"],["team","فريق العمل والتوكيلات"],["readiness","الجاهزية"],["log","السجل"]];

export function CooperationActivationWorkspace({data,sourceData,canEdit,personaKey="admin",initialActivationId,onChange,contributions=[],evidence=[]}:{data:WorkspaceData;sourceData:WorkspaceData;canEdit:boolean;personaKey?:string;initialActivationId?:string;onChange:(value:WorkspaceData)=>void;contributions?:ContributionView[];evidence?:Row[]}){
 const activations=arr(data.cooperationActivations);const found=activations.findIndex(row=>row.id===initialActivationId);const [selected,setSelected]=useState<number|null>(found>=0?found:null);const [tab,setTab]=useState<Tab>("overview");const [query,setQuery]=useState("");const [notice,setNotice]=useState("");const current=selected===null?null:activations[selected];const restricted=personaKey==="partner";const viewer=personaKey==="viewer";const visibleTabs=tabs.filter(([key])=>!viewer||["overview","meetings","outputs","readiness"].includes(key)).filter(([key])=>!restricted||!["decisions","log"].includes(key));
 const sourceCooperations=arr(sourceData.cooperations);const sourceAgreements=arr(sourceData.agreements);const sourceContacts=arr(sourceData.partnerContacts);
 function replace(row:Row){onChange({...data,cooperationActivations:activations.map((item,index)=>index===selected?row:item)});}function update(key:string,value:unknown){if(current)replace({...current,[key]:value,log:[{date:new Date().toISOString(),actor:"المستخدم الحالي",action:`تحديث ${key}`},...arr(current.log)]});}
 function open(index:number){setSelected(index);const id=activations[index]?.id;if(id)window.history.pushState({},"",`/activities/requirements/5-23-2-r4/activations/${id}${window.location.search}`);}
 function linkSource(source:Row){const partner=String(source.partnerName);const agreement=sourceAgreements.find(row=>row.cooperationName===partner);const contact=sourceContacts.find(row=>row.cooperationName===partner);const row={id:String(agreement?.agreementId||makeId("activation")),cooperationName:partner,agreementTitle:String(agreement?.title||""),agreementReference:String(agreement?.referenceNumber||""),scope:String(agreement?.scope||source.scope||""),owner:String(source.internalOwner||""),department:String(source.owningDepartment||""),responsible:String(source.internalOwner||""),partnerContact:String(contact?.name||""),partnerEmail:String(contact?.email||""),startDate:String(agreement?.startDate||source.startDate||""),endDate:String(agreement?.endDate||source.endDate||""),status:"مسودة تفعيل",nextAction:"إعداد خطة التفعيل",plan:{},milestones:[],meetings:[],commitments:[],tasks:[],outputs:[],reports:[],decisions:[],correctiveActions:[],files:[],log:[{date:new Date().toISOString(),actor:"المستخدم الحالي",action:"ربط علاقة تعاون قائمة"}]};onChange({...data,cooperationActivations:[...activations,row]});setSelected(activations.length);setNotice("تم ربط علاقة التعاون القائمة دون نسخها كسجل شراكة جديد.");}
 if(!current){const available=sourceCooperations.filter(source=>!activations.some(row=>row.cooperationName===source.partnerName));return <Registry rows={activations} query={query} setQuery={setQuery} canEdit={canEdit} open={open} available={available} link={linkSource}/>;}
 const metrics=derive(current,evidence,contributions);return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" onClick={()=>setSelected(null)}><ArrowLeft className="h-4 w-4"/>علاقات التعاون المفعّلة</Button><div className="flex gap-2"><Badge variant="primary">السياق من 5.23.1-03</Badge><Badge variant="warning">التفعيل لا يساوي وجود الاتفاقية</Badge></div></div>
 <Card className="border-primary/20"><CardContent className="p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-muted">{current.agreementTitle} · {current.agreementReference}</p><h2 className="mt-1 text-xl font-bold">{current.cooperationName}</h2><p className="mt-1 text-xs text-muted">{current.department} · {current.owner}</p></div><Badge variant="warning">{current.status}</Badge></div><div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{[[metrics.held,"اجتماعات منعقدة"],[metrics.quarters,"أرباع مكتملة"],[metrics.openCommitments,"التزامات مفتوحة"],[metrics.outputs,"مخرجات"],[metrics.reports,"تقارير"],[metrics.corrective,"إجراءات مفتوحة"],[metrics.tasks,"مهام معلقة"],[`${metrics.readiness}%`,"جاهزية داخلية"]].map(([value,label])=><div key={label} className="rounded-lg border p-2 text-center"><b>{value}</b><p className="text-[11px] text-muted">{label}</p></div>)}</div><p className="mt-4 rounded-lg bg-primary-50 p-3 text-xs"><b>الإجراء التالي:</b> {current.nextAction}</p></CardContent></Card>
 <div className="flex gap-2 overflow-x-auto pb-2">{visibleTabs.map(([key,label])=><Button key={key} size="sm" variant={tab===key?"default":"outline"} onClick={()=>setTab(key)}>{label}</Button>)}</div>
 {tab==="overview"?<Overview row={current} canEdit={canEdit} update={update} metrics={metrics}/>:null}
 {tab==="plan"?<Plan row={current} canEdit={canEdit} update={update}/>:null}
 {tab==="meetings"?<><QuarterBoard meetings={arr(current.meetings)}/><Records title="سجل اجتماعات المتابعة" rows={arr(current.meetings)} canEdit={canEdit} columns={["title","quarter","date","organizer","minutesState","status"]} labels={["الاجتماع","الربع","التاريخ","المنظم","المحضر","الحالة"]} add={()=>update("meetings",[...arr(current.meetings),{id:makeId("meeting"),title:"اجتماع متابعة جديد",quarter:"Q4",date:"",organizer:"",minutesState:"غير متوفر",status:"مسودة"}])} change={(i,p)=>update("meetings",patch(arr(current.meetings),i,p))}/><MeetingMinutes meetings={arr(current.meetings)}/></>:null}
 {tab==="commitments"?<><Records title="الالتزامات" rows={arr(current.commitments)} canEdit={canEdit} columns={["title","source","responsibility","owner","dueDate","status"]} labels={["الالتزام","المصدر","المسؤولية","المالك","الموعد","الحالة"]} add={()=>update("commitments",[...arr(current.commitments),{id:makeId("commitment"),title:"التزام جديد",source:"",responsibility:"مشترك",owner:"",dueDate:"",status:"لم يبدأ"}])} change={(i,p)=>update("commitments",patch(arr(current.commitments),i,p))}/><Records title="المهام المرتبطة" rows={arr(current.tasks)} canEdit={canEdit} columns={["title","assignee","priority","dueDate","status","nextAction"]} labels={["المهمة","المسؤول","الأولوية","الموعد","الحالة","الإجراء التالي"]} add={()=>update("tasks",[...arr(current.tasks),{id:makeId("task"),title:"مهمة متابعة",assignee:"",priority:"MEDIUM",dueDate:"",status:"OPEN",source:"manual",section:"commitments",nextAction:"فتح مساحة التفعيل"}])} change={(i,p)=>update("tasks",patch(arr(current.tasks),i,p))}/></>:null}
 {tab==="outputs"?<Records title="المخرجات الفعلية" rows={arr(current.outputs)} canEdit={canEdit} columns={["name","type","commitmentId","meetingId","owner","status"]} labels={["المخرج","النوع","الالتزام","الاجتماع","المالك","الحالة"]} add={()=>update("outputs",[...arr(current.outputs),{id:makeId("output"),name:"مخرج جديد",type:"تقرير",commitmentId:"",meetingId:"",owner:"",status:"مسودة"}])} change={(i,p)=>update("outputs",patch(arr(current.outputs),i,p))}/>:null}
 {tab==="reports"?<><Records title="التقارير الدورية" rows={arr(current.reports)} canEdit={canEdit} columns={["title","period","cooperationStatus","responsible","reviewStatus","approvalStatus"]} labels={["التقرير","الفترة","حالة التعاون","المسؤول","المراجعة","الاعتماد"]} add={()=>update("reports",[...arr(current.reports),{id:makeId("report"),title:"تقرير دوري جديد",period:"",cooperationStatus:"",responsible:"",reviewStatus:"مسودة",approvalStatus:"غير معتمد"}])} change={(i,p)=>update("reports",patch(arr(current.reports),i,p))}/><ReportSummary row={current}/></>:null}
 {tab==="decisions"?<Records title="القرارات" rows={arr(current.decisions)} canEdit={canEdit} columns={["title","source","date","owner","dueDate","status"]} labels={["القرار","المصدر","التاريخ","المالك","الموعد","الحالة"]} add={()=>update("decisions",[...arr(current.decisions),{id:makeId("decision"),title:"قرار جديد",source:"",date:"",owner:"",dueDate:"",status:"مفتوح"}])} change={(i,p)=>update("decisions",patch(arr(current.decisions),i,p))}/>:null}
 {tab==="corrective"?<Records title="الإجراءات التصحيحية" rows={arr(current.correctiveActions)} canEdit={canEdit} columns={["issue","action","source","responsible","dueDate","status"]} labels={["الفجوة","الإجراء","المصدر","المسؤول","الموعد","الحالة"]} add={()=>update("correctiveActions",[...arr(current.correctiveActions),{id:makeId("corrective"),issue:"فجوة جديدة",action:"",source:"",responsible:"",dueDate:"",status:"مفتوح"}])} change={(i,p)=>update("correctiveActions",patch(arr(current.correctiveActions),i,p))}/>:null}
 {tab==="files"?<EvidenceView row={current} evidence={evidence} canEdit={canEdit} update={update}/>:null}
 {tab==="team"?<Team contributions={contributions} tasks={arr(current.tasks)}/>:null}
 {tab==="readiness"?<Readiness metrics={metrics}/>:null}
 {tab==="log"?<Card><CardHeader><CardTitle>سجل نشاط التفعيل</CardTitle></CardHeader><CardContent>{arr(current.log).map((item,index)=><p key={index} className="border-b py-3 text-xs"><b>{item.actor}</b> · {item.action} · {new Date(item.date).toLocaleDateString("ar-SA")}</p>)}</CardContent></Card>:null}
 {notice?<p className="rounded-lg bg-primary-50 p-3 text-sm">{notice}</p>:null}</div>;
}

function Registry({rows,query,setQuery,canEdit,open,available,link}:{rows:Row[];query:string;setQuery:(v:string)=>void;canEdit:boolean;open:(i:number)=>void;available:Row[];link:(r:Row)=>void}){const filtered=rows.filter(row=>`${row.cooperationName} ${row.owner} ${row.status}`.includes(query));return <div className="space-y-5"><Card><CardHeader><CardTitle>تفعيل علاقات التعاون القائمة</CardTitle></CardHeader><CardContent><label className="relative block"><Search className="absolute right-3 top-3 h-4 w-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالجهة أو المالك أو الحالة" className="h-10 w-full rounded-lg border bg-transparent pr-10 pl-3 text-sm"/></label>{canEdit&&available.length?<div className="mt-4 flex flex-wrap gap-2">{available.map(source=><Button key={source.partnerName} onClick={()=>link(source)}><Link2 className="h-4 w-4"/>ربط {source.partnerName}</Button>)}</div>:canEdit&&!available.length&&!rows.length?<Button asChild className="mt-4" variant="outline"><Link href="/strategy/requirements/5-23-1-r3">إنشاء علاقة تعاون في 5.23.1 <ExternalLink className="h-4 w-4"/></Link></Button>:null}</CardContent></Card><div className="grid gap-4 lg:grid-cols-2">{filtered.map((row,index)=>{const m=derive(row,[],[]);return <Card key={row.id}><CardContent className="p-5"><div className="flex justify-between"><div><h3 className="font-bold">{row.cooperationName}</h3><p className="text-xs text-muted">{row.agreementTitle}</p></div><Badge variant="warning">{row.status}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span><b>{m.held}</b><small className="block text-muted">اجتماعات</small></span><span><b>{m.outputs}</b><small className="block text-muted">مخرجات</small></span><span><b>{m.corrective}</b><small className="block text-muted">تصحيحية مفتوحة</small></span></div><Button className="mt-4" size="sm" onClick={()=>open(rows.indexOf(row))}>فتح مساحة تفعيل التعاون <ArrowLeft className="h-4 w-4"/></Button></CardContent></Card>})}</div></div>}
function Overview({row,canEdit,update,metrics}:{row:Row;canEdit:boolean;update:(k:string,v:unknown)=>void;metrics:ReturnType<typeof derive>}){const fields=[["cooperationName","الجهة"],["agreementTitle","الاتفاقية"],["scope","نطاق التعاون"],["owner","المالك"],["department","الإدارة المالكة"],["responsible","المسؤول الداخلي"],["partnerContact","جهة اتصال الشريك"],["startDate","البداية"],["endDate","النهاية"],["status","حالة التفعيل"],["nextAction","الإجراء التالي"]];return <Card><CardHeader><CardTitle>ملخص حالة التفعيل</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{fields.map(([key,label])=><label key={key} className="text-xs font-semibold">{label}<input disabled={!canEdit||["cooperationName","agreementTitle","scope","partnerContact","startDate","endDate"].includes(key)} value={String(row[key]??"")} onChange={e=>update(key,e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-transparent px-3"/></label>)}</div><p className="mt-4 text-xs text-muted">آخر اجتماع: {metrics.lastMeeting||"—"} · الاجتماع القادم: {metrics.nextMeeting||"—"} · آخر تقرير: {arr(row.reports).at(-1)?.title||"—"}</p></CardContent></Card>}
function Plan({row,canEdit,update}:{row:Row;canEdit:boolean;update:(k:string,v:unknown)=>void}){const plan=row.plan??{};const fields=[["objectives","أهداف التفعيل"],["expectedOutputs","المخرجات المتوقعة"],["responsibleDepartments","الإدارات المسؤولة"],["partnerResponsibilities","مسؤوليات الشريك"],["owner","المالك"],["status","الحالة"]];return <div className="space-y-4"><Card><CardHeader><CardTitle>خطة تفعيل الاتفاقية</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{fields.map(([key,label])=><label key={key} className="text-xs font-semibold">{label}<textarea disabled={!canEdit} value={String(plan[key]??"")} onChange={e=>update("plan",{...plan,[key]:e.target.value})} className="mt-1 min-h-20 w-full rounded-lg border bg-transparent p-3"/></label>)}</CardContent></Card><Records title="المحطات المستهدفة" rows={arr(row.milestones)} canEdit={canEdit} columns={["name","targetDate","owner","status"]} labels={["المحطة","التاريخ","المالك","الحالة"]} add={()=>update("milestones",[...arr(row.milestones),{id:makeId("milestone"),name:"محطة جديدة",targetDate:"",owner:"",status:"لم تبدأ"}])} change={(i,p)=>update("milestones",patch(arr(row.milestones),i,p))}/></div>}
function QuarterBoard({meetings}:{meetings:Row[]}){return <Card><CardHeader><CardTitle>المتابعة الربعية 2026</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-4">{["Q1","Q2","Q3","Q4"].map((q,index)=>{const item=meetings.find(m=>m.quarter===q);const complete=item?.status==="مكتمل"&&item?.minutesState==="معتمد";const due=index<3;return <div key={q} className="rounded-xl border p-4"><div className="flex justify-between"><b>{q}</b>{complete?<CheckCircle2 className="h-5 w-5 text-success"/>:<AlertTriangle className="h-5 w-5 text-warning"/>}</div><p className="mt-2 text-xs">{complete?"مكتمل":item?String(item.minutesState||item.status):due?"اجتماع المتابعة مفقود":"لم يحن موعده"}</p></div>})}</CardContent></Card>}
function MeetingMinutes({meetings}:{meetings:Row[]}){return <Card><CardHeader><CardTitle>ملخص المحاضر والقرارات</CardTitle></CardHeader><CardContent>{meetings.map(row=><div key={row.id} className="border-b py-3 text-xs"><b>{row.title}</b><p className="mt-1">الملخص: {row.minutes||"غير متوفر"}</p><p>القرارات: {row.decisions||"غير موثقة"} · الالتزامات: {row.commitments||"غير موثقة"}</p></div>)}</CardContent></Card>}
function Records({title,rows,canEdit,columns,labels,add,change}:{title:string;rows:Row[];canEdit:boolean;columns:string[];labels:string[];add:()=>void;change:(i:number,p:Row)=>void}){return <Card><CardHeader><div className="flex justify-between gap-3"><div><CardTitle>{title}</CardTitle><p className="mt-1 text-xs text-muted">{rows.length} سجلًا مترابطًا.</p></div>{canEdit?<Button size="sm" onClick={add}><Plus className="h-4 w-4"/>إضافة</Button>:null}</div></CardHeader><CardContent className="space-y-3">{rows.map((row,index)=><div key={row.id??index} className="grid gap-2 rounded-xl border p-3 md:grid-cols-3">{columns.map((key,i)=><label key={key} className="text-[11px] font-semibold">{labels[i]}<input disabled={!canEdit} value={String(row[key]??"")} onChange={e=>change(index,{[key]:e.target.value})} className="mt-1 h-9 w-full rounded-lg border bg-transparent px-2 text-xs"/></label>)}</div>)}{!rows.length?<p className="py-6 text-center text-sm text-muted">لا توجد سجلات بعد.</p>:null}</CardContent></Card>}
function ReportSummary({row}:{row:Row}){return <Card><CardHeader><CardTitle>ملخص دوري مشتق من السجلات</CardTitle></CardHeader><CardContent className="grid gap-2 text-xs sm:grid-cols-3"><p>الاجتماعات: {arr(row.meetings).filter(m=>m.status==="مكتمل").length}</p><p>الالتزامات المكتملة: {arr(row.commitments).filter(c=>c.status==="مكتمل").length}</p><p>المتأخرة: {arr(row.commitments).filter(c=>c.status==="متأخر").length}</p><p>المخرجات: {arr(row.outputs).length}</p><p>القرارات المفتوحة: {arr(row.decisions).filter(d=>d.status!=="مكتمل").length}</p><p>الإجراءات التصحيحية المفتوحة: {arr(row.correctiveActions).filter(c=>!["مغلق","مكتمل"].includes(c.status)).length}</p></CardContent></Card>}
function EvidenceView({row,evidence,canEdit,update}:{row:Row;evidence:Row[];canEdit:boolean;update:(k:string,v:unknown)=>void}){return <div className="space-y-4"><Records title="ملفات العمل والسجلات الداعمة" rows={arr(row.files)} canEdit={canEdit} columns={["title","category","fileName","reviewState","markedAsEvidence"]} labels={["الملف","الفئة","اسم الملف","المراجعة","مرشح للإثبات"]} add={()=>update("files",[...arr(row.files),{id:makeId("file"),title:"ملف جديد",category:"محضر",fileName:"",reviewState:"مسودة",markedAsEvidence:"لا"}])} change={(i,p)=>update("files",patch(arr(row.files),i,p))}/><Card><CardHeader><CardTitle>الدليل الرسمي للمتطلب</CardTitle></CardHeader><CardContent><p className="text-sm">الاتفاقية سياق فقط؛ الاجتماعات والمخرجات والتقارير والمتابعة هي ما يثبت التفعيل.</p><p className="mt-2 text-xs text-muted">الأدلة المرتبطة: {evidence.length} · المعتمدة: {evidence.filter(item=>item.reviewStatus==="APPROVED").length}</p><a href="#requirement-evidence" className="mt-3 inline-flex text-sm font-semibold text-primary">فتح رفع ومراجعة الدليل</a></CardContent></Card></div>}
function Team({contributions,tasks}:{contributions:ContributionView[];tasks:Row[]}){return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>التوكيلات والمساهمات</CardTitle></CardHeader><CardContent>{contributions.map(row=><div key={row.id} className="border-b py-3 text-xs"><b>{row.contributorName}</b><p>{row.departmentName} · {row.sectionKey} · {row.status}</p></div>)}{!contributions.length?<p className="text-sm text-muted">لا توجد توكيلات.</p>:null}<a href="#section-collaboration" className="mt-3 inline-flex text-sm font-semibold text-primary">إدارة التوكيلات</a></CardContent></Card><Card><CardHeader><CardTitle>تمييز المهمة عن التوكيل</CardTitle></CardHeader><CardContent className="text-xs"><p><b>المهمة:</b> إجراء محدد، مثل رفع المحضر.</p><p className="mt-2"><b>التوكيل:</b> مسؤولية تعبئة وتسليم نطاق كامل للمراجعة.</p><p className="mt-3">المهام المفتوحة: {tasks.filter(t=>!["COMPLETED","CANCELLED"].includes(t.status)).length}</p></CardContent></Card></div>}
function Readiness({metrics}:{metrics:ReturnType<typeof derive>}){return <Card><CardHeader><CardTitle>فحص جاهزية تفعيل التعاون</CardTitle></CardHeader><CardContent><Progress value={metrics.readiness}/><p className="mt-2 text-sm font-bold">الجاهزية الداخلية التقديرية: {metrics.readiness}%</p><div className="mt-4 space-y-2">{metrics.gaps.map(gap=><p key={gap} className="flex gap-2 text-xs"><AlertTriangle className="h-4 w-4 text-warning"/>{gap}</p>)}</div><p className="mt-4 text-xs text-muted">هذه جاهزية داخلية تقديرية ولا تمثل اعتمادًا رسميًا من هيئة الحكومة الرقمية.</p></CardContent></Card>}
function derive(row:Row,evidence:Row[],contributions:ContributionView[]){const meetings=arr(row.meetings);const held=meetings.filter(m=>["مكتمل","بانتظار المحضر"].includes(m.status)).length;const quarters=meetings.filter(m=>m.status==="مكتمل"&&m.minutesState==="معتمد").length;const openCommitments=arr(row.commitments).filter(c=>!["مكتمل","ملغي"].includes(c.status)).length;const corrective=arr(row.correctiveActions).filter(c=>!["مكتمل","مغلق"].includes(c.status)).length;const tasks=arr(row.tasks).filter(t=>!["COMPLETED","CANCELLED"].includes(t.status)).length;const gaps:string[]=[];if(!row.cooperationName||!row.agreementTitle)gaps.push("لم يتم ربط علاقة التعاون والاتفاقية بصورة صحيحة.");for(const q of ["Q1","Q2","Q3"]){const meeting=meetings.find(m=>m.quarter===q);if(!meeting)gaps.push(`لا يوجد اجتماع متابعة موثق للربع ${q.slice(1)}.`);else if(meeting.minutesState!=="معتمد")gaps.push(`محضر اجتماع ${q} غير مكتمل أو غير معتمد.`);}if(arr(row.commitments).some(c=>c.status==="متأخر"))gaps.push("يوجد التزام متأخر يحتاج إلى متابعة.");if(!arr(row.reports).length)gaps.push("لا يوجد تقرير دوري موثق.");if(corrective)gaps.push("يوجد إجراء تصحيحي ما زال مفتوحًا.");if(!evidence.length)gaps.push("دليل التفعيل الرسمي غير مرفوع أو غير معتمد.");if(contributions.some(c=>!["COMPLETED","CANCELLED"].includes(c.status)))gaps.push("توجد مساهمة مسندة لم تُقبل بعد.");const readiness=Math.max(0,Math.round((7-Math.min(gaps.length,7))/7*100));const dates=meetings.filter(m=>m.date).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return{held,quarters,openCommitments,outputs:arr(row.outputs).length,reports:arr(row.reports).length,corrective,tasks,readiness,gaps,lastMeeting:dates.filter(m=>new Date(m.date)<=new Date("2026-08-20")).at(-1)?.date,nextMeeting:dates.find(m=>new Date(m.date)>new Date("2026-08-20"))?.date};}
function patch(rows:Row[],index:number,value:Row){return rows.map((row,i)=>i===index?{...row,...value}:row)}
