"use client";
import {useState} from "react";
import {AlertTriangle,ArrowLeft,CheckCircle2,Link2,Plus,Search} from "lucide-react";
import {PreviewLink as Link} from "@/components/layout/preview-link";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Progress} from "@/components/ui/progress";
import type {WorkspaceData} from "../workspace-status";import type {ContributionView} from "@/modules/requirement-contributions/types";

type Row=Record<string,any>;type Tab="overview"|"timeline"|"challenges"|"people"|"solutions"|"judging"|"prototypes"|"projects"|"impact"|"files"|"evidence"|"tasks"|"closure";
const tabs:[Tab,string][]=[["overview","نظرة عامة"],["timeline","الجدول واللقاءات"],["challenges","التحديات"],["people","المشاركون والفرق"],["solutions","الحلول والمشاركات"],["judging","التحكيم والفائزون"],["prototypes","النماذج الأولية"],["projects","المشاريع الناتجة"],["impact","الأثر"],["files","الملفات والشهادات"],["evidence","الأدلة"],["tasks","المهام والتوكيلات"],["closure","الإغلاق والسجل"]];
const arr=(value:unknown)=>Array.isArray(value)?value as Row[]:[];const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;

export function OpenInnovationWorkspace({data,canEdit,personaKey="admin",initialEventId,onChange,contributions=[],evidence=[],annualPlanData={}}:{data:WorkspaceData;canEdit:boolean;personaKey?:string;initialEventId?:string;onChange:(data:WorkspaceData)=>void;contributions?:ContributionView[];evidence?:Row[];annualPlanData?:WorkspaceData}){
 const events=arr(data.openInnovationEvents);const selected=events.findIndex(event=>event.id===initialEventId);const [selectedIndex,setSelectedIndex]=useState(selected>=0?selected:null);const [tab,setTab]=useState<Tab>("overview");const [query,setQuery]=useState("");const [notice,setNotice]=useState("");const current=selectedIndex===null?null:events[selectedIndex];
 const restricted=personaKey==="partner"||personaKey==="viewer";const visibleTabs=tabs.filter(([key])=>!restricted||!["people","tasks"].includes(key));
 function replaceEvent(next:Row){onChange({...data,openInnovationEvents:events.map((event,index)=>index===selectedIndex?next:event)});}
 function openEvent(index:number){setSelectedIndex(index);const event=events[index];if(event?.id)window.history.pushState({},"",`/activities/requirements/5-23-2-r3/events/${event.id}${window.location.search}`);}
 function update(key:string,value:unknown){if(!current)return;replaceEvent({...current,[key]:value,log:[{date:new Date().toISOString(),action:"تحديث بيانات الفعالية"},...arr(current.log)]});}
 function addEvent(linked?:Row){const next={id:id("open-event"),name:String(linked?.name??linked?.activity??"فعالية ابتكار مفتوح جديدة"),type:String(linked?.type??"هاكاثون"),description:String(linked?.description??""),objective:String(linked?.objective??linked?.objectives??""),beneficiaryGroups:String(linked?.targetAudience??linked?.audience??""),approach:"",owner:String(linked?.owner??""),department:String(linked?.owningDepartment??""),responsible:String(linked?.manager??linked?.owner??""),startDate:String(linked?.startDate??""),endDate:String(linked?.endDate??""),location:String(linked?.location??""),deliveryMode:"حضوري",status:"مسودة",annualPlanActivityId:String(linked?.activityId??linked?.id??""),annualPlanActivityName:String(linked?.name??linked?.activity??""),timeline:arr(linked?.milestones),challenges:[],participants:[],teams:[],solutions:[],judges:[],judging:[],winners:[],prototypes:[],projects:[],impacts:[],files:arr(linked?.files),documentationSamples:[],tasks:arr(linked?.tasks),log:[{date:new Date().toISOString(),action:linked?"ربط فعالية بالخطة السنوية":"إنشاء فعالية ابتكار مفتوح"}]};onChange({...data,openInnovationEvents:[...events,next]});setSelectedIndex(events.length);setNotice(linked?"تم إنشاء مساحة ابتكار مفتوح مرتبطة ببيانات النشاط، دون إنشاء نشاط مكرر.":"أضيفت مسودة فعالية جديدة.");}
 const eligibleActivities=arr(annualPlanData.activities).filter(activity=>!["CANCELLED","ملغاة"].includes(String(activity.status))&&!events.some(event=>event.annualPlanActivityId===(activity.activityId??activity.id)));
 if(!current)return <Registry events={events} query={query} setQuery={setQuery} canEdit={canEdit} onOpen={openEvent} onCreate={()=>addEvent()} onLink={()=>eligibleActivities[0]?addEvent(eligibleActivities[0]):setNotice("لا يوجد نشاط مؤهل غير مرتبط في الخطة السنوية.")}/>;
 const metrics=deriveMetrics(current);const gaps=deriveGaps(current,contributions,evidence);const operational=Math.max(0,Math.round((12-gaps.operational.length)/12*100));const evidenceReady=evidence.some(item=>item.reviewStatus==="APPROVED")?100:evidence.length?67:0;
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" onClick={()=>setSelectedIndex(null)}><ArrowLeft className="h-4 w-4"/>فعاليات الابتكار المفتوح</Button><div className="flex gap-2"><Badge variant="neutral">إغلاق تشغيلي مستقل</Badge><Badge variant="warning">لا يمثل اعتماد DGA</Badge></div></div>
 <Card className="border-primary/20"><CardContent className="p-5"><div className="flex flex-wrap justify-between gap-4"><div><Badge variant="primary">{current.type}</Badge><h2 className="mt-2 text-xl font-bold">{current.name}</h2><p className="mt-1 text-xs text-muted">{current.department} · {current.startDate} — {current.endDate}</p></div><Badge variant={current.status==="مغلقة تشغيليًا"?"success":"warning"}>{current.status}</Badge></div><div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{[[metrics.participants,"مشارك"],[metrics.teams,"فريق"],[metrics.challenges,"تحديًا"],[metrics.solutions,"حلًا"],[metrics.prototypes,"نموذجًا"],[metrics.winners,"فائزًا"],[metrics.projects,"مشروعًا ناتجًا"],[`${operational}%`,"اكتمال التوثيق"]].map(([value,label])=><div key={label} className="rounded-lg border p-2 text-center"><b>{value}</b><p className="text-[11px] text-muted">{label}</p></div>)}</div></CardContent></Card>
 <div className="flex gap-2 overflow-x-auto pb-2">{visibleTabs.map(([key,label])=><Button key={key} size="sm" variant={tab===key?"default":"outline"} onClick={()=>setTab(key)}>{label}</Button>)}</div>
 {tab==="overview"?<Overview row={current} canEdit={canEdit} update={update} operational={operational} evidenceReady={evidenceReady}/>:null}
 {tab==="timeline"?<Records title="المحطات والجلسات والمواعيد" rows={arr(current.timeline)} canEdit={canEdit} columns={["name","type","date","responsible","status","followUp"]} labels={["الاسم","النوع","التاريخ/الوقت","المسؤول","الحالة","إجراء المتابعة"]} add={()=>update("timeline",[...arr(current.timeline),{id:id("timeline"),name:"سجل زمني جديد",type:"جلسة",date:"",responsible:"",status:"لم تبدأ",followUp:""}])} change={(i,p)=>update("timeline",patch(arr(current.timeline),i,p))}/>:null}
 {tab==="challenges"?<Records title="تحديات الفعالية" rows={arr(current.challenges)} canEdit={canEdit} columns={["title","category","owner","entity","beneficiaryGroup","status"]} labels={["التحدي","التصنيف","المالك","الإدارة/الجهة","المستفيدون","الحالة"]} add={()=>update("challenges",[...arr(current.challenges),{id:id("challenge"),title:"تحدٍ جديد",description:"",category:"",owner:"",entity:"",beneficiaryGroup:"",status:"مسودة"}])} change={(i,p)=>update("challenges",patch(arr(current.challenges),i,p))}/>:null}
 {tab==="people"&&!restricted?<><Records title="سجل المشاركين" rows={arr(current.participants)} canEdit={canEdit} columns={["name","category","organization","teamId","status","attendance"]} labels={["المشارك","الفئة","الجهة","الفريق","الحالة","الحضور"]} add={()=>update("participants",[...arr(current.participants),{id:id("participant"),name:"مشارك جديد",category:"",organization:"",teamId:"",status:"مسجل",attendance:""}])} change={(i,p)=>update("participants",patch(arr(current.participants),i,p))}/><Records title="الفرق" rows={arr(current.teams)} canEdit={canEdit} columns={["name","lead","challengeId","solutionId","status"]} labels={["الفريق","القائد","التحدي","الحل","الحالة"]} add={()=>update("teams",[...arr(current.teams),{id:id("team"),name:"فريق جديد",lead:"",challengeId:"",solutionId:"",status:"مسجل"}])} change={(i,p)=>update("teams",patch(arr(current.teams),i,p))}/></>:null}
 {tab==="solutions"?<Records title="الحلول والمشاركات" rows={arr(current.solutions)} canEdit={canEdit} columns={["name","challengeId","teamId","submittedAt","version","status","winnerStatus"]} labels={["الحل","التحدي","الفريق","التسليم","الإصدار","الحالة","الفوز"]} add={()=>update("solutions",[...arr(current.solutions),{id:id("solution"),name:"حل جديد",challengeId:"",teamId:"",submittedAt:"",version:"1",status:"مسودة",winnerStatus:"غير محدد"}])} change={(i,p)=>update("solutions",patch(arr(current.solutions),i,p))}/>:null}
 {tab==="judging"?<><Records title="لجنة التحكيم" rows={arr(current.judges)} canEdit={canEdit} columns={["name","organization","role"]} labels={["المحكم","الجهة","الدور"]} add={()=>update("judges",[...arr(current.judges),{id:id("judge"),name:"محكم جديد",organization:"",role:""}])} change={(i,p)=>update("judges",patch(arr(current.judges),i,p))}/><Records title="الجولات والنتائج" rows={arr(current.judging)} canEdit={canEdit} columns={["solutionId","round","criteria","score","comments","ranking"]} labels={["الحل","الجولة","المعايير","النتيجة","الملاحظات","الترتيب"]} add={()=>update("judging",[...arr(current.judging),{id:id("judging"),solutionId:"",round:"",criteria:"",score:"",comments:"",ranking:""}])} change={(i,p)=>update("judging",patch(arr(current.judging),i,p))}/><Records title="الفائزون" rows={arr(current.winners)} canEdit={canEdit} columns={["solutionId","category","ranking","decision"]} labels={["الحل","الفئة","الترتيب","القرار"]} add={()=>update("winners",[...arr(current.winners),{id:id("winner"),solutionId:"",category:"",ranking:"",decision:""}])} change={(i,p)=>update("winners",patch(arr(current.winners),i,p))}/></>:null}
 {tab==="prototypes"?<Records title="النماذج الأولية وإصداراتها" rows={arr(current.prototypes)} canEdit={canEdit} columns={["name","solutionId","version","stage","owner","testingSummary","feedback","result","state"]} labels={["النموذج","الحل المصدر","الإصدار","المرحلة","المالك","الاختبار","التغذية الراجعة","النتيجة","الحالة"]} add={()=>update("prototypes",[...arr(current.prototypes),{id:id("prototype"),name:"نموذج جديد",solutionId:"",version:"1",stage:"بناء",owner:"",testingSummary:"",feedback:"",result:"",state:"مسودة",versions:[]}])} change={(i,p)=>update("prototypes",patch(arr(current.prototypes),i,p))}/>:null}
 {tab==="projects"?<Records title="المشاريع الناتجة ومسارها" rows={arr(current.projects)} canEdit={canEdit} columns={["solutionId","name","owner","department","implementationState","startDate","status","impactLink"]} labels={["الحل المصدر","المشروع/المبادرة","المالك","الإدارة","حالة التنفيذ","البداية","الحالة","قياس الأثر"]} add={()=>update("projects",[...arr(current.projects),{id:id("project"),solutionId:"",name:"مشروع ناتج",owner:"",department:"",implementationState:"",startDate:"",status:"مسودة",impactLink:""}])} change={(i,p)=>update("projects",patch(arr(current.projects),i,p))}/>:null}
 {tab==="impact"?<Records title="نتائج وأثر الفعالية" rows={arr(current.impacts)} canEdit={canEdit} columns={["projectId","beneficiaries","adoptionState","outcome","kpi","measurement","formalImpactLink"]} labels={["المشروع","المستفيدون","التبني","النتيجة","المؤشر","القياس","رابط 5.24.2"]} add={()=>update("impacts",[...arr(current.impacts),{id:id("impact"),projectId:"",beneficiaries:"",adoptionState:"",outcome:"",kpi:"",measurement:"",formalImpactLink:""}])} change={(i,p)=>update("impacts",patch(arr(current.impacts),i,p))}/>:null}
 {tab==="files"?<><Records title="ملفات العمل والتصاميم والشهادات" rows={arr(current.files)} canEdit={canEdit} columns={["title","category","fileName","version","reviewState","markedAsEvidence"]} labels={["الملف","الفئة","اسم الملف","الإصدار","المراجعة","مرشح للإثبات"]} add={()=>update("files",[...arr(current.files),{id:id("file"),title:"ملف جديد",category:"مادة فعالية",fileName:"",version:1,reviewState:"مسودة",markedAsEvidence:"لا"}])} change={(i,p)=>update("files",patch(arr(current.files),i,p))}/><Samples rows={arr(current.documentationSamples)} files={arr(current.files)}/></>:null}
 {tab==="evidence"?<EvidenceSummary evidence={evidence} samples={arr(current.documentationSamples)} files={arr(current.files)}/>:null}
 {tab==="tasks"&&!restricted?<TasksAndDelegations event={current} canEdit={canEdit} users={[]} update={update} contributions={contributions}/>:null}
 {tab==="closure"?<Closure event={current} gaps={gaps} operational={operational} evidenceReady={evidenceReady} canEdit={canEdit} onClose={()=>{if(gaps.operational.length)setNotice("لا يمكن الإغلاق التشغيلي قبل معالجة النواقص الموضحة.");else update("status","مغلقة تشغيليًا");}}/>:null}
 {notice?<p className="rounded-lg bg-primary-50 p-3 text-sm">{notice}</p>:null}</div>;
}

function Registry({events,query,setQuery,canEdit,onOpen,onCreate,onLink}:{events:Row[];query:string;setQuery:(v:string)=>void;canEdit:boolean;onOpen:(i:number)=>void;onCreate:()=>void;onLink:()=>void}){const filtered=events.filter(e=>`${e.name} ${e.type} ${e.department}`.includes(query));return <div className="space-y-5"><Card className="border-primary/20"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>فعاليات الابتكار المفتوح</CardTitle><p className="mt-1 text-xs text-muted">سجل متعدد الفعاليات لإدارة التوثيق التشغيلي وتجهيز أدلة المتطلب.</p></div>{canEdit?<div className="flex flex-wrap gap-2"><Button onClick={onCreate}><Plus className="h-4 w-4"/>إضافة فعالية ابتكار مفتوح</Button><Button variant="outline" onClick={onLink}><Link2 className="h-4 w-4"/>ربط فعالية من الخطة السنوية</Button></div>:null}</div></CardHeader><CardContent><label className="relative block"><Search className="absolute right-3 top-3 h-4 w-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو النوع أو الإدارة" className="h-10 w-full rounded-lg border bg-transparent pr-10 pl-3 text-sm"/></label></CardContent></Card><div className="grid gap-4 xl:grid-cols-2">{filtered.map((event,index)=>{const m=deriveMetrics(event);const gaps=deriveGaps(event,[],[]);return <Card key={event.id}><CardContent className="p-5"><div className="flex justify-between gap-3"><div><Badge variant="primary">{event.type}</Badge><h3 className="mt-2 font-bold">{event.name}</h3><p className="mt-1 text-xs text-muted">{event.startDate} — {event.endDate} · {event.department}</p></div><Badge variant="warning">{event.status}</Badge></div><div className="mt-4 grid grid-cols-4 gap-2 text-center text-xs"><span><b>{m.participants}</b><small className="block text-muted">مشارك</small></span><span><b>{m.teams}</b><small className="block text-muted">فريق</small></span><span><b>{m.challenges}</b><small className="block text-muted">تحدٍ</small></span><span><b>{m.solutions}</b><small className="block text-muted">حل</small></span></div><div className="mt-4 flex items-center justify-between"><p className="text-xs text-warning">{gaps.operational.length} فجوات توثيقية</p><Button size="sm" onClick={()=>onOpen(events.indexOf(event))}>فتح مساحة الفعالية <ArrowLeft className="h-4 w-4"/></Button></div></CardContent></Card>})}</div></div>}
function Overview({row,canEdit,update,operational,evidenceReady}:{row:Row;canEdit:boolean;update:(k:string,v:unknown)=>void;operational:number;evidenceReady:number}){const fields=[["name","اسم الفعالية"],["type","نوع الفعالية"],["objective","الهدف"],["beneficiaryGroups","الفئات المستفيدة"],["approach","منهج الابتكار المفتوح"],["owner","المالك"],["department","الإدارة المسؤولة"],["responsible","المسؤول"],["startDate","تاريخ البداية"],["endDate","تاريخ النهاية"],["location","المكان"],["deliveryMode","نمط التنفيذ"],["status","الحالة"]];return <Card><CardHeader><CardTitle>بيانات الفعالية</CardTitle></CardHeader><CardContent><div className="mb-5 grid gap-3 sm:grid-cols-2"><div><p className="text-xs text-muted">اكتمال التوثيق التشغيلي</p><Progress className="mt-2" value={operational}/><b>{operational}%</b></div><div><p className="text-xs text-muted">جاهزية أدلة المتطلب</p><Progress className="mt-2" value={evidenceReady}/><b>{evidenceReady}%</b></div></div><div className="grid gap-3 md:grid-cols-2">{fields.map(([key,label])=><label key={key} className="text-xs font-semibold">{label}<input disabled={!canEdit} value={String(row[key]??"")} onChange={e=>update(key,e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-transparent px-3"/></label>)}<label className="text-xs font-semibold md:col-span-2">الوصف<textarea disabled={!canEdit} value={String(row.description??"")} onChange={e=>update("description",e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border bg-transparent p-3"/></label></div>{row.annualPlanActivityName?<p className="mt-4 rounded-lg bg-primary-50 p-3 text-xs"><Link2 className="ml-1 inline h-4 w-4"/>مرتبطة بنشاط الخطة السنوية: {row.annualPlanActivityName}</p>:null}</CardContent></Card>}
function Records({title,rows,canEdit,columns,labels,add,change}:{title:string;rows:Row[];canEdit:boolean;columns:string[];labels:string[];add:()=>void;change:(i:number,p:Row)=>void}){return <Card><CardHeader><div className="flex justify-between gap-3"><div><CardTitle>{title}</CardTitle><p className="mt-1 text-xs text-muted">{rows.length} سجلًا منظمًا ومترابطًا داخل الفعالية.</p></div>{canEdit?<Button size="sm" onClick={add}><Plus className="h-4 w-4"/>إضافة سجل</Button>:null}</div></CardHeader><CardContent className="space-y-3">{rows.slice(0,24).map((row,index)=><div key={row.id??index} className="grid gap-2 rounded-xl border p-3 md:grid-cols-3">{columns.map((key,i)=><label key={key} className="text-[11px] font-semibold">{labels[i]}<input disabled={!canEdit} value={String(row[key]??"")} onChange={e=>change(index,{[key]:e.target.value})} className="mt-1 h-9 w-full rounded-lg border bg-transparent px-2 text-xs"/></label>)}</div>)}{rows.length>24?<p className="text-center text-xs text-muted">يظهر أول 24 سجلًا من {rows.length} في المعاينة المختصرة.</p>:null}{!rows.length?<p className="py-8 text-center text-sm text-muted">لا توجد سجلات بعد.</p>:null}</CardContent></Card>}
function Samples({rows,files}:{rows:Row[];files:Row[]}){const complete=rows.filter(r=>r.status==="مكتملة"&&files.some(f=>f.id===r.fileId)).length;return <Card><CardHeader><CardTitle>عينات التوثيق</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{complete} / {rows.length}</p><p className="text-xs text-muted">تُحتسب العينة فقط عند ارتباطها بسجل وملف فعليين.</p>{rows.map(row=><p key={row.id} className="mt-3 flex items-center gap-2 rounded-lg border p-3 text-xs">{row.status==="مكتملة"?<CheckCircle2 className="h-4 w-4 text-success"/>:<AlertTriangle className="h-4 w-4 text-warning"/>}{row.type}<Badge className="mr-auto" variant={row.status==="مكتملة"?"success":"warning"}>{row.status}</Badge></p>)}</CardContent></Card>}
function EvidenceSummary({evidence,samples,files}:{evidence:Row[];samples:Row[];files:Row[]}){return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>الدليل الرسمي للمتطلب</CardTitle></CardHeader><CardContent><p className="text-sm">الملفات التشغيلية لا تصبح دليلًا رسميًا تلقائيًا.</p><p className="mt-3 text-xs text-muted">الأدلة المرتبطة: {evidence.length} · المعتمدة: {evidence.filter(e=>e.reviewStatus==="APPROVED").length}</p><a href="#requirement-evidence" className="mt-4 inline-flex text-sm font-semibold text-primary">فتح رفع ومراجعة الإثبات</a></CardContent></Card><Samples rows={samples} files={files}/></div>}
function TasksAndDelegations({event,canEdit,update,contributions}:{event:Row;canEdit:boolean;users:Row[];update:(k:string,v:unknown)=>void;contributions:ContributionView[]}){const tasks=arr(event.tasks);return <div className="space-y-4"><Records title="مهام الفعالية" rows={tasks} canEdit={canEdit} columns={["title","assignee","priority","dueDate","status","nextAction"]} labels={["المهمة","المسؤول","الأولوية","الموعد","الحالة","الإجراء التالي"]} add={()=>update("tasks",[...tasks,{id:id("event-task"),title:"مهمة جديدة",description:"",assignedUserId:"",assignee:"",priority:"MEDIUM",assignedAt:new Date().toISOString().slice(0,10),dueDate:"",status:"NOT_STARTED",section:"overview",nextAction:"فتح مساحة الفعالية"}])} change={(i,p)=>update("tasks",patch(tasks,i,p))}/><Card><CardHeader><CardTitle>فريق العمل / التوكيلات</CardTitle></CardHeader><CardContent><p className="mb-3 text-xs text-muted">التوكيل مسؤولية لتعبئة وتسليم نطاق محدد، وليس مجرد مهمة.</p><div className="grid gap-3 md:grid-cols-2">{contributions.map(row=><div key={row.id} className="rounded-xl border p-3 text-xs"><p className="font-bold">{row.contributorName}</p><p>{row.departmentName??"—"}</p><p className="mt-2">القسم: {row.sectionKey} · الحالة: {row.status}</p><p>الموعد: {row.dueDate?new Date(row.dueDate).toLocaleDateString("ar-SA"):"—"}</p></div>)}</div><a href="#section-collaboration" className="mt-4 inline-flex text-sm font-semibold text-primary">إدارة التوكيلات والمراجعات</a></CardContent></Card></div>}
function Closure({event,gaps,operational,evidenceReady,canEdit,onClose}:{event:Row;gaps:{operational:string[];evidence:string[]};operational:number;evidenceReady:number;canEdit:boolean;onClose:()=>void}){return <div className="space-y-4"><Card><CardHeader><CardTitle>إغلاق الفعالية تشغيليًا</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-primary-50 p-4"><p className="text-xs">اكتمال التوثيق التشغيلي</p><b className="text-2xl">{operational}%</b></div><div className="rounded-xl bg-warning-bg p-4"><p className="text-xs">جاهزية أدلة المتطلب</p><b className="text-2xl">{evidenceReady}%</b></div></div><div className="mt-4 space-y-2">{gaps.operational.map(g=><p key={g} className="flex gap-2 text-xs"><AlertTriangle className="h-4 w-4 text-warning"/>{g}</p>)}</div>{canEdit?<Button className="mt-4" onClick={onClose}>إغلاق الفعالية تشغيليًا</Button>:null}<p className="mt-3 text-xs text-muted">الإغلاق التشغيلي لا يعني اكتمال أو اعتماد أدلة DGA.</p></CardContent></Card><Card><CardHeader><CardTitle>سجل النشاط</CardTitle></CardHeader><CardContent>{arr(event.log).map((row,index)=><p key={`${row.date}-${index}`} className="border-b py-2 text-xs"><b>{new Date(row.date).toLocaleDateString("ar-SA")}</b> · {row.action}</p>)}</CardContent></Card></div>}
function deriveMetrics(event:Row){return{participants:arr(event.participants).length,teams:arr(event.teams).length,challenges:arr(event.challenges).length,solutions:arr(event.solutions).length,prototypes:arr(event.prototypes).length,winners:arr(event.winners).length,projects:arr(event.projects).length};}
function deriveGaps(event:Row,contributions:ContributionView[],evidence:Row[]){const operational:string[]=[];if(!event.name||!event.objective)operational.push("بيانات الفعالية الأساسية غير مكتملة");if(!arr(event.timeline).length)operational.push("لا توجد محطات أو جلسات موثقة");if(!arr(event.challenges).length)operational.push("لا توجد تحديات موثقة");if(!arr(event.participants).length)operational.push("سجل المشاركين غير مكتمل");if(!arr(event.solutions).length)operational.push("لا توجد حلول أو مشاركات موثقة");if(!arr(event.judging).length)operational.push("نتائج التحكيم غير موثقة");if(!arr(event.winners).length)operational.push("الفائزون غير موثقين");if(!arr(event.prototypes).length)operational.push("لا توجد نماذج أولية موثقة");if(!arr(event.projects).length)operational.push("المشاريع الناتجة غير موثقة");if(!arr(event.impacts).length)operational.push("الأثر والنتائج غير موثقين");if(arr(event.tasks).some(t=>!["COMPLETED","CANCELLED"].includes(t.status)))operational.push("توجد مهام مفتوحة");if(contributions.some(c=>!["COMPLETED","CANCELLED"].includes(c.status)))operational.push("توجد توكيلات أو مساهمات مفتوحة");return{operational,evidence:evidence.length?[]:["دليل المتطلب الرسمي غير مرفوع أو غير معتمد"]};}
function patch(rows:Row[],index:number,value:Row){return rows.map((row,i)=>i===index?{...row,...value}:row)}
