"use client";
import { useEffect, useMemo, useState } from "react";
import { useFormState } from "react-dom";
import Link from "next/link";
import { AlertCircle, CheckCircle2, Download, FileText, Plus, Save, Upload, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { saveWorkspaceAction, uploadWorkspaceEvidenceAction, type WorkspaceActionState } from "../workspace-actions";
import { deriveOperationalStatus, missingEvidence, missingWorkspaceFields, type WorkspaceData, type OperationalStatus } from "../workspace-status";
import type { RequirementWorkspaceConfig, WorkspaceSection } from "../workspace-config";
import type { DgaRequirementDefinition, DgaUnitDefinition } from "../types";

type EvidenceRow={id:string;title:string;classification:string|null;fileName:string|null;version:number;reviewStatus:string;uploadedAt:string;uploader:string};
const labels:Record<OperationalStatus,string>={NOT_STARTED:"لم تبدأ",IN_PROGRESS:"قيد التنفيذ",AWAITING_EVIDENCE:"بانتظار الإثبات",COMPLETED:"مكتملة"};
const emptyRow=(section:WorkspaceSection)=>Object.fromEntries(section.fields.map((field)=>[field.key,""]));
const initialData=(config:RequirementWorkspaceConfig,data:WorkspaceData)=>Object.fromEntries(config.sections.map((section)=>[section.key,data[section.key]??(section.repeatable?[emptyRow(section)]:emptyRow(section))])) as WorkspaceData;

export function OperationalWorkspace({unit,requirement,config,initial,initialEvidence,initialStatus,canEdit,preview=false,personaKey="admin"}:{unit:DgaUnitDefinition;requirement:DgaRequirementDefinition;config:RequirementWorkspaceConfig;initial:WorkspaceData;initialEvidence:EvidenceRow[];initialStatus:OperationalStatus;canEdit:boolean;preview?:boolean;personaKey?:string}){
  const storageKey=`dga-workspace:${personaKey}:${requirement.id}`;
  const [data,setData]=useState(()=>initialData(config,initial)); const [evidence,setEvidence]=useState(initialEvidence); const [notice,setNotice]=useState("");
  const [saveState,saveAction]=useFormState(saveWorkspaceAction,{} as WorkspaceActionState); const [uploadState,uploadAction]=useFormState(uploadWorkspaceEvidenceAction,{} as WorkspaceActionState);
  useEffect(()=>{if(!preview)return; const value=localStorage.getItem(storageKey); if(value){try{const parsed=JSON.parse(value);setData(initialData(config,parsed.data??{}));setEvidence(parsed.evidence??[]);}catch{}}},[preview,storageKey,config]);
  const counts=useMemo(()=>evidence.reduce<Record<string,number>>((acc,item)=>{if(item.classification)acc[item.classification]=(acc[item.classification]??0)+1;return acc;},{}),[evidence]);
  const missingFields=missingWorkspaceFields(config,data); const missingFiles=missingEvidence(config,counts); const status=deriveOperationalStatus(config,data,counts); const total=config.sections.reduce((sum,s)=>sum+(s.repeatable?(s.minItems??1)*s.fields.filter(f=>f.required!==false).length:s.fields.filter(f=>f.required!==false).length),0)+config.evidence.reduce((s,e)=>s+e.minCount,0); const progress=Math.round(((total-missingFields.length-missingFiles.length)/Math.max(total,1))*100);
  function update(section:WorkspaceSection,row:number|undefined,key:string,value:string){setData(current=>{const copy=structuredClone(current); if(section.repeatable){const rows=copy[section.key] as Record<string,unknown>[];rows[row??0]={...rows[row??0],[key]:value};}else copy[section.key]={...(copy[section.key] as Record<string,unknown>),[key]:value};return copy;});}
  function add(section:WorkspaceSection){setData(current=>({...current,[section.key]:[...(current[section.key] as Record<string,unknown>[]),emptyRow(section)]}));}
  function remove(section:WorkspaceSection,index:number){setData(current=>({...current,[section.key]:(current[section.key] as Record<string,unknown>[]).filter((_,i)=>i!==index)}));}
  function savePreview(){localStorage.setItem(storageKey,JSON.stringify({data,evidence}));setNotice("حُفظت المعاينة في هذا المتصفح فقط — لم تُحفظ في النظام التشغيلي.");}
  function previewUpload(ruleKey:string,file:File|null){if(!file)return; const next:EvidenceRow={id:crypto.randomUUID(),title:config.evidence.find(r=>r.key===ruleKey)!.title,classification:ruleKey,fileName:file.name,version:(evidence.filter(e=>e.classification===ruleKey).at(0)?.version??0)+1,reviewStatus:"DRAFT",uploadedAt:new Date().toISOString(),uploader:"مستخدم وضع المعاينة"};const rows=[next,...evidence];setEvidence(rows);localStorage.setItem(storageKey,JSON.stringify({data,evidence:rows}));setNotice("سُجل الملف للمعاينة محليًا فقط ولم يُرفع إلى خادم تشغيلي.");}
  return <div className="space-y-5">
    <Link href={unit.href} className="text-sm font-semibold text-primary">العودة إلى متطلبات {unit.code}</Link>
    <Card><CardContent className="p-6"><div className="flex flex-wrap justify-between gap-4"><div className="max-w-4xl"><Badge variant="primary">البند {unit.code} · المتطلب {requirement.number}</Badge><h1 className="mt-3 text-xl font-bold">{requirement.title}</h1><p className="mt-3 text-sm leading-7 text-muted">{requirement.applicationRequirement}</p></div><Badge className="self-start" variant={status==="COMPLETED"?"success":status==="NOT_STARTED"?"neutral":"warning"}>{labels[status]}</Badge></div><div className="mt-5 grid gap-3 border-t pt-4 text-xs sm:grid-cols-3"><span><b>المسؤول:</b> {requirement.owner}</span><span><b>آخر تحديث:</b> {requirement.lastUpdate}</span><span><b>رقم المتطلب:</b> {config.code}</span></div></CardContent></Card>
    <Card><CardHeader><CardTitle>ما المطلوب؟</CardTitle></CardHeader><CardContent><p className="text-sm leading-7">{config.explanation}</p><div className="mt-4"><div className="flex justify-between text-xs"><span>تقدم الاستكمال</span><b>{Math.max(0,progress)}%</b></div><Progress className="mt-2" value={Math.max(0,progress)}/></div></CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-5">
      {config.sections.map(section=><Card key={section.key}><CardHeader><div className="flex items-center justify-between"><CardTitle>{section.title}</CardTitle>{section.repeatable&&canEdit&&<Button type="button" size="sm" variant="outline" onClick={()=>add(section)}><Plus className="h-4 w-4"/>إضافة سجل</Button>}</div>{section.minItems&&<p className="text-xs text-muted">الحد الأدنى المطلوب: {section.minItems}</p>}</CardHeader><CardContent className="space-y-4">{(section.repeatable?(data[section.key] as Record<string,unknown>[]):[data[section.key] as Record<string,unknown>]).map((row,index)=><div key={index} className="relative grid gap-4 rounded-xl border p-4 sm:grid-cols-2">{section.repeatable&&canEdit&&(data[section.key] as unknown[]).length>1&&<button type="button" onClick={()=>remove(section,index)} className="absolute left-3 top-3 text-muted" aria-label="حذف السجل"><X className="h-4 w-4"/></button>}{section.fields.map(field=><label key={field.key} className={field.type==="textarea"?"sm:col-span-2":""}><span className="mb-1.5 block text-xs font-semibold">{field.label}{field.required!==false&&<span className="text-danger"> *</span>}</span>{field.type==="textarea"?<textarea disabled={!canEdit} value={String(row?.[field.key]??"")} onChange={event=>update(section,section.repeatable?index:undefined,field.key,event.target.value)} className="min-h-24 w-full rounded-lg border bg-transparent p-3 text-sm"/>:<input disabled={!canEdit} type={field.type??"text"} value={String(row?.[field.key]??"")} onChange={event=>update(section,section.repeatable?index:undefined,field.key,event.target.value)} className="h-10 w-full rounded-lg border bg-transparent px-3 text-sm"/>}</label>)}</div>)}</CardContent></Card>)}
      {canEdit&&(preview?<Button onClick={savePreview}><Save className="h-4 w-4"/>حفظ كمسودة</Button>:<form action={saveAction}><input type="hidden" name="requirementId" value={requirement.id}/><input type="hidden" name="path" value={`${unit.href}/requirements/${requirement.id}`}/><input type="hidden" name="workspaceData" value={JSON.stringify(data)}/><Button><Save className="h-4 w-4"/>حفظ التحديث</Button></form>)}
      {(notice||saveState.error||saveState.success)&&<p className="rounded-lg bg-primary-50 p-3 text-sm">{notice||saveState.error||saveState.success}</p>}
    </div><div className="space-y-5"><Card><CardHeader><CardTitle>مستندات الإثبات المطلوبة</CardTitle></CardHeader><CardContent className="space-y-4">{config.evidence.map(rule=><div key={rule.key} className="rounded-xl border p-4"><div className="flex gap-3"><FileText className="h-5 w-5 text-primary"/><div><p className="text-sm font-semibold">{rule.title}</p><p className="mt-1 text-xs text-muted">المرفوع {counts[rule.key]??0} من {rule.minCount}</p></div></div>{evidence.filter(item=>item.classification===rule.key).map(item=><div key={item.id} className="mt-3 rounded-lg bg-slate-50 p-3 text-xs"><b>{item.fileName}</b><p className="mt-1 text-muted">نسخة {item.version} · {item.uploader} · {new Date(item.uploadedAt).toLocaleDateString("ar-SA")}</p>{!preview&&<Link className="mt-2 inline-flex items-center gap-1 text-primary" href={`/api/requirement-evidence/${item.id}/download`}><Download className="h-3.5 w-3.5"/>عرض/تنزيل</Link>}</div>)}{canEdit&&(preview?<label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-lg border p-2 text-xs font-semibold"><Upload className="h-4 w-4"/>رفع/استبدال الإثبات<input className="sr-only" type="file" accept=".pdf,.docx,.xlsx" onChange={event=>previewUpload(rule.key,event.target.files?.[0]??null)}/></label>:<form action={uploadAction} className="mt-3"><input type="hidden" name="requirementId" value={requirement.id}/><input type="hidden" name="evidenceType" value={rule.key}/><input type="hidden" name="path" value={`${unit.href}/requirements/${requirement.id}`}/><input required name="file" type="file" accept=".pdf,.docx,.xlsx" className="block w-full text-xs"/><Button className="mt-2 w-full" size="sm" variant="outline"><Upload className="h-4 w-4"/>رفع/استبدال الإثبات</Button></form>)}</div>)}{uploadState.error&&<p className="text-xs text-danger">{uploadState.error}</p>}{uploadState.success&&<p className="text-xs text-success">{uploadState.success}</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>النواقص</CardTitle></CardHeader><CardContent className="space-y-2">{[...missingFields,...missingFiles].length?[...missingFields,...missingFiles].map(item=><p key={item} className="flex gap-2 text-xs leading-5"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-warning"/>{item}</p>):<p className="flex gap-2 text-sm text-success"><CheckCircle2 className="h-5 w-5"/>اكتملت البيانات والإثباتات المطلوبة.</p>}</CardContent></Card>
      <p className="rounded-lg bg-warning-bg p-3 text-xs leading-6 text-warning">اكتمال المتطلب داخل المنصة لا يمثل اعتماداً رسمياً من هيئة الحكومة الرقمية.</p>
      {requirement.number!==String(unit.requirements.length).padStart(2,"0")&&<Button asChild variant="outline" className="w-full"><Link href={`${unit.href}/requirements/${unit.requirements[Number(requirement.number)]?.id}`}>الانتقال للمتطلب التالي</Link></Button>}
    </div></div>
  </div>;
}
