import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleDashed, FileSearch, Paperclip, Upload } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { buildPreviewHref, type PreviewPersonaKey } from "@/lib/ux-preview";
import type { DgaRequirementDefinition, DgaUnitDefinition } from "../types";
import { RequirementStatusBadge } from "./status-badge";
import { OperationalWorkspace } from "./operational-workspace";
import { getWorkspaceConfig } from "../workspace-config";
import { PREVIEW_WORKSPACE_DATA } from "../preview-workspace-fixtures";
import type { GovernanceView } from "@/modules/governance-workflow/components/governance-panel";

function previewGovernance(persona:PreviewPersonaKey|undefined,requirementId:string):GovernanceView|undefined{if(!persona)return undefined;const users=[{id:"admin",name:"مدير النظام",email:"admin@innovation.local"},{id:"internal",name:"محرر الابتكار الداخلي",email:"editor@innovation.local"},{id:"partner",name:"منسق الشراكة",email:"partner@innovation.local"}];return{assignmentId:`preview-${requirementId}`,workflowState:requirementId.endsWith("r3")?"RETURNED_FOR_AMENDMENT":"UNDER_REVIEW",priority:"HIGH",ownerUserId:"internal",responsibleUserId:"internal",dueDate:"2026-08-18T00:00:00.000Z",nextAction:requirementId.endsWith("r3")?"استكمال ملاحظات المراجع وإعادة الإرسال":"إتمام المراجعة وإرسال المتطلب للاعتماد",raci:[{responsibility:"RESPONSIBLE",userId:"internal",departmentId:null,organizationalRole:null},{responsibility:"ACCOUNTABLE",userId:"admin",departmentId:null,organizationalRole:null},{responsibility:"CONSULTED",userId:"partner",departmentId:null,organizationalRole:null}],events:[{id:"e2",previousState:"UNDER_REVIEW",newState:"RETURNED_FOR_AMENDMENT",comment:null,reason:"استكمال تاريخ الاتفاقية ومحضر المتابعة",actor:"مدير النظام",createdAt:"2026-08-10T09:00:00.000Z"},{id:"e1",previousState:"IN_PROGRESS",newState:"SUBMITTED_FOR_REVIEW",comment:"اكتملت المسودة الأولية",reason:null,actor:"محرر الابتكار الداخلي",createdAt:"2026-08-09T12:00:00.000Z"}],versions:[{id:"v1",version:1,workflowState:"SUBMITTED_FOR_REVIEW",author:"محرر الابتكار الداخلي",createdAt:"2026-08-09T12:00:00.000Z",reviewComment:"المسودة الأولى"}],comments:[{id:"c1",type:"REVIEW_NOTE",body:"يرجى استكمال المستندات قبل إعادة الإرسال.",author:"مدير النظام",createdAt:"2026-08-10T09:05:00.000Z"}],tasks:[{id:"t1",type:"REVIEW",title:"مراجعة بيانات المتطلب قبل الاعتماد",status:"IN_PROGRESS",priority:"HIGH",assignedTo:"مدير النظام",dueDate:"2026-08-18T00:00:00.000Z",nextAction:"استكمال المراجعة"}],auditEntries:[{id:"a1",action:"COMPLIANCE_ASSIGNMENT_UPDATED",actor:"محرر الابتكار الداخلي",summary:"تحديث بيانات مساحة العمل (معاينة)",createdAt:"2026-08-09T12:00:00.000Z"}],canViewAudit:persona==="admin",users,canConfigure:persona==="admin",canReview:persona==="admin"};}

const reviewLabels = { NOT_REVIEWED: "لم يتم الفحص", READY_FOR_REVIEW: "جاهز للفحص", HAS_NOTES: "توجد ملاحظات", HUMAN_REVIEWED: "تمت المراجعة البشرية" } as const;
function href(path: string, persona?: PreviewPersonaKey) { return persona ? buildPreviewHref(path, persona) : path; }

function RequirementWorkspace({ unit, requirement, persona, canEdit }: { unit: DgaUnitDefinition; requirement: DgaRequirementDefinition; persona?: PreviewPersonaKey; canEdit: boolean }) {
  return <div className="min-w-0 max-w-full space-y-5 overflow-hidden">
    <Link href={href(unit.href, persona)} className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowRight className="h-4 w-4" />العودة إلى متطلبات {unit.code}</Link>
    <Card><CardContent className="min-w-0 p-6"><div className="flex min-w-0 flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><Badge variant="primary">{unit.code}.{requirement.number}</Badge><h1 className="mt-3 break-words text-xl font-bold">{requirement.title}</h1><p className="mt-3 max-w-4xl break-words text-sm leading-7 text-muted">{requirement.applicationRequirement}</p></div><RequirementStatusBadge status={requirement.status} /></div><div className="mt-5 grid gap-3 border-t pt-4 text-xs sm:grid-cols-3"><span><b>المسؤول:</b> {requirement.owner}</span><span><b>آخر تحديث:</b> {requirement.lastUpdate}</span><span><b>الحالة:</b> {requirement.status === "COMPLETED" ? "مستوفى تشغيليًا" : "يحتاج متابعة"}</span></div></CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <div className="min-w-0 space-y-5"><Card><CardHeader><CardTitle>الحقول والمهام</CardTitle></CardHeader><CardContent className="min-w-0 space-y-3">{requirement.tasks.map((task,index)=><div key={task} className="flex min-w-0 items-start gap-3 rounded-lg border p-3"><CheckCircle2 className={`mt-0.5 h-4 w-4 ${requirement.status === "COMPLETED" || index === 0 ? "text-success" : "text-slate-300"}`} /><div className="min-w-0"><p className="break-words text-sm font-semibold">{task}</p><p className="mt-1 text-xs text-muted">{requirement.status === "NOT_STARTED" ? "لم يبدأ" : index === 0 ? "تم توثيقه" : "قيد الاستكمال"}</p></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>الملاحظات</CardTitle></CardHeader><CardContent><div className="min-h-24 rounded-lg border bg-slate-50 p-4 text-sm text-muted dark:bg-white/5">{requirement.notes ?? "لا توجد ملاحظات إضافية. ستظهر هنا ملاحظات المسؤول والمراجع المرتبطة بالمتطلب."}</div></CardContent></Card></div>
      <div className="space-y-5"><Card className="border-primary/20"><CardHeader><div className="flex items-center justify-between"><CardTitle>مستندات الإثبات</CardTitle><Badge variant="neutral">مرتبطة بالمتطلب</Badge></div></CardHeader><CardContent className="space-y-3">{requirement.evidence.map((evidence)=><div key={evidence.title} className="rounded-lg border p-4"><div className="flex items-start gap-3"><FileSearch className="mt-0.5 h-5 w-5 text-primary"/><div className="flex-1"><p className="text-sm font-semibold">{evidence.title}</p><Badge className="mt-2" variant={evidence.reviewStatus === "HUMAN_REVIEWED" ? "success" : evidence.reviewStatus === "HAS_NOTES" ? "warning" : "neutral"}>{reviewLabels[evidence.reviewStatus ?? "NOT_REVIEWED"]}</Badge></div></div></div>)}<Button className="w-full" disabled={!canEdit} title={canEdit ? "رفع إثبات لهذا المتطلب" : "لا يملك هذا الدور صلاحية الرفع"}><Upload className="h-4 w-4" />رفع إثبات لهذا المتطلب</Button>{!canEdit && <p className="text-center text-xs text-muted">العرض فقط وفق صلاحيات هذا الدور.</p>}<p className="rounded-lg bg-primary-50 p-3 text-xs leading-6 text-primary-700">المراجعة المستقبلية للوثيقة ستكون مساعدة فقط. لا تدّعي المنصة أن الذكاء الاصطناعي اعتمد أي وثيقة.</p></CardContent></Card><Card><CardHeader><CardTitle>سجل التحديثات</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-3 text-xs"><CircleDashed className="h-4 w-4 text-primary"/><div><b>{requirement.lastUpdate}</b><p className="mt-1 text-muted">تحديث حالة المتطلب وبيانات المسؤول.</p></div></div><div className="flex gap-3 text-xs"><Paperclip className="h-4 w-4 text-muted"/><div><b>سجل قابل للتدقيق</b><p className="mt-1 text-muted">ستظهر الإضافات والاستبدالات والمراجعات دون إخفاء النسخ السابقة.</p></div></div></CardContent></Card></div>
    </div>
  </div>;
}

export function DgaUnitPage({ unit, requirement, persona, canEdit = true }: { unit: DgaUnitDefinition; requirement?: DgaRequirementDefinition; persona?: PreviewPersonaKey; canEdit?: boolean }) {
  if (requirement) {
    const config = getWorkspaceConfig(requirement.id);
    if (config) return <OperationalWorkspace unit={unit} requirement={requirement} config={config} initial={PREVIEW_WORKSPACE_DATA[requirement.id]??{}} initialEvidence={[]} initialStatus="IN_PROGRESS" canEdit={canEdit} preview={Boolean(persona)} personaKey={persona} governance={previewGovernance(persona,requirement.id)} referenceData={requirement.id==="5-23-1-r2"?PREVIEW_WORKSPACE_DATA["5-23-1-r1"]:{}} />;
    return <RequirementWorkspace unit={unit} requirement={requirement} persona={persona} canEdit={canEdit} />;
  }
  const completed = unit.requirements.filter((item) => item.status === "COMPLETED").length;
  return <div className="space-y-6"><section className="rounded-2xl border bg-surface p-6 dark:bg-surface-dark"><div className="flex flex-wrap items-start justify-between gap-6"><div className="max-w-4xl"><Badge variant="primary">الوحدة {unit.code}</Badge><h1 className="mt-3 text-2xl font-bold">{unit.name}</h1><p className="mt-3 text-sm leading-7 text-muted"><b className="text-slate-800 dark:text-white">الهدف:</b> {unit.goal}</p></div><div className="min-w-44 rounded-xl bg-primary-50 p-4 text-center"><p className="text-xs text-primary-700">نسبة الجاهزية</p><p className="mt-1 text-3xl font-bold text-primary">{unit.readiness}%</p><p className="mt-1 text-xs text-muted">{completed} من {unit.requirements.length || "—"} مكتملة</p></div></div><Progress className="mt-5" value={unit.readiness}/></section>
    {unit.requirements.length ? <section><div className="mb-3"><h2 className="text-lg font-bold">متطلبات التطبيق</h2><p className="text-xs text-muted">افتح المتطلب لمعرفة المطلوب والمهام والإثبات والإجراء التالي.</p></div><div className="space-y-3">{unit.requirements.map((item)=><Card key={item.id} className="transition hover:border-primary/35"><CardContent className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-primary-50 text-sm font-bold text-primary">{item.number}</span><div className="min-w-0"><h3 className="font-bold">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-6 text-muted">{item.applicationRequirement}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted"><span>المسؤول: <b>{item.owner}</b></span><span>آخر تحديث: <b>{item.lastUpdate}</b></span><span>الأدلة: <b>{item.evidence.length}</b></span></div></div></div><div className="flex flex-wrap items-center gap-3 lg:justify-end"><RequirementStatusBadge status={item.status}/><Badge variant={item.evidence.some((e)=>e.reviewStatus === "NOT_REVIEWED") ? "warning" : "neutral"}>{item.evidence.some((e)=>e.reviewStatus === "NOT_REVIEWED") ? "إثبات ناقص" : "الإثبات قيد المتابعة"}</Badge><Button asChild size="sm" variant="outline"><Link href={href(`${unit.href}/requirements/${item.id}`,persona)}>فتح مساحة المتطلب <ArrowLeft className="h-4 w-4"/></Link></Button></div></div></CardContent></Card>)}</div></section> : <section><Card><CardHeader><CardTitle>بيانات الوحدة</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{unit.productFields?.map((field)=><div key={field} className="rounded-lg border p-4"><p className="text-sm font-semibold">{field}</p><p className="mt-1 text-xs text-muted">حقل وارد في مرجع تعريف المنتج</p></div>)}</div>{unit.boundaryNote && <p className="mt-5 rounded-lg bg-warning-bg p-4 text-xs leading-6 text-warning">{unit.boundaryNote}</p>}</CardContent></Card></section>}
  </div>;
}
