import Link from "next/link";
import { ArrowRight, BarChart3, FileText, Plus } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ImpactForm } from "@/modules/impact/components/impact-form";
import { IMPACT_TYPE_LABELS } from "@/modules/impact/schema";
import { getImpactWorkspace, checkMeasurementEligibility } from "@/modules/impact/service";
import { can, getAccessContext, requirePermission } from "@/server/authz";

const value = (item: { toString(): string } | null | undefined, unit?: string | null) => item == null ? "—" : `${item.toString()} ${unit ?? ""}`;

export default async function ImpactWorkspacePage({ params }: { params: { solutionId: string } }) {
  await requirePermission("impact.view");
  const actor = (await getAccessContext())!;
  const solution = await getImpactWorkspace(actor, params.solutionId);
  const eligibility = solution.impactIndicators.length ? null : checkMeasurementEligibility(solution);
  const allMeasurements = solution.impactIndicators.flatMap((indicator) => indicator.measurements.map((measurement) => ({ indicator, measurement }))).sort((a, b) => (b.measurement.measuredAt?.getTime() ?? 0) - (a.measurement.measuredAt?.getTime() ?? 0));
  const latest = allMeasurements[0];
  const verified = allMeasurements.filter((item) => item.measurement.verificationStatus === "VERIFIED").length;
  const canUpdate = can(actor, "impact.update");
  const canUploadEvidence = can(actor, "evidence.upload");

  return <div className="flex flex-col gap-5">
    <Link href="/impact" className="flex items-center gap-1 text-xs text-muted"><ArrowRight className="h-4 w-4"/>العودة إلى مركز قياس الأثر</Link>
    <PageHeader title={`ملف أثر: ${solution.nameAr}`} description={`${solution.owningDepartment?.organization.nameAr ?? ""}${solution.owningDepartment ? ` — ${solution.owningDepartment.nameAr}` : ""}`} action={<div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href={`/solutions/${solution.id}`}><FileText className="h-4 w-4"/>تفاصيل الحل</Link></Button>{canUploadEvidence ? <Button asChild variant="outline"><Link href={`/solutions/${solution.id}/evidence/new`}>رفع دليل الحل</Link></Button> : null}</div>} />
    <section id="overview" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card><CardContent className="p-4"><p className="text-xs text-muted">مؤشرات الأثر</p><b className="mt-1 block text-2xl">{solution.impactIndicators.length}</b></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted">القياسات المسجلة</p><b className="mt-1 block text-2xl">{allMeasurements.length}</b></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted">قياسات متحقق منها</p><b className="mt-1 block text-2xl">{verified}</b></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted">آخر قياس</p><b className="mt-1 block text-sm">{latest?.measurement.periodEnd?.toLocaleDateString("ar-SA") ?? "لم يسجل بعد"}</b></CardContent></Card></section>
    <nav className="sticky top-3 z-20 flex gap-2 overflow-x-auto rounded-2xl border bg-surface/95 p-2 shadow-sm backdrop-blur" aria-label="أقسام ملف الأثر">{[["نظرة عامة","#overview"],["مؤشرات الأثر","#indicators"],["القياسات","#measurements"],["الأدلة","#evidence"],["التقرير","#report"]].map(([label, href]) => <a key={label} href={href} className="whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold hover:bg-primary-50 hover:text-primary">{label}</a>)}</nav>
    {eligibility && !eligibility.eligible ? <Card className="border-warning/40 bg-warning-bg/30"><CardContent className="p-4 text-xs leading-6 text-warning"><b className="block text-sm">لا يمكن بدء أول مؤشر أثر لهذا الحل بعد وفق شروط الأهلية الموجودة:</b><ul className="mt-2 list-disc space-y-1 pr-4">{eligibility.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></CardContent></Card> : null}
    <section id="indicators" className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">مؤشرات الأثر</h2><p className="mt-1 text-xs text-muted">تُعرض المقارنة كما سُجلت: خط الأساس ثم آخر قيمة فعلية ثم المستهدف. لا يحدد النظام اتجاه المؤشر، لذلك لا يحسب تحقق الهدف تلقائيًا.</p></div>{canUpdate ? <a href="#add-measurement" className="inline-flex items-center gap-1 text-sm font-semibold text-primary"><Plus className="h-4 w-4"/>إضافة مؤشر أو قياس</a> : null}</div><div className="grid gap-3 lg:grid-cols-2">{solution.impactIndicators.map((indicator) => { const current = indicator.measurements[0]; return <Card key={indicator.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{indicator.nameAr}</CardTitle><p className="mt-1 text-xs text-muted">{indicator.measurementMethod ?? "منهجية القياس غير محددة"}</p></div><Badge variant="neutral">{IMPACT_TYPE_LABELS[indicator.type]}</Badge></div></CardHeader><CardContent><div className="grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg border p-2"><p className="text-muted">Baseline</p><b>{value(indicator.baselineValue, indicator.unit)}</b></div><div className="rounded-lg border p-2"><p className="text-muted">Current</p><b>{value(current?.actualValue, indicator.unit)}</b></div><div className="rounded-lg border p-2"><p className="text-muted">Target</p><b>{value(indicator.targetValue, indicator.unit)}</b></div></div><div className="mt-3 flex justify-between text-xs text-muted"><span>{current?.periodStart?.toLocaleDateString("ar-SA") ?? "—"} — {current?.periodEnd?.toLocaleDateString("ar-SA") ?? "—"}</span><Badge variant={current?.verificationStatus === "VERIFIED" ? "success" : "warning"}>{current?.verificationStatus === "VERIFIED" ? "تم التحقق" : current ? "بانتظار التحقق" : "لم تسجل قيمة"}</Badge></div></CardContent></Card> })}{!solution.impactIndicators.length ? <Card className="lg:col-span-2"><CardContent className="p-8 text-center text-sm text-muted"><BarChart3 className="mx-auto mb-2 h-8 w-8"/>لم تُسجل مؤشرات لهذا الحل بعد.</CardContent></Card> : null}</div></section>
    <section id="measurements" className="space-y-3"><div><h2 className="text-lg font-bold">القياسات</h2><p className="mt-1 text-xs text-muted">السجل الزمني يعتمد فقط على القياسات المحفوظة للمؤشرات.</p></div><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead><tr className="border-b text-muted"><th className="p-3 text-start">المؤشر</th><th className="p-3 text-start">القيمة</th><th className="p-3 text-start">الفترة</th><th className="p-3 text-start">مصدر البيانات</th><th className="p-3 text-start">التحقق</th></tr></thead><tbody>{allMeasurements.map(({indicator, measurement}) => <tr key={measurement.id} className="border-b last:border-0"><td className="p-3 font-semibold">{indicator.nameAr}</td><td className="p-3">{value(measurement.actualValue, indicator.unit)}</td><td className="p-3">{measurement.periodStart?.toLocaleDateString("ar-SA") ?? "—"} — {measurement.periodEnd?.toLocaleDateString("ar-SA") ?? "—"}</td><td className="p-3">{measurement.dataSource ?? "غير محدد"}</td><td className="p-3"><Badge variant={measurement.verificationStatus === "VERIFIED" ? "success" : "warning"}>{measurement.verificationStatus === "VERIFIED" ? "تم التحقق" : "بانتظار التحقق"}</Badge></td></tr>)}{!allMeasurements.length ? <tr><td colSpan={5} className="p-8 text-center text-muted">لا توجد قياسات مسجلة بعد.</td></tr> : null}</tbody></table></div></CardContent></Card></section>
    <section id="evidence" className="rounded-2xl border bg-surface p-4"><h2 className="text-lg font-bold">الأدلة</h2><p className="mt-1 text-sm text-muted">لا توجد علاقة مباشرة في نموذج البيانات الحالي بين دليل الحل وقياس أو KPI محدد. تُدار الأدلة من ملف الحل نفسه.</p><div className="mt-3 flex flex-wrap gap-2"><Button asChild size="sm" variant="outline"><Link href={`/solutions/${solution.id}/evidence`}>فتح أدلة الحل</Link></Button>{canUploadEvidence ? <Button asChild size="sm"><Link href={`/solutions/${solution.id}/evidence/new`}>رفع دليل</Link></Button> : null}</div></section>
    <section id="report" className="rounded-2xl border bg-surface p-4"><h2 className="text-lg font-bold">التقرير</h2><p className="mt-1 text-sm text-muted">لا يتضمن النظام الحالي تقريرًا أو تصديرًا مخصصًا لقياس الأثر؛ لذلك لا يُنشأ تقرير جديد هنا.</p></section>
    {canUpdate ? <section id="add-measurement"><Card><CardHeader><CardTitle>إضافة مؤشر وقياس</CardTitle></CardHeader><CardContent><ImpactForm solutionId={solution.id}/></CardContent></Card></section> : null}
    <p className="text-xs text-muted">الأرقام المعروضة قياسات تشغيلية داخلية وليست حكمًا رسميًا على الامتثال.</p>
  </div>;
}
