"use server";
import { revalidatePath } from "next/cache";
import type { WorkPriority } from "@prisma/client";
import { getAccessContext } from "@/server/authz";
import type { WorkspaceData } from "@/modules/dga/workspace-status";
import { createContribution, reviewContribution, submitContributionByToken, submitContributionByUser } from "./service";

export interface ContributionActionState { success?:string; error?:string; invitationPath?:string }
const path="/strategy/requirements/5-23-1-r1";
export async function createContributionAction(_:ContributionActionState,fd:FormData):Promise<ContributionActionState>{try{const actor=await getAccessContext();if(!actor)return{error:"يلزم تسجيل الدخول"};const result=await createContribution(actor,{sectionKey:String(fd.get("sectionKey")),contributorRole:String(fd.get("contributorRole")||"RESPONSIBLE") as "RESPONSIBLE"|"SUPPORTING",contributorUserId:String(fd.get("contributorUserId")||"")||undefined,name:String(fd.get("name")||""),email:String(fd.get("email")||""),jobTitle:String(fd.get("jobTitle")||""),departmentName:String(fd.get("departmentName")||""),dueDate:fd.get("dueDate")?new Date(String(fd.get("dueDate"))):null,priority:String(fd.get("priority")||"MEDIUM") as WorkPriority,note:String(fd.get("note")||"")});revalidatePath(path);return{success:result.invitationToken?"تم تجهيز الدعوة. لم يُرسل بريد إلكتروني؛ انسخ الرابط وشاركه بأمان.":"تم إنشاء المهمة داخل المنصة.",invitationPath:result.invitationToken?`/contribute/${result.invitationToken}`:undefined};}catch(error){const message=error instanceof Error?error.message:"";return{error:message==="RESPONSIBLE_EXISTS"?"يوجد مساهم مسؤول نشط لهذا القسم. غيّر المسؤول أو أضفه كمساهم داعم.":"تعذر إنشاء الإسناد. تحقق من البيانات والصلاحيات."};}}
export async function reviewContributionAction(_:ContributionActionState,fd:FormData):Promise<ContributionActionState>{try{const actor=await getAccessContext();if(!actor)return{error:"يلزم تسجيل الدخول"};await reviewContribution(actor,{id:String(fd.get("id")),decision:String(fd.get("decision")) as "ACCEPT"|"RETURN"|"CANCEL",notes:String(fd.get("notes")||""),dueDate:fd.get("dueDate")?new Date(String(fd.get("dueDate"))):null});revalidatePath(path);return{success:"تم تسجيل القرار وتحديث المهمة والتقدم."};}catch(error){return{error:error instanceof Error&&error.message==="NOTES_REQUIRED"?"ملاحظات الإعادة مطلوبة.":"تعذر تنفيذ القرار."};}}
export async function submitPlatformContributionAction(_:ContributionActionState,fd:FormData):Promise<ContributionActionState>{try{const actor=await getAccessContext();if(!actor)return{error:"يلزم تسجيل الدخول"};await submitContributionByUser(actor,String(fd.get("id")),JSON.parse(String(fd.get("sectionData"))) as WorkspaceData[string]);revalidatePath(path);return{success:"تم تسليم المساهمة للمراجعة."};}catch(error){return{error:error instanceof Error&&error.message.startsWith("MISSING:")?error.message.slice(8):"تعذر تسليم المساهمة."};}}
export async function submitInviteContributionAction(_:ContributionActionState,fd:FormData):Promise<ContributionActionState>{try{await submitContributionByToken(String(fd.get("token")),JSON.parse(String(fd.get("sectionData"))) as WorkspaceData[string]);return{success:"تم تسليم مساهمتك إلى مالك المتطلب بنجاح."};}catch(error){return{error:error instanceof Error&&error.message.startsWith("MISSING:")?error.message.slice(8):"تعذر تسليم المساهمة أو انتهت صلاحية الرابط."};}}
