import {createHash,randomBytes} from "crypto";
import type {Prisma,SectionContributionStatus,WorkPriority} from "@prisma/client";
import {prisma} from "@/server/db";
import type {AccessContext} from "@/server/access-context";
import {writeAudit,AUDIT} from "@/server/audit";
import {getWorkspaceConfig} from "@/modules/dga/workspace-config";
import {deriveOperationalStatus,missingWorkspaceFields,type WorkspaceData} from "@/modules/dga/workspace-status";
import {loadRequirementWorkspace} from "@/modules/dga/workspace-service";
import {getContributionDefinition,sectionLabel,type ContributionView} from "./types";

const activeStatuses:SectionContributionStatus[]=["NOT_SENT","INVITATION_SENT","OPENED","IN_PROGRESS","SUBMITTED","UNDER_REVIEW","NEEDS_AMENDMENT","OVERDUE"];
const hashToken=(token:string)=>createHash("sha256").update(token).digest("hex");
function definition(requirementId:string){const value=getContributionDefinition(requirementId);if(!value)throw new Error("UNSUPPORTED_REQUIREMENT");return value;}
function assertSection(requirementId:string,sectionKey:string){const item=definition(requirementId);if(!item.sections.includes(sectionKey))throw new Error("INVALID_SECTION");return sectionKey;}
function view(row:any,names:Record<string,string>):ContributionView{return{id:row.id,sectionKey:row.sectionKey,contributorRole:row.contributorRole,contributorUserId:row.contributorUserId,contributorName:row.contributorName,contributorEmail:row.contributorEmail,jobTitle:row.jobTitle,departmentName:row.departmentName,assignedByName:names[row.assignedById]??"مستخدم",reviewerName:row.reviewerUserId?(names[row.reviewerUserId]??"مستخدم"):null,dueDate:row.dueDate?.toISOString()??null,priority:row.priority,requesterNote:row.requesterNote,status:row.dueDate&&row.dueDate<new Date()&&activeStatuses.includes(row.status)?"OVERDUE":row.status,invitationDelivery:row.invitationDelivery,assignedAt:row.assignedAt.toISOString(),invitationSentAt:row.invitationSentAt?.toISOString()??null,openedAt:row.openedAt?.toISOString()??null,submittedAt:row.submittedAt?.toISOString()??null,reviewedAt:row.reviewedAt?.toISOString()??null,completedAt:row.completedAt?.toISOString()??null,latestSubmission:row.submissions[0]?{version:row.submissions[0].version,data:row.submissions[0].data,submittedAt:row.submissions[0].submittedAt.toISOString(),reviewNotes:row.submissions[0].reviewNotes}:null};}

export async function listContributionsForAssignment(assignmentId:string){const rows=await prisma.requirementSectionContribution.findMany({where:{assignmentId},include:{submissions:{orderBy:{version:"desc"},take:1}},orderBy:{assignedAt:"asc"}});const ids=rows.flatMap(row=>[row.assignedById,row.reviewerUserId]).filter(Boolean) as string[];const users=ids.length?await prisma.user.findMany({where:{id:{in:[...new Set(ids)]}},select:{id:true,name:true}}):[];const names=Object.fromEntries(users.map(user=>[user.id,user.name]));return rows.map(row=>view(row,names));}

export async function createContribution(actor:AccessContext,input:{requirementId:string;sectionKey:string;contributorRole:"RESPONSIBLE"|"SUPPORTING";contributorUserId?:string;name:string;email:string;jobTitle?:string;departmentName?:string;dueDate?:Date|null;priority:WorkPriority;note?:string}){
  const def=definition(input.requirementId);const loaded=await loadRequirementWorkspace(actor,input.requirementId);if(!loaded.canEdit)throw new Error("FORBIDDEN");const sectionKey=assertSection(input.requirementId,input.sectionKey);if(!input.name.trim()||!/^\S+@\S+\.\S+$/.test(input.email))throw new Error("VALIDATION");
  if(input.contributorRole==="RESPONSIBLE"){const existing=await prisma.requirementSectionContribution.findFirst({where:{assignmentId:loaded.assignment.id,sectionKey,contributorRole:"RESPONSIBLE",status:{in:activeStatuses},...(input.requirementId==="5-23-1-r3"?{requesterNote:input.note?.trim()||null}:{})}});if(existing)throw new Error("RESPONSIBLE_EXISTS");}
  let existingUser:null|{id:string;name:string;email:string}=null;if(input.contributorUserId)existingUser=await prisma.user.findFirst({where:{id:input.contributorUserId,status:"ACTIVE",registrationStatus:"APPROVED"},select:{id:true,name:true,email:true}});if(input.contributorUserId&&!existingUser)throw new Error("INVALID_USER");
  const token=existingUser?null:randomBytes(32).toString("base64url");const now=new Date();const label=sectionLabel(input.requirementId,sectionKey);
  const created=await prisma.$transaction(async tx=>{const task=existingUser?await tx.requirementTask.create({data:{assignmentId:loaded.assignment.id,type:"PREPARE",title:`استكمال ${label}`,status:"OPEN",priority:input.priority,requestedById:actor.userId,assignedToUserId:existingUser.id,dueDate:input.dueDate,nextAction:`فتح النطاق المسند: ${label}`}}):null;const row=await tx.requirementSectionContribution.create({data:{assignmentId:loaded.assignment.id,sectionKey,contributorRole:input.contributorRole,contributorUserId:existingUser?.id,contributorName:existingUser?.name??input.name.trim(),contributorEmail:existingUser?.email??input.email.trim().toLowerCase(),jobTitle:input.jobTitle?.trim()||null,departmentName:input.departmentName?.trim()||null,assignedById:actor.userId,dueDate:input.dueDate,priority:input.priority,requesterNote:input.note?.trim()||null,status:existingUser?"INVITATION_SENT":"NOT_SENT",invitationDelivery:existingUser?"NOT_REQUIRED":"PREPARED",invitationTokenHash:token?hashToken(token):null,invitationTokenLast4:token?.slice(-4),invitationSentAt:existingUser?now:null,taskId:task?.id}});if(existingUser)await tx.notification.create({data:{userId:existingUser.id,title:`مساهمة جديدة: ${label}`,message:input.note?.trim()||`تم إسناد تعبئة نطاق ضمن المتطلب ${def.code}`,type:"INFO"}});await writeAudit({actorUserId:actor.userId,action:AUDIT.SECTION_CONTRIBUTION_ASSIGNED,entityType:"REQUIREMENT_ASSIGNMENT",entityId:loaded.assignment.id,departmentId:loaded.assignment.departmentId,summary:`إسناد تعبئة «${label}» إلى ${existingUser?.name??input.name.trim()}`,metadata:{requirementCode:def.code,sectionKey,contributionId:row.id,delivery:existingUser?"مهمة داخل المنصة":"رابط دعوة مُجهز ولم يُرسل بالبريد"}},tx);return row;});return{contributionId:created.id,invitationToken:token};
}

async function rowWithContext(where:{id?:string;invitationTokenHash?:string}){return prisma.requirementSectionContribution.findFirst({where,include:{assignment:{include:{requirement:true,department:{include:{organization:true}}}},submissions:{orderBy:{version:"desc"}}}});}
function requirementIdForCode(code:string){const def=["5-23-1-r1","5-23-1-r2","5-23-1-r3","5-23-2-r1","5-23-2-r2","5-23-2-r3","5-23-2-r4"].map(getContributionDefinition).find(item=>item?.code===code);if(!def)throw new Error("UNSUPPORTED_REQUIREMENT");return def.requirementId;}

function mergeAcceptedData(requirementId:string,current:WorkspaceData,sectionKey:string,accepted:WorkspaceData[string],requesterNote:string|null){
  if(!["5-23-2-r3","5-23-2-r4"].includes(requirementId))return{...current,[sectionKey]:accepted};
  const eventId=requesterNote?.match(/^\[event:([^\]]+)\]/m)?.[1];
  const collectionKey=requirementId==="5-23-2-r3"?"openInnovationEvents":"cooperationActivations";
  const events=Array.isArray(current[collectionKey])?current[collectionKey] as Record<string,unknown>[]:[];
  const index=eventId?events.findIndex(event=>event.id===eventId):events.length===1?0:-1;
  if(index<0)throw new Error("EVENT_CONTEXT_REQUIRED");
  current[collectionKey]=events.map((event,eventIndex)=>eventIndex===index?{...event,[sectionKey]:accepted}:event);
  return current;
}
async function contributionForActor(actor:AccessContext,id:string){const row=await rowWithContext({id});if(!row||row.contributorUserId!==actor.userId)throw new Error("FORBIDDEN");requirementIdForCode(row.assignment.requirement.code);return row;}
async function contributionForToken(token:string){const row=await rowWithContext({invitationTokenHash:hashToken(token)});if(!row||row.status==="CANCELLED")throw new Error("NOT_FOUND");requirementIdForCode(row.assignment.requirement.code);return row;}

export async function openContributionByToken(token:string){const row=await contributionForToken(token);const requirementId=requirementIdForCode(row.assignment.requirement.code);if(!row.openedAt)await prisma.$transaction(async tx=>{await tx.requirementSectionContribution.update({where:{id:row.id},data:{openedAt:new Date(),status:"OPENED"}});await writeAudit({action:AUDIT.SECTION_CONTRIBUTION_OPENED,entityType:"REQUIREMENT_ASSIGNMENT",entityId:row.assignmentId,departmentId:row.assignment.departmentId,summary:`فتح دعوة المساهمة في «${sectionLabel(requirementId,row.sectionKey)}»`,metadata:{contributionId:row.id}},tx);});return row;}

async function submit(row:any,data:WorkspaceData[string],identity:{userId?:string;email?:string}){const requirementId=requirementIdForCode(row.assignment.requirement.code);const sectionKey=assertSection(requirementId,row.sectionKey);const config=getWorkspaceConfig(requirementId)!;const section=config.sections.find(item=>item.key===sectionKey)!;const missing=missingWorkspaceFields({...config,sections:[section]},{[sectionKey]:data} as WorkspaceData);if(missing.length)throw new Error(`MISSING:${missing.join("، ")}`);const version=(row.submissions[0]?.version??0)+1;await prisma.$transaction(async tx=>{await tx.requirementSectionSubmission.create({data:{contributionId:row.id,version,data:data as Prisma.InputJsonValue,submittedById:identity.userId,submitterEmail:identity.email}});await tx.requirementSectionContribution.update({where:{id:row.id},data:{status:"SUBMITTED",submittedAt:new Date()}});await writeAudit({actorUserId:identity.userId,action:AUDIT.SECTION_CONTRIBUTION_SUBMITTED,entityType:"REQUIREMENT_ASSIGNMENT",entityId:row.assignmentId,departmentId:row.assignment.departmentId,summary:`تسليم مساهمة «${sectionLabel(requirementId,sectionKey)}» — النسخة ${version}`,metadata:{contributionId:row.id,version,requirementCode:row.assignment.requirement.code}},tx);});}
export async function submitContributionByToken(token:string,data:WorkspaceData[string]){const row=await contributionForToken(token);return submit(row,data,{email:row.contributorEmail});}
export async function submitContributionByUser(actor:AccessContext,id:string,data:WorkspaceData[string]){const row=await contributionForActor(actor,id);return submit(row,data,{userId:actor.userId,email:row.contributorEmail});}

export async function reviewContribution(actor:AccessContext,input:{id:string;decision:"ACCEPT"|"RETURN"|"CANCEL";notes?:string;dueDate?:Date|null}){const candidate=await rowWithContext({id:input.id});if(!candidate)throw new Error("NOT_FOUND");const requirementId=requirementIdForCode(candidate.assignment.requirement.code);const loaded=await loadRequirementWorkspace(actor,requirementId);if(!loaded.canEdit||candidate.assignmentId!==loaded.assignment.id)throw new Error("FORBIDDEN");const row=candidate;const sectionKey=assertSection(requirementId,row.sectionKey);if(input.decision==="RETURN"&&!input.notes?.trim())throw new Error("NOTES_REQUIRED");if(input.decision==="ACCEPT"&&!row.submissions[0])throw new Error("NO_SUBMISSION");
  if(input.decision==="ACCEPT"&&["5-23-2-r3","5-23-2-r4"].includes(requirementId))mergeAcceptedData(requirementId,loaded.assignment.workspaceData as WorkspaceData,sectionKey,row.submissions[0].data as WorkspaceData[string],row.requesterNote);
  await prisma.$transaction(async tx=>{const now=new Date();if(input.decision==="ACCEPT"){const current=loaded.assignment.workspaceData as WorkspaceData;let accepted=row.submissions[0].data as WorkspaceData[string];if(requirementId==="5-23-1-r3"&&Array.isArray(accepted)){const existing=Array.isArray(current[sectionKey])?current[sectionKey] as Record<string,unknown>[]:[];const incoming=accepted as Record<string,unknown>[];const key=sectionKey==="cooperations"?"partnerName":"cooperationName";const incomingNames=new Set(incoming.map(item=>String(item[key]??"").trim()).filter(Boolean));accepted=[...existing.filter(item=>!incomingNames.has(String(item[key]??"").trim())),...incoming];}const data={...current,[sectionKey]:accepted};const status=deriveOperationalStatus(getWorkspaceConfig(requirementId)!,data,loaded.approvedCounts);await tx.complianceRequirementAssignment.update({where:{id:loaded.assignment.id},data:{workspaceData:data as Prisma.InputJsonValue,operationalStatus:status,lastSavedById:actor.userId}});await tx.requirementSectionSubmission.update({where:{id:row.submissions[0].id},data:{reviewDecision:"ACCEPTED",reviewNotes:input.notes?.trim()||null,reviewedById:actor.userId,reviewedAt:now}});await tx.requirementSectionContribution.update({where:{id:row.id},data:{status:"COMPLETED",reviewerUserId:actor.userId,reviewedAt:now,completedAt:now}});if(row.taskId)await tx.requirementTask.update({where:{id:row.taskId},data:{status:"COMPLETED",completedAt:now}});}else if(input.decision==="RETURN"){await tx.requirementSectionSubmission.update({where:{id:row.submissions[0].id},data:{reviewDecision:"NEEDS_AMENDMENT",reviewNotes:input.notes!.trim(),reviewedById:actor.userId,reviewedAt:now}});await tx.requirementSectionContribution.update({where:{id:row.id},data:{status:"NEEDS_AMENDMENT",reviewerUserId:actor.userId,reviewedAt:now,dueDate:input.dueDate??row.dueDate}});if(row.taskId)await tx.requirementTask.update({where:{id:row.taskId},data:{status:"OPEN",completedAt:null,dueDate:input.dueDate??row.dueDate,nextAction:"تعديل المساهمة وإعادة تسليمها"}});}else{await tx.requirementSectionContribution.update({where:{id:row.id},data:{status:"CANCELLED",cancelledAt:now}});if(row.taskId)await tx.requirementTask.update({where:{id:row.taskId},data:{status:"CANCELLED"}});}const action=input.decision==="ACCEPT"?AUDIT.SECTION_CONTRIBUTION_ACCEPTED:input.decision==="RETURN"?AUDIT.SECTION_CONTRIBUTION_RETURNED:AUDIT.SECTION_CONTRIBUTION_CANCELLED;const label=input.decision==="ACCEPT"?"قبول":input.decision==="RETURN"?"إعادة للتعديل":"إلغاء";await writeAudit({actorUserId:actor.userId,action,entityType:"REQUIREMENT_ASSIGNMENT",entityId:loaded.assignment.id,departmentId:loaded.assignment.departmentId,summary:`${label} مساهمة «${sectionLabel(requirementId,sectionKey)}»`,metadata:{contributionId:row.id,notes:input.notes,requirementCode:row.assignment.requirement.code}},tx);});}

export async function loadInvite(token:string){const row=await openContributionByToken(token);const requirementId=requirementIdForCode(row.assignment.requirement.code);const def=definition(requirementId);return{contributionId:row.id,organization:row.assignment.department.organization.nameAr,unit:def.unit,requirement:def.number,requirementId,requirementTitle:row.assignment.requirement.titleAr,sectionKey:assertSection(requirementId,row.sectionKey),sectionLabel:sectionLabel(requirementId,row.sectionKey),dueDate:row.dueDate?.toISOString()??null,note:row.requesterNote,status:row.status,latestData:row.submissions[0]?.data??null};}
export async function loadPlatformContribution(actor:AccessContext,id:string){const row=await contributionForActor(actor,id);const requirementId=requirementIdForCode(row.assignment.requirement.code);if(!row.openedAt)await prisma.requirementSectionContribution.update({where:{id:row.id},data:{openedAt:new Date(),status:"OPENED"}});return{contributionId:row.id,organization:row.assignment.department.organization.nameAr,requirementId,unit:definition(requirementId).unit,requirement:definition(requirementId).number,sectionKey:assertSection(requirementId,row.sectionKey),dueDate:row.dueDate?.toISOString()??null,note:row.requesterNote,latestData:row.submissions[0]?.data??null};}
