import { CalendarClock, Check, Clock3, Lightbulb, LockKeyhole, Map, Sparkles, Target, UploadCloud } from "lucide-react";

import { Badge } from "@/components/ui/badge";

const stages = ["تقديم الفكرة", "التقييم الأولي", "دورة الابتكار", "الاحتضان", "مسرعة الأعمال", "الدعم والتبني", "قياس الأثر", "الاكتمال"];
const tasks = ["تحديد المشكلة", "فهم المستفيد", "التحقق من المشكلة", "تطوير الحل", "النموذج الأولي", "الاختبار", "النتائج", "المراجعة"];

export function InnovatorJourneyPreview() {
  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 pb-10">
    <header className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-primary-700 via-primary to-secondary-600 p-6 text-white shadow-xl shadow-primary/10 sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-5"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold ring-1 ring-white/20"><Map className="h-4 w-4"/> رحلتي الابتكارية</div><h1 className="text-2xl font-black sm:text-3xl">مساعد ذكي لطلبات المستفيدين</h1><p className="mt-2 text-sm text-white/80">خطوة واضحة في كل مرة. أكمل مهمتك الحالية، ثم تابع تقدم فكرتك عبر محطات الرحلة.</p></div><div className="min-w-48 rounded-2xl bg-white/10 p-4 ring-1 ring-white/20"><div className="flex items-end justify-between"><span className="text-xs text-white/75">نسبة الرحلة</span><b className="text-2xl">31%</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/15"><div className="h-full w-[31%] rounded-full bg-white"/></div></div></div>
    </header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Sparkles} label="المرحلة الحالية" value="دورة الابتكار"/><Summary icon={Target} label="المهمة الحالية" value="التحقق من المشكلة"/><Summary icon={CalendarClock} label="أقرب موعد" value="19 سبتمبر 2026"/><Summary icon={Clock3} label="الوقت المتبقي" value="3 أيام"/></section>
    <section className="rounded-[2rem] border border-border bg-surface p-5 shadow-sm sm:p-7"><div className="mb-7"><p className="text-xs font-bold text-primary">المسار الرئيسي</p><h2 className="mt-1 text-xl font-black">محطات رحلتك</h2></div><div className="relative overflow-x-auto pb-3"><div className="absolute right-10 left-10 top-9 h-1 bg-slate-100"><div className="h-full w-[29%] bg-gradient-to-l from-success to-primary"/></div><ol className="relative z-[1] grid min-w-[900px] grid-cols-8 gap-3">{stages.map((stage,index)=><li key={stage} className="flex flex-col items-center text-center"><span className={`grid h-[4.5rem] w-[4.5rem] place-items-center rounded-2xl border-2 ${index<2?"border-success bg-success text-white":index===2?"border-primary bg-primary text-white ring-4 ring-primary-50":"border-slate-200 bg-slate-50 text-slate-400"}`}>{index<2?<Check className="h-7 w-7"/>:index===2?<Sparkles className="h-7 w-7"/>:<LockKeyhole className="h-5 w-5"/>}</span><b className={`mt-3 text-xs ${index===2?"text-primary":""}`}>{stage}</b><span className="mt-1 text-[10px] text-muted">{index<2?"مكتمل":index===2?"المرحلة الحالية":"مقفل"}</span></li>)}</ol></div></section>
    <section className="grid items-start gap-5 lg:grid-cols-[1.55fr_.75fr]"><div className="rounded-[2rem] border border-primary/20 bg-primary-50/50 p-5 sm:p-7"><Badge variant="primary">المرحلة الحالية</Badge><h2 className="mt-2 text-xl font-black">دورة الابتكار</h2><p className="mt-1 text-sm text-muted">أنجز المهام بالترتيب؛ تُفتح كل خطوة عندما تصبح جاهزة لك.</p><div className="relative mt-7 overflow-x-auto pb-4"><div className="absolute right-7 left-7 top-6 h-0.5 bg-slate-200"/><ol className="relative z-[1] grid min-w-[760px] grid-cols-8 gap-2">{tasks.map((task,index)=><li key={task} className="flex flex-col items-center text-center"><span className={`grid h-12 w-12 place-items-center rounded-full border-2 text-sm font-black ${index<2?"border-success bg-success text-white":index===2?"border-primary bg-white text-primary ring-4 ring-primary-100":"border-slate-200 bg-slate-50 text-slate-400"}`}>{index<2?<Check className="h-5 w-5"/>:index===2?"3":<LockKeyhole className="h-4 w-4"/>}</span><b className={`mt-3 text-[11px] ${index===2?"text-primary":""}`}>{task}</b></li>)}</ol></div></div><aside className="rounded-[2rem] border border-primary/25 bg-surface p-6 shadow-lg shadow-primary/5"><Badge variant="primary">مهمتك الآن</Badge><h2 className="mt-4 text-lg font-black">التحقق من المشكلة</h2><p className="mt-2 text-sm leading-6 text-muted">وثّق ما يؤكد وجود المشكلة من منظور المستفيد وأرفق الدليل المناسب.</p><div className="mt-5 space-y-3 rounded-2xl bg-slate-50 p-4 text-sm"><p className="flex gap-2"><CalendarClock className="h-4 w-4 text-warning"/> الموعد: 19 سبتمبر</p><p className="flex gap-2"><UploadCloud className="h-4 w-4 text-primary"/> مقابلات أو ملاحظات المستفيدين</p></div></aside></section>
  </div>;
}

function Summary({icon:Icon,label,value}:{icon:typeof Lightbulb;label:string;value:string}) { return <div className="flex items-center gap-3 rounded-2xl border border-border bg-surface p-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary-50 text-primary"><Icon className="h-5 w-5"/></span><div><p className="text-[11px] text-muted">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div></div>; }
