"use client";

import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft, FileCheck2, FolderSearch, TrendingUp } from "lucide-react";
import { PreviewLink as Link } from "@/components/layout/preview-link";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { DEMO_EVIDENCE, DEMO_IDEAS, DEMO_IMPACT_INDICATORS, DEMO_IMPACT_MEASUREMENTS, DEMO_REPORTS, DEMO_SOLUTIONS, DEMO_TASKS } from "@/server/demo-data";

const colors = ["#155e75", "#0f766e", "#d97706"];

function ChartCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card>; }

export function PortfolioDashboardPreview() {
  const byStage = [{ name: "أفكار", value: DEMO_IDEAS.filter((x) => x.gate < 4).length }, { name: "تجربة", value: DEMO_SOLUTIONS.filter((x) => x.maturityStage === "PILOT").length }, { name: "تشغيل", value: DEMO_SOLUTIONS.filter((x) => x.maturityStage === "OPERATIONAL").length }];
  const sectors = [{ name: "الخدمات الرقمية", value: 2 }, { name: "تجربة المستفيد", value: 2 }, { name: "التشغيل", value: 1 }];
  const records = [...DEMO_IDEAS.map((x) => ({ name: x.titleAr, kind: "فكرة", sector: x.category, stage: `Stage ${x.gate}`, status: x.status })), ...DEMO_SOLUTIONS.map((x) => ({ name: x.nameAr, kind: "حل", sector: x.domain, stage: x.maturityStage, status: x.portfolioStatus }))];
  return <div className="space-y-5"><PageHeader title="لوحة المحفظة" description="عرض مجمع للأفكار والحلول حسب المرحلة والقطاع. هذه أرقام معاينة فقط." action={<Button asChild variant="outline"><Link href="/solutions">سجل الحلول <ArrowLeft className="h-4 w-4"/></Link></Button>}/>
    <div className="grid gap-4 sm:grid-cols-3">{[["إجمالي السجلات",records.length,"أفكار وحلول"],["حلول تشغيلية",byStage[2].value,"قيد الاستخدام"],["تحتاج متابعة",DEMO_TASKS.length,"مهام مرتبطة"]].map(([label,value,hint])=><Card key={String(label)}><CardContent className="p-5"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-muted">{hint}</p></CardContent></Card>)}</div>
    <div className="grid gap-5 lg:grid-cols-2"><ChartCard title="توزيع المحفظة حسب المرحلة"><ResponsiveContainer width="100%" height={240}><BarChart data={byStage}><XAxis dataKey="name" fontSize={12}/><YAxis allowDecimals={false} fontSize={12}/><Tooltip/><Bar dataKey="value" fill="#0f766e" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="المحفظة حسب القطاع"><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={sectors} dataKey="value" nameKey="name" outerRadius={85} label>{sectors.map((_, index) => <Cell key={index} fill={colors[index]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="flex flex-wrap justify-center gap-3 text-xs">{sectors.map((item,index)=><span key={item.name}><i className="me-1 inline-block h-2.5 w-2.5 rounded-full" style={{background:colors[index]}}/>{item.name}</span>)}</div></ChartCard></div>
    <RecordsTable rows={records}/>
  </div>;
}

function RecordsTable({ rows }: { rows: { name: string; kind: string; sector: string | null; stage: string; status: string }[] }) { return <Card><CardHeader><CardTitle>سجل المحفظة المجمع</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-muted">{["السجل","النوع","القطاع","المرحلة","الحالة"].map((x)=><th className="p-3 text-start" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((x)=><tr className="border-b last:border-0" key={`${x.kind}-${x.name}`}><td className="p-3 font-semibold">{x.name}</td><td className="p-3"><Badge variant="neutral">{x.kind}</Badge></td><td className="p-3">{x.sector}</td><td className="p-3">{x.stage}</td><td className="p-3">{x.status}</td></tr>)}</tbody></table></div></CardContent></Card>; }

export function ImpactDashboardPreview() {
  const cost = DEMO_SOLUTIONS.reduce((sum,x) => sum + (typeof x.costReductionValue === "number" ? x.costReductionValue : 0), 0);
  const indicatorData = DEMO_IMPACT_INDICATORS.map((indicator) => ({ name: indicator.nameAr, baseline: Number(indicator.baselineValue), target: Number(indicator.targetValue), actual: Number(DEMO_IMPACT_MEASUREMENTS.find((x) => x.indicatorId === indicator.id)?.actualValue ?? 0) }));
  return <div className="space-y-5"><PageHeader title="لوحة الأثر" description="متابعة مرئية للنتائج والقياسات المتاحة. القيم معروضة للمعاينة وليست بيانات تشغيلية." action={<Button asChild variant="outline"><Link href="/impact/demo-sol-2">مساحة القياس <ArrowLeft className="h-4 w-4"/></Link></Button>}/>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["خفض التكلفة المسجل",cost ? `${cost.toLocaleString("ar-SA")} ر.س` : "لم يسجل"],["المستفيدون",DEMO_SOLUTIONS.reduce((sum,x) => sum + (x.beneficiaryCount ?? 0), 0).toLocaleString("ar-SA")],["قياسات متحقق منها",DEMO_IMPACT_MEASUREMENTS.filter((x) => x.verificationStatus === "VERIFIED").length],["تحتاج دليلًا",DEMO_IMPACT_MEASUREMENTS.filter((x) => !x.actualValue || x.verificationStatus !== "VERIFIED").length]].map(([label,value])=><Card className="bg-gradient-to-bl from-white to-primary-50" key={String(label)}><CardContent className="p-5"><TrendingUp className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></CardContent></Card>)}</div>
    <ChartCard title="قبل التنفيذ والمستهدف والنتيجة الفعلية"><ResponsiveContainer width="100%" height={280}><BarChart data={indicatorData}><XAxis dataKey="name" fontSize={11}/><YAxis fontSize={12}/><Tooltip/><Bar dataKey="baseline" name="خط الأساس" fill="#94a3b8"/><Bar dataKey="target" name="المستهدف" fill="#0f766e"/><Bar dataKey="actual" name="الفعلي" fill="#155e75"/></BarChart></ResponsiveContainer></ChartCard>
    <div className="grid gap-4 lg:grid-cols-2">{DEMO_IMPACT_MEASUREMENTS.map((measurement) => { const indicator = DEMO_IMPACT_INDICATORS.find((x) => x.id === measurement.indicatorId); return <Card key={measurement.id}><CardContent className="p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold">{indicator?.nameAr}</p><p className="mt-1 text-xs text-muted">{measurement.dataSource}</p></div><Badge variant={measurement.verificationStatus === "VERIFIED" ? "success" : "warning"}>{measurement.verificationStatus === "VERIFIED" ? "تم التحقق" : "بانتظار التحقق"}</Badge></div><Progress className="my-4" value={measurement.actualValue && indicator?.targetValue ? Math.min(100, Math.round(Number(measurement.actualValue) / Number(indicator.targetValue) * 100)) : 0}/><p className="text-xs text-muted">النتيجة: {measurement.actualValue ?? "لم تسجل"} {indicator?.unit ?? ""} · {measurement.notes}</p></CardContent></Card>; })}</div>
  </div>;
}

export function OperationsDataPreview({ path }: { path: string }) {
  if (path === "/my-tasks") return <div className="space-y-5"><PageHeader title="مهامي" description="إجراءات DEMO مرتبطة بالمتطلبات والأدلة الحالية."/><div className="space-y-3">{DEMO_TASKS.map((task)=><Card key={task.id}><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_auto]"><div><p className="font-semibold">{task.title}</p><p className="mt-1 text-xs text-muted">المسؤول: {task.assignedToName} · الإجراء التالي: {task.nextAction}</p></div><Badge variant={task.priority === "HIGH" ? "warning" : "neutral"}>{task.priority === "HIGH" ? "عالية" : "متوسطة"}</Badge></CardContent></Card>)}</div></div>;
  if (path === "/reports") return <div className="space-y-5"><PageHeader title="التقارير" description="تقارير تجريبية مبنية على سجلات المحفظة والأدلة والقياسات."/><div className="grid gap-4 md:grid-cols-3">{DEMO_REPORTS.map((report)=><Card key={report.id}><CardContent className="p-5"><FileCheck2 className="h-5 w-5 text-primary"/><p className="mt-3 font-semibold">{report.title}</p><p className="mt-1 text-xs text-muted">{report.scope}</p><div className="mt-4 flex items-center justify-between"><Badge variant={report.status === "جاهز للعرض" ? "success" : "warning"}>{report.status}</Badge><span className="text-xs text-muted">{report.updatedAt}</span></div></CardContent></Card>)}</div></div>;
  const title = path === "/evidence-matrix" ? "مصفوفة أدلة القياس" : path === "/evidence-repository" ? "مستودع الأدلة" : "مركز المراجعات والاعتمادات";
  return <div className="space-y-5"><PageHeader title={title} description="بيانات Demo واقعية تربط الدليل بمتطلبه ومالكه وحالة مراجعته."/><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-muted">{["الدليل","المصدر","المتطلب","المالك","المراجعة","تاريخ الرفع"].map((x)=><th key={x} className="p-3 text-start">{x}</th>)}</tr></thead><tbody>{DEMO_EVIDENCE.map((evidence)=><tr key={evidence.id} className="border-b last:border-0"><td className="p-3 font-semibold"><FolderSearch className="me-2 inline h-4 w-4 text-primary"/>{evidence.nameAr}</td><td className="p-3">{evidence.source}</td><td className="p-3">{evidence.requirementCode}</td><td className="p-3">{evidence.owner}</td><td className="p-3"><Badge variant={evidence.reviewStatus === "معتمد" ? "success" : evidence.reviewStatus === "يحتاج تعديل" ? "warning" : "primary"}>{evidence.reviewStatus}</Badge></td><td className="p-3">{evidence.uploadedAt}</td></tr>)}</tbody></table></div></CardContent></Card></div>;
}
