import Link from "next/link";

import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Field = { label: string; type?: "text" | "date" | "select" | "textarea" | "file"; required?: boolean; options?: string[]; placeholder?: string };

const forms: Record<string, { title: string; back: string; fields: Field[] }> = {
  activity: { title: "إنشاء برنامج أو فعالية", back: "/activities", fields: [{label:"اسم البرنامج أو الفعالية",required:true},{label:"النوع",type:"select",required:true,options:["برنامج","هاكاثون","ورشة عمل"]},{label:"الهدف الاستراتيجي",type:"select",required:true,options:["SO-01 رفع كفاءة تبني الحلول","SO-02 تعزيز الشراكات"]},{label:"الإدارة المالكة",required:true},{label:"مدير البرنامج",required:true},{label:"تاريخ البداية",type:"date",required:true},{label:"تاريخ النهاية",type:"date",required:true},{label:"وصف مختصر",type:"textarea",required:true}] },
  challenge: { title: "تسجيل تحدٍ جديد", back: "/challenges", fields: [{label:"عنوان التحدي",required:true},{label:"الجهة أو الإدارة المالكة",required:true},{label:"التصنيف",type:"select",required:true,options:["تحسين الخدمات","الاستدامة","التحول الرقمي"]},{label:"وصف المشكلة",type:"textarea",required:true},{label:"النتيجة المستهدفة",type:"textarea",required:true},{label:"الموعد المستهدف",type:"date",required:true}] },
  innovation: { title: "إضافة سجل إلى بنك الابتكار", back: "/governance/ideas", fields: [{label:"اسم الابتكار",required:true},{label:"المصدر",type:"select",required:true,options:["برنامج أو فعالية","تحدٍ مؤسسي","اقتراح داخلي","شريك خارجي"]},{label:"المالك",required:true},{label:"الفئة",required:true},{label:"مرحلة النضج",type:"select",required:true,options:["مفهوم","نموذج أولي","إثبات مفهوم","نسخة تجريبية"]},{label:"الفجوات الحالية",type:"textarea"},{label:"احتياجات الدعم",type:"textarea"}] },
  solution: { title: "تسجيل حل ابتكاري", back: "/solutions", fields: [{label:"اسم الحل",required:true},{label:"السجل المصدر",required:true},{label:"الإدارة المالكة",required:true},{label:"مسؤول الحل",required:true},{label:"وصف الحل",type:"textarea",required:true},{label:"مرحلة النضج",type:"select",required:true,options:["إثبات مفهوم","نسخة تجريبية","تشغيل فعلي"]},{label:"الموعد المستهدف",type:"date"}] },
  committee: { title: "تشكيل لجنة", back: "/governance", fields: [{label:"اسم اللجنة",required:true},{label:"الغرض",type:"textarea",required:true},{label:"رئيس اللجنة",required:true},{label:"الأعضاء",required:true,placeholder:"اختيار أعضاء متعدد"},{label:"السجلات المسندة",placeholder:"اختيار حلول أو ابتكارات"},{label:"موعد الاجتماع",type:"date"}] },
  impact: { title: "إضافة قياس أثر", back: "/impact", fields: [{label:"الحل أو البرنامج",required:true},{label:"الأثر المتوقع",type:"textarea",required:true},{label:"المؤشر",required:true},{label:"خط الأساس",required:true},{label:"المستهدف",required:true},{label:"النتيجة الفعلية"},{label:"فترة القياس",required:true},{label:"دليل التحقق",type:"file"}] },
  evidence: { title: "رفع دليل أو وثيقة", back: "/evidence", fields: [{label:"عنوان الوثيقة",required:true},{label:"السجل المصدر",required:true},{label:"نوع الوثيقة",type:"select",required:true,options:["محضر اعتماد","تقرير تجربة","تقرير أثر","مستند اتفاقية"]},{label:"متطلب الامتثال المرتبط",type:"select",options:["5.23.1","5.23.2","5.23.3","5.24.1","5.24.2"]},{label:"الملف",type:"file",required:true},{label:"ملاحظات المراجعة",type:"textarea"}] },
  partner: { title: "إضافة جهة أو شريك", back: "/partners", fields: [{label:"اسم الجهة",required:true},{label:"نوع العلاقة",type:"select",required:true,options:["شريك بحثي","شريك تقني","جهة داعمة"]},{label:"مسؤول التواصل",required:true},{label:"البريد الإلكتروني",required:true},{label:"البرامج والحلول المرتبطة",placeholder:"اختيار متعدد"},{label:"الإجراء التالي",type:"textarea"}] },
  agreement: { title: "إضافة اتفاقية تعاون", back: "/agreements", fields: [{label:"نوع الاتفاقية",required:true},{label:"الجهة",required:true},{label:"تاريخ البداية",type:"date",required:true},{label:"تاريخ النهاية",type:"date",required:true},{label:"الالتزامات",type:"textarea",required:true},{label:"البرامج أو الحلول المرتبطة"},{label:"وثيقة الاتفاقية",type:"file"},{label:"حالة التجديد",type:"select",options:["غير مطلوب","مراجعة لاحقة","تجديد قريب"]}] },
  user: { title: "إدارة مستخدم وصلاحية", back: "/admin/users", fields: [{label:"اسم المستخدم",required:true},{label:"البريد الإلكتروني",required:true},{label:"فئة المستخدم",type:"select",required:true,options:["مدير النظام / مالك المنصة","مستخدم داخلي / مسؤول ابتكار","شريك خارجي","مطّلع / قيادة"]},{label:"الدور",required:true},{label:"النطاق",required:true},{label:"الإجراءات المسموحة",placeholder:"اختيار متعدد"}] },
  report: { title: "إنشاء معاينة تقرير", back: "/reports", fields: [{label:"فئة التقرير",type:"select",required:true,options:["برنامج أو فعالية","المحفظة الابتكارية","الحلول","الأثر","الجاهزية والامتثال","تنفيذي"]},{label:"الفترة",required:true},{label:"النطاق",required:true},{label:"السجلات المشمولة",placeholder:"اختيار متعدد"},{label:"ملاحظات العرض",type:"textarea"}] },
};

export const PREVIEW_FORM_KINDS = Object.keys(forms);

export function PreviewForm({ kind }: { kind: string }) {
  const form = forms[kind] ?? forms.activity;
  return <div className="space-y-5"><Link className="text-xs text-muted hover:text-primary" href={form.back}>العودة</Link><PageHeader title={form.title} description="نموذج مقترح لمراجعة المدخلات فقط؛ لن تُحفظ أي بيانات."/><Badge variant="warning">نموذج معاينة — بلا حفظ</Badge><Card><CardContent className="grid gap-5 p-6 md:grid-cols-2">{form.fields.map(field=><div className={field.type==="textarea"?"md:col-span-2":""} key={field.label}><Label>{field.label} {field.required?<span className="text-danger">*</span>:<span className="text-muted">(اختياري)</span>}</Label>{field.type==="select"?<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm"><option>اختر...</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:field.type==="textarea"?<textarea className="mt-2 min-h-24 w-full rounded-xl border p-3 text-sm" placeholder={field.placeholder}/>:<Input className="mt-2" type={field.type==="file"?"file":field.type??"text"} placeholder={field.placeholder}/>}</div>)}<div className="flex gap-2 md:col-span-2"><Button disabled>حفظ — غير متاح في المعاينة</Button><Button asChild variant="outline"><Link href={form.back}>إلغاء والعودة</Link></Button></div></CardContent></Card></div>;
}
