import type {PreviewPersonaKey} from "@/lib/ux-preview";
import type {WorkspaceData} from "./workspace-status";

const activation={
  id:"majmaah-2026",cooperationName:"جامعة المجمعة",agreementTitle:"اتفاقية التعاون البحثي والابتكاري 2026",agreementReference:"COOP-2026-014",scope:"البحث التطبيقي ونقل المعرفة وتطوير النماذج الأولية",owner:"نورة العتيبي",department:"إدارة الشراكات",responsible:"خالد القحطاني",partnerContact:"د. سارة المطيري",partnerEmail:"s.almotairi@example.edu.sa",startDate:"2026-01-15",endDate:"2027-01-14",status:"قيد التفعيل",nextAction:"استكمال محضر اجتماع الربع الثالث ومتابعة التزام الشريك",
  plan:{objectives:"تفعيل البحث التطبيقي ونقل المعرفة وتحويل نتائج التعاون إلى نموذج أولي قابل للتجربة",expectedOutputs:"دراسة مشتركة، ورشتا نقل معرفة، ونموذج إثبات مفهوم",responsibleDepartments:"إدارة الشراكات، إدارة الابتكار",partnerResponsibilities:"توفير الخبراء والباحثين ومراجعة المخرجات",owner:"نورة العتيبي",status:"قيد التنفيذ"},
  milestones:[{id:"m1",name:"اعتماد خطة التفعيل",targetDate:"2026-02-01",owner:"إدارة الشراكات",status:"مكتمل"},{id:"m2",name:"إنجاز الدراسة المشتركة",targetDate:"2026-06-30",owner:"فريق البحث المشترك",status:"مكتمل"},{id:"m3",name:"اختبار إثبات المفهوم",targetDate:"2026-10-15",owner:"إدارة الابتكار",status:"قيد التنفيذ"}],
  meetings:[
    {id:"q1",title:"اجتماع متابعة التعاون — الربع الأول",quarter:"Q1",date:"2026-03-18",startTime:"10:00",endTime:"11:30",location:"مقر الجهة",organizer:"نورة العتيبي",internalAttendees:"فريق الشراكات والابتكار",partnerAttendees:"د. سارة المطيري وفريق المركز",agenda:"اعتماد خطة التفعيل",discussion:"الأولويات ونطاق الدراسة",decisions:"اعتماد الخطة وبدء الدراسة",commitments:"تشكيل فريق العمل المشترك",minutes:"محضر معتمد ومرفوع",minutesState:"معتمد",status:"مكتمل"},
    {id:"q2",title:"اجتماع متابعة التعاون — الربع الثاني",quarter:"Q2",date:"2026-06-22",startTime:"11:00",endTime:"12:30",location:"عن بعد",organizer:"خالد القحطاني",internalAttendees:"فريق الابتكار",partnerAttendees:"فريق البحث",agenda:"مراجعة الدراسة ونقل المعرفة",discussion:"نتائج الدراسة وخطة الورشة",decisions:"اعتماد الدراسة وتنفيذ الورشة",commitments:"تسليم مادة نقل المعرفة",minutes:"محضر معتمد ومرفوع",minutesState:"معتمد",status:"مكتمل"},
    {id:"q3",title:"اجتماع متابعة التعاون — الربع الثالث",quarter:"Q3",date:"2026-08-12",startTime:"10:30",endTime:"12:00",location:"عن بعد",organizer:"نورة العتيبي",internalAttendees:"فريق الابتكار",partnerAttendees:"مختبر النماذج الأولية",agenda:"مراجعة إثبات المفهوم",discussion:"نتائج الاختبار الأولي",decisions:"إعادة الاختبار بعد معالجة الملاحظات",commitments:"إرسال تقرير الاختبار المحدث",minutes:"مسودة قيد الاستكمال",minutesState:"بانتظار المحضر",status:"بانتظار المحضر"},
    {id:"q4",title:"اجتماع متابعة التعاون — الربع الرابع",quarter:"Q4",date:"2026-11-18",startTime:"10:00",endTime:"11:30",location:"مقر الجامعة",organizer:"إدارة الشراكات",internalAttendees:"",partnerAttendees:"",agenda:"مراجعة النتائج وخطة الاستدامة",discussion:"",decisions:"",commitments:"",minutes:"",minutesState:"غير متوفر",status:"مجدول"}],
  commitments:[{id:"c1",title:"تسليم الدراسة المشتركة",description:"نسخة نهائية من الدراسة",source:"اجتماع Q1",responsibility:"مشترك",owner:"د. سارة المطيري",dueDate:"2026-06-30",status:"مكتمل",meetingId:"q1",outputId:"o1"},{id:"c2",title:"تحديث تقرير اختبار إثبات المفهوم",description:"معالجة الملاحظات وإعادة الاختبار",source:"اجتماع Q3",responsibility:"الشريك",owner:"فريق الجامعة",dueDate:"2026-08-18",status:"متأخر",meetingId:"q3",outputId:"o3"}],
  tasks:[{id:"t1",title:"استكمال محضر اجتماع الربع الثالث",description:"توثيق القرارات والالتزامات",assignee:"خالد القحطاني",priority:"HIGH",dueDate:"2026-08-22",status:"OPEN",source:"meeting:q3",section:"meetings",nextAction:"فتح الاجتماع واستكمال المحضر"},{id:"t2",title:"متابعة تقرير الاختبار مع الشريك",description:"استلام النسخة المحدثة",assignee:"د. سارة المطيري",priority:"URGENT",dueDate:"2026-08-18",status:"OVERDUE",source:"commitment:c2",section:"commitments",nextAction:"فتح الالتزام والرد"}],
  outputs:[{id:"o1",name:"دراسة فرص الخدمات الاستباقية",type:"دراسة",description:"دراسة مشتركة تحدد حالات الاستخدام",owner:"فريق البحث المشترك",partner:"جامعة المجمعة",commitmentId:"c1",meetingId:"q2",dueDate:"2026-06-30",completionDate:"2026-06-25",status:"مكتمل",file:"دراسة-الخدمات-الاستباقية.pdf"},{id:"o2",name:"ورشة نقل المعرفة الأولى",type:"نقل معرفة",description:"ورشة تطبيقية للفريق الداخلي",owner:"إدارة الابتكار",partner:"جامعة المجمعة",commitmentId:"c1",meetingId:"q2",dueDate:"2026-07-15",completionDate:"2026-07-12",status:"مكتمل",file:"تقرير-ورشة-نقل-المعرفة.pdf"},{id:"o3",name:"نموذج إثبات مفهوم للخدمة الاستباقية",type:"Proof of Concept",description:"نموذج أولي لاختبار الحالة المختارة",owner:"مختبر الابتكار",partner:"جامعة المجمعة",commitmentId:"c2",meetingId:"q3",dueDate:"2026-10-15",completionDate:"",status:"قيد التنفيذ",file:""}],
  reports:[{id:"r1",title:"تقرير تفعيل التعاون — النصف الأول 2026",period:"يناير–يونيو 2026",cooperationStatus:"نشط",completedCommitments:"1",delayedCommitments:"0",outputsAchieved:"الدراسة وورشة نقل المعرفة",issues:"لا توجد",decisions:"الانتقال إلى إثبات المفهوم",recommendations:"استمرار المتابعة الربعية",correctiveActions:"لا يوجد",responsible:"نورة العتيبي",reviewStatus:"مراجع",approvalStatus:"معتمد",attachment:"تقرير-النصف-الأول.pdf"}],
  decisions:[{id:"d1",title:"اعتماد الدراسة والانتقال لإثبات المفهوم",source:"اجتماع Q2",date:"2026-06-22",owner:"مدير الابتكار",responsible:"مختبر الابتكار",dueDate:"2026-10-15",resultingCommitment:"c2",status:"قيد التنفيذ"}],
  correctiveActions:[{id:"ca1",issue:"تأخر تقرير الاختبار من الشريك",action:"تحديد موعد تسليم محدث ومراجعة أسبوعية",source:"اجتماع Q3",owner:"نورة العتيبي",responsible:"د. سارة المطيري",priority:"عالية",dueDate:"2026-08-25",status:"قيد التنفيذ",result:"",completionDate:"",attachment:""}],
  files:[{id:"f1",title:"محضر اجتماع Q1",category:"محضر",fileName:"minutes-q1.pdf",reviewState:"معتمد",markedAsEvidence:"نعم"},{id:"f2",title:"محضر اجتماع Q2",category:"محضر",fileName:"minutes-q2.pdf",reviewState:"معتمد",markedAsEvidence:"نعم"},{id:"f3",title:"مسودة محضر Q3",category:"محضر",fileName:"minutes-q3-draft.docx",reviewState:"مسودة",markedAsEvidence:"لا"}],
  log:[{date:"2026-08-20T09:00:00.000Z",action:"إنشاء إجراء تصحيحي لتأخر تقرير الشريك",actor:"نورة العتيبي"},{date:"2026-08-12T12:00:00.000Z",action:"تسجيل اجتماع متابعة الربع الثالث",actor:"خالد القحطاني"},{date:"2026-06-25T10:00:00.000Z",action:"توثيق مخرج الدراسة المشتركة",actor:"نورة العتيبي"}]
};

export const PREVIEW_COOPERATION_ACTIVATION:WorkspaceData={cooperationActivations:[activation]};
export function cooperationActivationForPersona(persona?:PreviewPersonaKey):WorkspaceData{
  const row=structuredClone(activation);
  if(persona==="partner"){row.tasks=row.tasks.filter(task=>task.assignee.includes("سارة"));row.log=[];row.files=row.files.filter(file=>file.markedAsEvidence==="نعم");}
  if(persona==="viewer"){row.tasks=[];row.log=[];row.files=[];row.partnerEmail="";}
  return{cooperationActivations:[row]};
}
