import type { WorkspaceData } from "./workspace-status";

export const PREVIEW_ANNUAL_PLAN: WorkspaceData = {
  annualPlan:{year:"2026",name:"الخطة السنوية للابتكار — 2026",owner:"إدارة الابتكار المؤسسي",status:"قيد التنفيذ"},
  activities:[
    {id:"activity-hackathon-2026",name:"هاكاثون المدن المستدامة",activity:"هاكاثون المدن المستدامة",type:"هاكاثون",status:"ONGOING",progress:68,description:"فعالية ابتكار مفتوح لتطوير حلول رقمية لتحديات الاستدامة.",objective:"تطوير نماذج أولية قابلة للتجربة ورفع مشاركة المجتمع الابتكاري.",objectives:"تطوير نماذج أولية قابلة للتجربة ورفع مشاركة المجتمع الابتكاري.",year:"2026",owningDepartment:"إدارة الابتكار المؤسسي",manager:"نورة العتيبي",startDate:"2026-08-20",endDate:"2026-08-29",location:"Hybrid — مركز الابتكار ومنصة الاجتماع",audience:"الموظفون والطلاب والشركات الناشئة",targetAudience:"الموظفون والطلاب والشركات الناشئة",budget:"120000",timeline:"أغسطس 2026",owner:"نورة العتيبي",evaluation:"متابعة يومية ومراجعة المخرجات بعد التحكيم",
      milestones:[{id:"m1",title:"فتح التسجيل",date:"2026-07-20",owner:"فريق التسجيل",status:"مكتملة",description:"فتح النموذج ونشر الإعلان"},{id:"m2",title:"اللقاء التعريفي",date:"2026-08-21",owner:"مدير الفعالية",status:"مكتملة",description:"تعريف المشاركين بالتحديات"},{id:"m3",title:"التسليم النهائي",date:"2026-08-27",owner:"لجنة التحكيم",status:"قيد التنفيذ",description:"يعتمد على اكتمال النماذج"},{id:"m4",title:"إعلان النتائج",date:"2026-08-29",owner:"مدير الفعالية",status:"لم تبدأ",description:"بعد اعتماد نتائج التحكيم"}],
      team:[{id:"team1",name:"نورة العتيبي",department:"إدارة الابتكار",role:"مدير الفعالية",responsibilities:"الإشراف واتخاذ القرارات",userId:"internal"},{id:"team2",name:"خالد القحطاني",department:"إدارة الاتصال",role:"مسؤول التصميم",responsibilities:"الإعلان والمواد البصرية",userId:"admin"},{id:"team3",name:"سارة الحربي",department:"إدارة البرامج",role:"منسقة المشاركين",responsibilities:"التسجيل والحضور"}],
      tasks:[{id:"task1",title:"اعتماد تصميم إعلان الهاكاثون",description:"مراجعة التاريخ والشعارات",assignee:"خالد القحطاني",assignedUserId:"admin",priority:"HIGH",assignedAt:"2026-08-10",dueDate:"2026-08-15",status:"COMPLETED",completedAt:"2026-08-16T09:00:00.000Z",nextAction:"عرض النسخة المعتمدة"},{id:"task2",title:"تأكيد قائمة المرشدين",description:"انتظار رد الجامعة الشريكة",assignee:"نورة العتيبي",assignedUserId:"internal",priority:"URGENT",assignedAt:"2026-08-12",dueDate:"2026-08-17",status:"OVERDUE",nextAction:"متابعة الجهة الشريكة"},{id:"task3",title:"إعداد نموذج تقييم التحكيم",description:"تهيئة النموذج ومراجعته",assignee:"سارة الحربي",priority:"MEDIUM",assignedAt:"2026-08-14",dueDate:"2026-08-25",status:"IN_PROGRESS",nextAction:"إكمال حقول التقييم"}],
      meetings:[{id:"meet1",name:"الاجتماع الافتتاحي للمنظمين",type:"تحضيري",date:"2026-08-10",location:"قاعة الابتكار",organizer:"نورة العتيبي",objective:"اعتماد خطة التنفيذ",decisions:"تثبيت الجدول وتوزيع المسؤوليات"},{id:"meet2",name:"اللقاء التعريفي للمشاركين",type:"تعريفي",date:"2026-08-21",location:"Online",organizer:"سارة الحربي",objective:"شرح التحديات",decisions:"نشر الأسئلة المتكررة"}],
      participants:[{id:"p1",name:"فريق حلول الطاقة",organization:"جامعة المجمعة",category:"فريق مشارك",attendance:"حضر"},{id:"p2",name:"شركة التقنية الخضراء",organization:"قطاع خاص",category:"مرشد",attendance:"مؤكد"}],
      files:[{id:"f1",title:"تصميم إعلان الهاكاثون",category:"تصميم",fileName:"poster-v1.pdf",version:1,reviewState:"يحتاج تعديل",reviewNote:"تعديل التاريخ وإضافة شعار الجهة",markedAsEvidence:"لا"},{id:"f2",title:"تصميم إعلان الهاكاثون",category:"تصميم",fileName:"poster-v2.pdf",version:2,reviewState:"معتمد",markedAsEvidence:"لا"},{id:"f3",title:"الخطة السنوية المحدثة",category:"خطة",fileName:"annual-plan-2026-v3.pdf",version:3,reviewState:"معتمد",markedAsEvidence:"نعم"}],
      deliverables:[{id:"d1",name:"تصميم إعلان الهاكاثون",version:1,reviewState:"أعيد للتعديل",reviewNote:"تعديل التاريخ وإضافة شعار الجهة"},{id:"d2",name:"تصميم إعلان الهاكاثون",version:2,reviewState:"معتمد",reviewNote:"اعتمدت النسخة النهائية"}],
      outputs:[{id:"o1",name:"نماذج أولية للحلول",type:"نماذج أولية",owner:"فرق المشاركين",status:"قيد التنفيذ"},{id:"o2",name:"تقرير نتائج التحكيم",type:"تقرير",owner:"لجنة التحكيم",status:"لم يبدأ"}],
      log:[{date:"2026-08-10T08:00:00.000Z",action:"إنشاء النشاط وتوزيع الفريق"},{date:"2026-08-15T11:00:00.000Z",action:"إعادة تصميم الإعلان للتعديل"},{date:"2026-08-16T09:00:00.000Z",action:"اعتماد الإصدار الثاني وإكمال المهمة"}]},
    {id:"activity-workshop-2026",name:"ورشة الابتكار المؤسسي",activity:"ورشة الابتكار المؤسسي",type:"ورشة عمل",status:"PLANNED",progress:35,description:"ورشة عملية لتطبيق التفكير التصميمي على خدمات الجهة.",objective:"تمكين فرق الخدمات من تعريف المشكلات وبناء حلول أولية.",objectives:"تمكين فرق الخدمات من تعريف المشكلات وبناء حلول أولية.",year:"2026",owningDepartment:"إدارة الابتكار المؤسسي",manager:"سارة الحربي",startDate:"2026-09-10",endDate:"2026-09-10",location:"قاعة التدريب",audience:"فرق الخدمات الرقمية",targetAudience:"فرق الخدمات الرقمية",budget:"25000",timeline:"سبتمبر 2026",owner:"سارة الحربي",evaluation:"نموذج تقييم بعد الورشة",
      milestones:[{id:"wm1",title:"اعتماد الإعلان",date:"2026-08-25",owner:"إدارة الاتصال",status:"قيد التنفيذ",description:"موعد قريب"},{id:"wm2",title:"تنفيذ الورشة",date:"2026-09-10",owner:"سارة الحربي",status:"لم تبدأ",description:""}],team:[{id:"wt1",name:"سارة الحربي",department:"إدارة الابتكار",role:"مديرة الورشة",responsibilities:"الإعداد والتنفيذ",userId:"internal"},{id:"wt2",name:"خالد القحطاني",department:"إدارة الاتصال",role:"مسؤول الإعلان",responsibilities:"التصميم والنشر",userId:"admin"}],tasks:[{id:"wtask1",title:"تصميم إعلان ورشة الابتكار",description:"إعداد النسخة الأولى",assignee:"خالد القحطاني",assignedUserId:"admin",priority:"HIGH",assignedAt:"2026-08-19",dueDate:"2026-08-25",status:"REVIEW",nextAction:"مراجعة التصميم"},{id:"wtask2",title:"تأكيد قائمة الحضور",description:"التواصل مع الإدارات",assignee:"سارة الحربي",assignedUserId:"internal",priority:"MEDIUM",assignedAt:"2026-08-19",dueDate:"2026-09-03",status:"NOT_STARTED",nextAction:"بدء التواصل"}],meetings:[{id:"wmeet1",name:"اجتماع التحضير للورشة",type:"تحضيري",date:"2026-08-22",location:"Online",organizer:"سارة الحربي",objective:"مراجعة المحتوى",decisions:"استكمال العرض والإعلان"}],participants:[{id:"wp1",name:"ممثل إدارة الخدمات",organization:"إدارة الخدمات الرقمية",category:"مشارك",attendance:"مسجل"}],files:[{id:"wf1",title:"إعلان الورشة",category:"تصميم",fileName:"workshop-poster-v1.pdf",version:1,reviewState:"قيد المراجعة",markedAsEvidence:"لا"}],deliverables:[{id:"wd1",name:"تصميم إعلان الورشة",version:1,reviewState:"قيد المراجعة"}],outputs:[],log:[{date:"2026-08-19T09:00:00.000Z",action:"إنشاء نشاط الورشة وإسناد مهام التحضير"}]}
  ]
};

export function annualPlanForPersona(persona?:string):WorkspaceData {
  const copy=structuredClone(PREVIEW_ANNUAL_PLAN);const activities=(copy.activities as Record<string,unknown>[])??[];
  if(persona==="partner")copy.activities=activities.slice(0,1).map(activity=>({...activity,participants:[],log:[],files:((activity.files as Record<string,unknown>[])??[]).filter(file=>file.markedAsEvidence==="نعم"),tasks:((activity.tasks as Record<string,unknown>[])??[]).filter(task=>task.id==="task3")}));
  if(persona==="viewer")copy.activities=activities.map(activity=>({...activity,participants:[],files:[],log:[],tasks:[],team:[]}));
  return copy;
}
