import type { WorkspaceData } from "./workspace-status";
export const PREVIEW_WORKSPACE_DATA:Record<string,WorkspaceData>={
"5-23-1-r1":{innovationAreas:[{name:"الخدمات الرقمية الاستباقية",description:"تحليل البيانات والأتمتة لتقديم خدمات استباقية للمستفيدين",rationale:"رفع كفاءة الخدمات وتقليل الجهد على المستفيد",strategicPriorityLink:"يرتبط بأولوية تحسين تجربة المستفيد",ownerEntity:"إدارة الابتكار والتحول الرقمي",participatingDepartments:"تقنية المعلومات، البيانات"}],strategicGoals:[{name:"رفع نسبة المبادرات الابتكارية الرقمية المرتبطة بالأهداف الاستراتيجية",description:"مواءمة مبادرات الابتكار مع أهداف الجهة",entityGoalLink:"هدف الجهة في تقديم خدمات رقمية موثوقة",digitalTransformationLink:"محور الابتكار في استراتيجية التحول الرقمي",owner:"مدير الاستراتيجية والابتكار",startDate:"2026-01-01",endDate:"2026-12-31"}],kpis:[{name:"نسبة المبادرات الابتكارية المرتبطة بأهداف التحول الرقمي",definition:"نسبة المبادرات المرتبطة رسميًا بهدف في استراتيجية التحول الرقمي",calculationMethod:"عدد المبادرات المرتبطة ÷ إجمالي المبادرات ×100",baseline:"60%",target:"90%",measurementFrequency:"ربع سنوي",dataSource:"سجل المبادرات في المنصة",owner:"مدير الاستراتيجية والابتكار"}],alignment:{entityAlignment:"يرتبط بهدف الجهة في تقديم خدمات رقمية موثوقة"}},
"5-23-1-r2":{initiatives:[{name:"مختبر تحسين رحلة المستفيد",description:"اختبار حلول رقمية تقلل خطوات وزمن الحصول على الخدمة",owningDepartment:"إدارة تجربة المستفيد",owner:"نورة العتيبي",status:"مكتملة البيانات",startDate:"2026-01-15",targetDate:"2026-09-30",lastUpdate:"2026-08-18"},{name:"منصة التجارب الرقمية",description:"بيئة مؤسسية لتجربة النماذج الأولية قبل التوسع",owningDepartment:"إدارة التحول الرقمي",owner:"خالد القحطاني",status:"قيد الاستكمال",startDate:"2026-03-01",targetDate:"2026-12-15",lastUpdate:"2026-08-17"},{name:"برنامج الخدمات الاستباقية",description:"تطوير حالات استخدام مبنية على البيانات لخدمات استباقية",owningDepartment:"إدارة البيانات",owner:"سارة الحربي",status:"بانتظار المؤشر والإثبات",startDate:"2026-05-01",targetDate:"2027-01-31",lastUpdate:"2026-08-16"}],strategicAlignment:[{initiativeName:"مختبر تحسين رحلة المستفيد",strategicObjective:"رفع نسبة المبادرات الابتكارية الرقمية المرتبطة بالأهداف الاستراتيجية",alignmentReason:"يدعم تحسين جودة الخدمات الرقمية وتجربة المستفيد"},{initiativeName:"منصة التجارب الرقمية",strategicObjective:"رفع نسبة المبادرات الابتكارية الرقمية المرتبطة بالأهداف الاستراتيجية",alignmentReason:"تربط التجارب الرقمية بمحور الابتكار في استراتيجية التحول الرقمي"}],initiativeKpis:[{initiativeName:"مختبر تحسين رحلة المستفيد",kpiName:"نسبة المبادرات الابتكارية المرتبطة بأهداف التحول الرقمي",initiativeTarget:"إكمال تجربتين مرتبطتين خلال 2026",owner:"إدارة تجربة المستفيد"}]},
"5-23-1-r3":{cooperations:[{entity:"جامعة وطنية",scope:"تطوير نماذج أولية وبحث تطبيقي",startDate:"2026-01-15",endDate:"2026-12-31",owner:"إدارة الشراكات",outputs:"نموذجان أوليان وبرنامج نقل معرفة",agreementStatus:"سارية"}]},
"5-23-2-r1":{activities:[{activity:"هاكاثون المدن المستدامة",objectives:"توليد حلول رقمية لتحديات الاستدامة",outputs:"نماذج أولية ومشروعات مرشحة",timeline:"الربع الثالث 2026",owner:"مدير البرامج",evaluation:"متابعة شهرية وقياس جودة النماذج"}]},
"5-23-2-r2":{application:{methodology:"التفكير التصميمي",application:"مقابلات مستفيدين ثم تعريف المشكلة وتوليد الحلول",participants:"فريق الابتكار وممثلو الخدمات",challenges:"تعدد خطوات الوصول للخدمة",solutions:"مساعد رقمي موحد",prototypes:"نموذج تفاعلي أولي",prototypeStages:"اختبار أولي ثم تحسين الرحلة",projects:"مشروع المساعد الرقمي",kpis:"معدل إكمال الرحلة",impact:"تقليل زمن البحث"},brainstormingSessions:[{date:"2026-05-12",topic:"تبسيط رحلة المستفيد",participants:"12 مشاركًا",outputs:"18 فكرة أولية"},{date:"2026-06-03",topic:"اختيار الحلول القابلة للتجربة",participants:"9 مشاركين",outputs:"3 نماذج مرشحة"}]},
"5-23-2-r3":{events:[{eventType:"هاكاثون",eventInfo:"هاكاثون المدن المستدامة 2026",challenges:"كفاءة الطاقة",solutions:"حلول تنبؤية",participantCount:84,participantCategories:"موظفون وطلاب وشركات ناشئة",winners:"نظام التنبؤ باستهلاك الطاقة",certificateSamples:"نماذج شهادات المشاركين",prototypes:"ثلاثة نماذج أولية",implementedProjects:"حل واحد في تجربة محدودة",impact:"تسريع الوصول إلى حلول قابلة للاختبار"}]},
"5-23-2-r4":{activation:{agreement:"اتفاقية التعاون البحثي 2026",outputs:"برنامج نقل معرفة ونموذج أولي",progressReports:"تقرير الربع الأول والثاني",decisions:"الاستمرار في التجربة",correctiveActions:"تحديث جدول التسليم"},meetings:[{date:"2026-01-20",minutes:"مراجعة خطة العمل",outputs:"اعتماد الأولويات"},{date:"2026-04-20",minutes:"متابعة التقدم",outputs:"تحديث الجدول"},{date:"2026-07-20",minutes:"عرض النموذج",outputs:"ملاحظات التحسين"},{date:"2026-10-20",minutes:"مراجعة النتائج",outputs:"قرار التوسع"}]},
"5-23-3-r1":{formation:{name:"لجنة حوكمة الابتكار",organizationalPlacement:"مرتبطة بوكالة التحول الرقمي"},members:[{member:"مدير إدارة الابتكار",role:"رئيس اللجنة",responsibilities:"اعتماد الأولويات ومتابعة الأداء"},{member:"ممثل الاستراتيجية",role:"عضو",responsibilities:"مواءمة المبادرات مع أهداف الجهة"}]},
"5-23-3-r2":{activation:{procedures:"إجراء استقبال ومراجعة السجلات الابتكارية",policies:"سياسة إدارة الابتكار المؤسسي",reviewRecords:"سجل مراجعة شهري",projectCards:"بطاقات المبادرات المعتمدة",performanceReports:"تقرير أداء ربع سنوي",decisions:"تجربة الحلول الأعلى أولوية",correctiveActions:"استكمال مؤشرات القياس الناقصة"}},
"5-23-3-r3":{cultureActivities:[{name:"أسبوع الابتكار",type:"توعية",date:"2026-02-15",audience:"موظفو الجهة",attendance:160,objective:"رفع الوعي",result:"34 مقترحًا"},{name:"ورشة التفكير التصميمي",type:"تدريب",date:"2026-04-10",audience:"فرق الخدمات",attendance:28,objective:"تطبيق المنهجية",result:"نموذجان أوليان"},{name:"جلسة نقل المعرفة",type:"معرفة",date:"2026-06-22",audience:"مجتمع الابتكار",attendance:45,objective:"مشاركة النتائج",result:"دليل ممارسات"}]},
"5-23-3-r4":{mechanism:{framework:"إطار إدارة الابتكار الرقمي المعتمد",ideaDesign:"استقبال الفرصة وتعريف المشكلة والتصميم",development:"تطوير النموذج الأولي واختباره",implementation:"تجربة الحل ومتابعة التنفيذ"}},
"5-23-3-r5":{mechanism:{proposalReceiving:"نموذج إلكتروني موحد لاستقبال المقترحات",feedbackReceiving:"استبيان آلي مرتبط بالحلول المطورة",sourceAudience:"الموظفون والمستفيدون والشركاء"}}
};
