import type { WorkspaceData } from "./workspace-status";

export const PREVIEW_COMMITTEE: WorkspaceData = {
  structures: [
    {
      id: "structure-innovation-committee",
      committeeId: "preview-committee-innovation",
      name: "لجنة الابتكار المؤسسي",
      type: "لجنة",
      purpose: "تعزيز الابتكار وتبنيه مؤسسيًا ومتابعة تنفيذ مبادراته.",
      mandateDescription: "اعتماد أولويات الابتكار، ومتابعة أداء المبادرات، واعتماد التوصيات المرفوعة من فرق العمل.",
      relatedDepartmentName: "إدارة الابتكار والتحول الرقمي",
      chairName: "مدير إدارة الابتكار والتحول الرقمي",
      secretaryName: "منسقة أمانة اللجنة",
      formationDate: "2026-02-01",
      operationStartDate: "2026-02-15",
      meetingFrequency: "شهرية",
      notes: "أول لجنة مؤسسية معتمدة لدعم الابتكار.",
      status: "نشطة",
      decisionNumber: "INN-2026-004",
      decisionDate: "2026-01-28",
      decisionApprovingAuthority: "صاحب الصلاحية المفوّض",
      decisionEffectiveDate: "2026-02-01",
      decisionNotes: "اعتُمد القرار ضمن اجتماع الإدارة العليا.",
      members: [
        {
          id: "member-chair",
          name: "نورة العتيبي",
          category: "موظف",
          affiliation: "إدارة الابتكار والتحول الرقمي",
          title: "مدير إدارة الابتكار",
          email: "noura@example.gov.sa",
          phone: "",
          roleInCommittee: "رئيس اللجنة",
          responsibilities: "اعتماد الأولويات ومتابعة الأداء العام للجنة.",
          responsibilityScope: "الإشراف الكامل على أعمال اللجنة وقراراتها.",
          isPrimaryResponsible: "نعم",
          delegateName: "خالد القحطاني",
          joinDate: "2026-02-01",
          membershipEndDate: "",
          status: "نشط",
          notes: "",
        },
        {
          id: "member-dept-rep",
          name: "خالد القحطاني",
          category: "ممثل إدارة",
          affiliation: "إدارة الاستراتيجية والتخطيط",
          title: "ممثل إدارة الاستراتيجية",
          email: "khalid@example.gov.sa",
          phone: "0500000000",
          roleInCommittee: "نائب الرئيس",
          responsibilities: "مواءمة مبادرات الابتكار مع أهداف الجهة الاستراتيجية.",
          responsibilityScope: "التنسيق بين اللجنة وإدارة الاستراتيجية.",
          isPrimaryResponsible: "لا",
          delegateName: "",
          joinDate: "2026-02-01",
          membershipEndDate: "",
          status: "نشط",
          notes: "",
        },
        {
          id: "member-expert",
          name: "د. سارة الحربي",
          category: "خبير",
          affiliation: "استشارية ابتكار مستقلة",
          title: "خبيرة منهجيات الابتكار",
          email: "s.alharbi@example.com",
          phone: "",
          roleInCommittee: "عضو",
          responsibilities: "تقديم المشورة الفنية حول منهجيات الابتكار المطبّقة.",
          responsibilityScope: "استشارات فنية عند مراجعة المبادرات.",
          isPrimaryResponsible: "لا",
          delegateName: "",
          joinDate: "2026-02-10",
          membershipEndDate: "",
          status: "نشط",
          notes: "عضوة غير متفرغة — حضور حسب الحاجة.",
        },
        {
          id: "member-volunteer",
          name: "عبدالله الزهراني",
          category: "طالب متطوع",
          affiliation: "جامعة الملك سعود",
          title: "طالب هندسة برمجيات",
          email: "abdullah@example.edu.sa",
          phone: "",
          roleInCommittee: "عضو داعم",
          responsibilities: "دعم توثيق محاضر الاجتماعات ومتابعة المهام التنفيذية.",
          responsibilityScope: "مهام تنفيذية داعمة دون صلاحيات اعتماد.",
          isPrimaryResponsible: "لا",
          delegateName: "",
          joinDate: "2026-03-01",
          membershipEndDate: "2026-12-31",
          status: "نشط",
          notes: "عضوية تطوعية محدودة بمدة الفصل الدراسي — بلا دخول للمنصة.",
        },
      ],
      tasks: [
        {
          id: "task-formation-decision",
          title: "إعداد قرار التشكيل ورفعه للاعتماد",
          description: "صياغة قرار التشكيل الرسمي وربطه بمحضر الاجتماع التأسيسي.",
          assignee: "نورة العتيبي",
          assignedUserId: "internal",
          priority: "HIGH",
          assignedAt: "2026-01-20",
          dueDate: "2026-01-27",
          status: "COMPLETED",
          completedAt: "2026-01-28T10:00:00.000Z",
          nextAction: "أرشفة القرار المعتمد",
        },
        {
          id: "task-update-responsibilities",
          title: "تحديث مسؤوليات اللجنة بعد ضم العضو الجديد",
          description: "مراجعة نطاق مسؤولية كل عضو بعد انضمام العضو الخبير.",
          assignee: "خالد القحطاني",
          assignedUserId: "admin",
          priority: "MEDIUM",
          assignedAt: "2026-08-15",
          dueDate: "2026-08-25",
          status: "IN_PROGRESS",
          completedAt: null,
          nextAction: "استكمال مراجعة نطاق المسؤوليات",
        },
      ],
      log: [
        { date: "2026-01-20T09:00:00.000Z", action: "إنشاء مسودة اللجنة وتحديد الأعضاء المؤسسين" },
        { date: "2026-01-28T10:00:00.000Z", action: "اعتماد قرار التشكيل وإكمال مهمة الإعداد" },
        { date: "2026-08-15T08:00:00.000Z", action: "إسناد مهمة تحديث مسؤوليات اللجنة" },
      ],
    },
  ],
};

export function committeeForPersona(persona?: string): WorkspaceData {
  const copy = structuredClone(PREVIEW_COMMITTEE);
  const structures = (copy.structures as Record<string, unknown>[]) ?? [];
  if (persona === "partner") {
    copy.structures = structures.map((structure) => ({
      ...structure,
      members: ((structure.members as Record<string, unknown>[]) ?? []).map((member) => ({ ...member, email: "", phone: "" })),
      tasks: [],
      log: [],
    }));
  }
  if (persona === "viewer") {
    copy.structures = structures.map((structure) => ({
      ...structure,
      members: ((structure.members as Record<string, unknown>[]) ?? []).map((member) => ({ ...member, email: "", phone: "" })),
      tasks: [],
      log: [],
    }));
  }
  return copy;
}
