import type { WorkspaceData } from "./workspace-status";

export const PREVIEW_METHODOLOGY_WORKSPACE:WorkspaceData={
  application:{methodology:"التفكير التصميمي والعصف الذهني",application:"حالتان موثقتان لتطبيق منهجيات الابتكار على تحديات فعلية",participants:"فرق الخدمات والموارد البشرية",challenges:"تحسين تجربة خدمة رقمية وإجراء داخلي",solutions:"حلول مرتبطة بجلساتها",prototypes:"نموذج تفاعلي بإصدارين",prototypeStages:"اختبار ثم تحسين",projects:"مبادرة تحسين رحلة المستفيد",kpis:"معدل إكمال الرحلة",impact:"تقليل زمن الوصول للخدمة"},
  brainstormingSessions:[{date:"2026-06-03",topic:"توليد حلول رحلة المستفيد",methodology:"العصف الذهني",owningDepartment:"إدارة الخدمات الرقمية",facilitator:"نورة العتيبي",participants:"12 مشاركًا",outputs:"18 فكرة"},{date:"2026-08-12",topic:"تبسيط إجراء الموافقات الداخلية",methodology:"العصف الذهني",owningDepartment:"إدارة الموارد البشرية",facilitator:"سارة الحربي",participants:"9 مشاركين",outputs:"7 مقترحات"}],
  methodologyCases:[
    {id:"case-digital-service",name:"تحسين رحلة تسجيل المستفيد",description:"تطبيق منهجية عملية لتحسين تجربة التسجيل في الخدمة الرقمية.",challengeTitle:"تعدد خطوات تسجيل المستفيد",challengeDescription:"يتنقل المستفيد بين شاشات متعددة ولا يعرف متطلبات الإكمال.",department:"إدارة الخدمات الرقمية",responsible:"نورة العتيبي",responsibleUserId:"internal",startDate:"2026-05-01",endDate:"2026-07-30",status:"COMPLETED",objective:"تبسيط الرحلة ورفع معدل الإكمال",methodology:"التفكير التصميمي",selectionReason:"الحاجة لفهم تجربة المستفيد واختبار الحل",applicationMethod:"بحث المستخدم، تعريف المشكلة، توليد الحلول، نموذج أولي واختبار",facilitator:"نورة العتيبي",result:"اعتماد رحلة مبسطة ونموذج تفاعلي محدث",
      sessions:[{id:"s1",name:"جلسة تعريف المشكلة",type:"تعريف المشكلة",methodology:"التفكير التصميمي",date:"2026-05-12",startTime:"10:00",endTime:"12:00",location:"مختبر الابتكار",facilitator:"نورة العتيبي",objective:"صياغة المشكلة",challenge:"تعدد خطوات التسجيل",attendance:"10",notes:"تم تحديد نقاط التعثر",results:"صياغة تحدٍ موحد"},{id:"s2",name:"جلسة العصف الذهني للحلول",type:"عصف ذهني",methodology:"العصف الذهني",date:"2026-06-03",startTime:"09:00",endTime:"12:00",location:"قاعة الابتكار",facilitator:"نورة العتيبي",objective:"توليد حلول",challenge:"رحلة التسجيل",attendance:"12",notes:"",results:"18 فكرة و3 حلول مرشحة"},{id:"s3",name:"اختبار النموذج",type:"اختبار نموذج",methodology:"التفكير التصميمي",date:"2026-07-10",startTime:"11:00",endTime:"13:00",location:"Online",facilitator:"سارة الحربي",objective:"اختبار قابلية الاستخدام",challenge:"وضوح خطوات التسجيل",attendance:"6",notes:"تعديل لغة الأزرار",results:"اعتماد تحسينات الإصدار الثاني"}],
      participants:[{id:"p1",name:"ريم القحطاني",organization:"إدارة الخدمات الرقمية",role:"ممثل إدارة",category:"موظف",attendance:"حضر",sessions:"s1,s2"},{id:"p2",name:"مشارك مستفيد",organization:"عينة مستفيدين",role:"مستخدم",category:"مستفيد",attendance:"حضر",sessions:"s3"}],
      tasks:[{id:"t1",title:"إعداد تحديات جلسة العصف الذهني",description:"تهيئة لوحة العمل",sessionId:"s2",assignee:"نورة العتيبي",assignedUserId:"internal",priority:"HIGH",assignedAt:"2026-05-25",dueDate:"2026-06-01",status:"COMPLETED",completedAt:"2026-06-01T09:00:00Z"}],
      solutions:[{id:"sol1",title:"مسار تسجيل موحد",description:"دمج الخطوات في رحلة واحدة",challenge:"تعدد خطوات التسجيل",sessionId:"s2",contributors:"فريق الجلسة",status:"مختار للاختبار"},{id:"sol2",title:"قائمة تحقق ديناميكية",description:"إظهار المتطلبات قبل البدء",challenge:"عدم وضوح المتطلبات",sessionId:"s2",contributors:"فريق الخدمات",status:"موثق"}],
      prototypes:[{id:"proto1",name:"نموذج رحلة التسجيل",solutionId:"sol1",description:"نموذج تفاعلي للشاشات المقترحة",type:"نموذج واجهة",owner:"فريق تجربة المستفيد",startDate:"2026-06-15",status:"مكتمل",result:"تحسن وضوح الخطوات",stages:[{id:"st1",name:"Prototype v1",date:"2026-06-20",development:"بناء التدفق الأولي",change:"نسخة أولى",result:"احتاجت لغة أوضح",owner:"فريق التصميم",file:"journey-v1.fig"},{id:"st2",name:"Prototype v2",date:"2026-07-15",development:"تطبيق نتائج الاختبار",change:"تعديل الأزرار وترتيب الخطوات",result:"اعتمد للاستخدام التجريبي",owner:"فريق التصميم",file:"journey-v2.fig"}]}],
      projects:[{id:"pr1",name:"مبادرة تحسين رحلة المستفيد",solutionId:"sol1",department:"إدارة الخدمات الرقمية",owner:"نورة العتيبي",status:"قيد التنفيذ",startDate:"2026-08-01",description:"تنفيذ الرحلة المحسنة",linkedInitiative:"مختبر تحسين رحلة المستفيد"}],
      indicators:[{id:"k1",name:"معدل إكمال رحلة التسجيل",owner:"إدارة الخدمات الرقمية",baseline:"62%",target:"80%",result:"74% تجريبي",period:"الربع الثالث 2026",impact:"تقليل الانقطاع أثناء التسجيل"}],files:[{id:"f1",title:"توثيق تطبيق التفكير التصميمي",category:"دليل منهجية",fileName:"design-thinking-case.pdf",version:1,markedAsEvidence:"نعم"}],log:[{date:"2026-05-01",action:"إنشاء حالة تطبيق المنهجية"},{date:"2026-06-03",action:"إكمال جلسة العصف الذهني وتسجيل الحلول"},{date:"2026-07-15",action:"توثيق الإصدار الثاني للنموذج"}]},
    {id:"case-internal-process",name:"تبسيط إجراء الموافقات الداخلية",description:"جلسة عملية لتقليل زمن انتقال الطلب بين الإدارات.",challengeTitle:"طول دورة الموافقات",challengeDescription:"تتكرر المراجعة اليدوية بين ثلاث إدارات.",department:"إدارة الموارد البشرية",responsible:"سارة الحربي",responsibleUserId:"admin",startDate:"2026-08-01",endDate:"2026-09-15",status:"IN_PROGRESS",objective:"تقليل نقاط الانتظار",methodology:"العصف الذهني",selectionReason:"الحاجة لتوليد بدائل سريعة بمشاركة الإدارات",applicationMethod:"تجهيز السياق، جلسة عصف، تجميع المقترحات واختيار أولويات المتابعة",facilitator:"سارة الحربي",result:"قيد المتابعة",
      sessions:[{id:"s4",name:"جلسة عصف ذهني للإجراء الداخلي",type:"عصف ذهني",methodology:"العصف الذهني",date:"2026-08-12",startTime:"10:00",endTime:"12:00",location:"قاعة الاجتماعات",facilitator:"سارة الحربي",objective:"اقتراح مسارات مختصرة",challenge:"طول دورة الموافقات",attendance:"9",notes:"تحتاج بعض المقترحات رأي الإدارة القانونية",results:"7 مقترحات وحلان مرشحان"}],participants:[{id:"p3",name:"ممثل الموارد البشرية",organization:"إدارة الموارد البشرية",role:"مالك الإجراء",category:"ممثل إدارة",attendance:"حضر",sessions:"s4"}],tasks:[{id:"t2",title:"توثيق نتائج جلسة الإجراء الداخلي",description:"استكمال القرارات وملاك الإجراءات",sessionId:"s4",assignee:"سارة الحربي",assignedUserId:"admin",priority:"URGENT",assignedAt:"2026-08-12",dueDate:"2026-08-18",status:"IN_PROGRESS"}],solutions:[{id:"sol3",title:"مسار موافقة موحد",description:"بوابة واحدة لتجميع الموافقات",challenge:"طول دورة الموافقات",sessionId:"s4",contributors:"ممثلو الإدارات",status:"قيد الدراسة"}],prototypes:[],projects:[],indicators:[],files:[],log:[{date:"2026-08-01",action:"إنشاء الحالة"},{date:"2026-08-12",action:"توثيق جلسة العصف الذهني"}]}
  ]
};

export function methodologyForPersona(persona?:string):WorkspaceData{const copy=structuredClone(PREVIEW_METHODOLOGY_WORKSPACE);const cases=(copy.methodologyCases as Record<string,unknown>[])??[];if(persona==="partner")copy.methodologyCases=cases.slice(0,1).map(item=>({...item,participants:[],log:[],tasks:[],files:[]}));if(persona==="viewer")copy.methodologyCases=cases.map(item=>({...item,participants:[],log:[],tasks:[],files:[]}));return copy;}
