import type {WorkspaceData} from "./workspace-status";

const participants=Array.from({length:84},(_,index)=>({id:`participant-${index+1}`,name:`مشارك ${String(index+1).padStart(2,"0")}`,category:index<28?"طالب":index<56?"موظف":"شركة ناشئة",organization:index%3===0?"جامعة المجمعة":index%3===1?"الجهة الحكومية":"شركة تقنية",department:index%3===1?"الخدمات الرقمية":"—",teamId:`team-${(index%21)+1}`,status:"مؤكد",attendance:index<78?"حضر":"مسجل"}));
const teams=Array.from({length:21},(_,index)=>({id:`team-${index+1}`,name:`فريق الابتكار ${index+1}`,lead:`قائد الفريق ${index+1}`,memberIds:participants.filter(p=>p.teamId===`team-${index+1}`).map(p=>p.id),challengeId:`challenge-${(index%12)+1}`,solutionId:index<18?`solution-${index+1}`:"",status:index<18?"قدم حلاً":"قيد التطوير"}));
const challenges=Array.from({length:12},(_,index)=>({id:`challenge-${index+1}`,title:index===0?"خفض استهلاك الطاقة في المباني الحكومية":`تحدي الاستدامة ${index+1}`,description:"تحدٍ مؤسسي مطروح للفرق المشاركة ضمن نطاق الفعالية.",owner:`مالك التحدي ${index+1}`,entity:index%2?"إدارة المرافق":"إدارة الخدمات الرقمية",category:index%2?"الطاقة":"الخدمات",beneficiaryGroup:"المستفيدون وفرق التشغيل",problemStatement:"الحاجة إلى حل قابل للتجربة يحسن الكفاءة ويقيس النتيجة.",status:index<9?"مفتوح للمشاركات":"مغلق"}));
const solutions=Array.from({length:18},(_,index)=>({id:`solution-${index+1}`,name:index===0?"منصة التنبؤ الذكي بالطاقة":`حل الاستدامة ${index+1}`,challengeId:`challenge-${(index%12)+1}`,teamId:`team-${index+1}`,summary:"حل مقدم ضمن الهاكاثون لمعالجة التحدي المرتبط.",submittedAt:"2026-08-27",version:"1",status:index<6?"انتقل للنموذج الأولي":"تم التحكيم",prototypeId:index<6?`prototype-${index+1}`:"",judgingStatus:"مكتمل",winnerStatus:index<3?"فائز":"غير فائز",projectId:index<2?`project-${index+1}`:""}));
const prototypes=Array.from({length:6},(_,index)=>({id:`prototype-${index+1}`,name:`نموذج أولي ${index+1}`,solutionId:`solution-${index+1}`,version:"2",stage:index<3?"نموذج نهائي":"اختبار",owner:`فريق الابتكار ${index+1}`,date:"2026-08-28",testingSummary:"اختبار السيناريو الأساسي مع عينة من المستفيدين.",feedback:"تبسيط الواجهة وتحسين وضوح النتائج.",result:"جاهز للعرض",state:index<3?"مكتمل":"قيد التطوير",versions:[{id:`pv-${index+1}-1`,version:"1",stage:"بناء",date:"2026-08-25",result:"نسخة أولية"},{id:`pv-${index+1}-2`,version:"2",stage:"اختبار",date:"2026-08-28",result:"نسخة محسنة"}]}));

export const PREVIEW_OPEN_INNOVATION:WorkspaceData={openInnovationEvents:[{
  id:"sustainable-cities-2026",name:"هاكاثون المدن المستدامة 2026",type:"هاكاثون",description:"فعالية ابتكار مفتوح لتطوير حلول رقمية قابلة للتجربة لتحديات الاستدامة.",objective:"إشراك المستفيدين والجامعات والشركات الناشئة في تطوير نماذج أولية.",beneficiaryGroups:"الموظفون، الطلاب، الشركات الناشئة، فرق التشغيل",approach:"هاكاثون قائم على تحديات مؤسسية وإرشاد متخصص",owner:"إدارة الابتكار المؤسسي",department:"إدارة الابتكار",responsible:"نورة العتيبي",startDate:"2026-08-20",endDate:"2026-08-29",location:"مركز الابتكار",deliveryMode:"هجين",status:"قيد التوثيق",annualPlanActivityId:"activity-hackathon-2026",annualPlanActivityName:"هاكاثون المدن المستدامة",documentationProgress:87,evidenceReadiness:67,
  timeline:[{id:"time-1",name:"الجلسة الافتتاحية",type:"جلسة افتتاح",date:"2026-08-20T09:00",owner:"مدير الفعالية",responsible:"نورة العتيبي",status:"مكتملة",description:"شرح التحديات وقواعد المشاركة",followUp:"نشر العرض والأسئلة المتكررة"},{id:"time-2",name:"موعد تسليم الحلول",type:"موعد نهائي",date:"2026-08-27T18:00",owner:"لجنة التنظيم",responsible:"سارة الحربي",status:"مكتملة",description:"إغلاق استقبال المشاركات",followUp:"تهيئة ملفات التحكيم"},{id:"time-3",name:"جلسة العرض والتحكيم",type:"عرض وتحكيم",date:"2026-08-28T10:00",owner:"لجنة التحكيم",responsible:"خالد القحطاني",status:"مكتملة",description:"عرض النماذج أمام اللجنة",followUp:"اعتماد النتائج"}],
  challenges,participants,teams,solutions,
  judges:[{id:"judge-1",name:"د. ريم الشهري",organization:"جامعة المجمعة",role:"رئيسة لجنة التحكيم"},{id:"judge-2",name:"م. خالد القحطاني",organization:"الجهة الحكومية",role:"محكم تقني"},{id:"judge-3",name:"أ. سارة الحربي",organization:"قطاع التقنية",role:"محكمة تجربة مستفيد"}],
  judging:[{id:"judging-1",solutionId:"solution-1",round:"النهائية",criteria:"الأثر، القابلية للتنفيذ، الابتكار",score:"94",comments:"حل متكامل وقابل للتجربة",ranking:"1"},{id:"judging-2",solutionId:"solution-2",round:"النهائية",criteria:"الأثر، القابلية للتنفيذ، الابتكار",score:"91",comments:"نموذج واضح",ranking:"2"},{id:"judging-3",solutionId:"solution-3",round:"النهائية",criteria:"الأثر، القابلية للتنفيذ، الابتكار",score:"88",comments:"قيمة جيدة للمستفيد",ranking:"3"}],
  winners:[{id:"winner-1",solutionId:"solution-1",category:"المركز الأول",ranking:"1",decision:"معتمد داخليًا"},{id:"winner-2",solutionId:"solution-2",category:"المركز الثاني",ranking:"2",decision:"معتمد داخليًا"},{id:"winner-3",solutionId:"solution-3",category:"جائزة تجربة المستفيد",ranking:"3",decision:"معتمد داخليًا"}],prototypes,
  projects:[{id:"project-1",solutionId:"solution-1",name:"مشروع إدارة الطاقة التنبؤية",owner:"إدارة المرافق",department:"إدارة المرافق",implementationState:"تجربة محدودة",startDate:"2026-09-15",status:"قيد التنفيذ",impactLink:"impact-1"},{id:"project-2",solutionId:"solution-2",name:"مشروع متابعة الاستدامة",owner:"إدارة البيانات",department:"إدارة البيانات",implementationState:"تخطيط التجربة",startDate:"2026-10-01",status:"مخطط",impactLink:"impact-2"}],
  impacts:[{id:"impact-1",projectId:"project-1",beneficiaries:"فرق تشغيل المباني",adoptionState:"تجربة في مبنيين",outcome:"خفض متوقع في الاستهلاك",kpi:"نسبة خفض استهلاك الطاقة",measurement:"8% في الشهر الأول",formalImpactLink:"5.24.2 — نظام إدارة الطاقة"}],
  files:[{id:"file-1",title:"دليل المشاركين",category:"قائمة مشاركين",fileName:"participants-v2.xlsx",version:2,reviewState:"معتمد داخليًا",markedAsEvidence:"لا"},{id:"file-2",title:"نتائج التحكيم",category:"تحكيم",fileName:"judging-results.pdf",version:1,reviewState:"قيد المراجعة",markedAsEvidence:"لا"},{id:"file-3",title:"نموذج شهادة مشارك",category:"شهادة",fileName:"participant-certificate.pdf",version:1,reviewState:"معتمد داخليًا",markedAsEvidence:"لا"},{id:"file-4",title:"التقرير الختامي",category:"تقرير",fileName:"hackathon-final-report.pdf",version:1,reviewState:"مسودة",markedAsEvidence:"نعم"}],
  documentationSamples:[{id:"sample-1",type:"التحديات والحلول",recordId:"challenge-1",fileId:"file-4",status:"مكتملة"},{id:"sample-2",type:"المشاركون والشهادات",recordId:"participant-1",fileId:"file-3",status:"مكتملة"},{id:"sample-3",type:"التحكيم والفائزون",recordId:"winner-1",fileId:"file-2",status:"قيد المراجعة"}],
  tasks:[{id:"event-task-1",title:"استكمال سجل المشاركين",description:"مراجعة بيانات الحضور",assignedUserId:"internal",assignee:"محرر الابتكار الداخلي",priority:"HIGH",assignedAt:"2026-08-18",dueDate:"2026-08-22",status:"IN_PROGRESS",section:"participants",nextAction:"فتح قسم المشاركين والفرق"},{id:"event-task-2",title:"رفع نتائج التحكيم",description:"ربط النتائج بالحلول الفائزة",assignedUserId:"admin",assignee:"مدير النظام",priority:"URGENT",assignedAt:"2026-08-19",dueDate:"2026-08-21",status:"REVIEW",section:"judging",nextAction:"فتح قسم التحكيم والفائزين"}],
  log:[{date:"2026-08-10T08:00:00.000Z",action:"إنشاء فعالية ابتكار مفتوح"},{date:"2026-08-18T09:00:00.000Z",action:"إسناد توثيق سجل المشاركين"},{date:"2026-08-20T14:00:00.000Z",action:"تسليم توثيق نتائج التحكيم للمراجعة"}]
}]};

export function openInnovationForPersona(persona?:string):WorkspaceData{
  const copy=structuredClone(PREVIEW_OPEN_INNOVATION);const events=copy.openInnovationEvents as Record<string,unknown>[];
  if(persona==="partner")copy.openInnovationEvents=events.map(event=>({...event,participants:[],files:(event.files as Record<string,unknown>[]).filter(file=>file.markedAsEvidence==="نعم"),tasks:[],log:[]}));
  if(persona==="viewer")copy.openInnovationEvents=events.map(event=>({...event,participants:[],teams:[],judges:[],judging:[],files:[],tasks:[],log:[]}));
  return copy;
}
