import type { DgaRequirementDefinition, DgaUnitDefinition } from "./types";

const requirement = (value: DgaRequirementDefinition) => value;

export const DGA_UNITS: readonly DgaUnitDefinition[] = [
  {
    code: "5.23.1", slug: "strategy", href: "/strategy", name: "التوجه الاستراتيجي",
    goal: "تعزيز مفهوم الابتكار في استراتيجيات الجهة، بما فيها استراتيجية التحول الرقمي، وضمان وجود توجه استراتيجي لتفعيل الابتكار وتبنيه.",
    readiness: 67, missingEvidence: 2, actionRequired: 2, lastUpdate: "8 أغسطس 2026",
    requirements: [
      requirement({ id: "5-23-1-r1", number: "01", title: "تضمين البحث والتطوير والابتكار في استراتيجية التحول الرقمي", applicationRequirement: "تضمين البحث والتطوير والابتكار كعنصر في استراتيجية التحول الرقمي، وتحديد مجالات الابتكار والأهداف والمؤشرات الاستراتيجية لتفعيل البحث والتطوير والابتكار، ومواءمتها مع أهداف الجهة.", tasks: ["تحديد مجالات الابتكار", "توثيق الأهداف الاستراتيجية ومؤشرات الأداء", "بيان المواءمة مع أهداف الجهة"], evidence: [{ title: "استراتيجية التحول الرقمي المتضمنة للبحث والتطوير والابتكار", reviewStatus: "HUMAN_REVIEWED" }], status: "COMPLETED", owner: "مدير الاستراتيجية والابتكار", lastUpdate: "8 أغسطس 2026" }),
      requirement({ id: "5-23-1-r2", number: "02", title: "تحديد مبادرات ومشروعات الابتكار الرقمي", applicationRequirement: "تحديد مبادرات ومشروعات الابتكار الرقمي المتوافقة مع أولويات الجهة ومستهدفاتها، وتحديد مؤشرات الأداء التي تقيس نجاح التنفيذ.", tasks: ["حصر المبادرات والمشروعات", "ربطها بأولويات الجهة ومستهدفاتها", "تعريف مؤشرات نجاح التنفيذ"], evidence: [{ title: "وثائق مبادرات ومشروعات البحث والتطوير والابتكار ومؤشرات أدائها", reviewStatus: "READY_FOR_REVIEW" }], status: "AWAITING_EVIDENCE", owner: "محرر الابتكار الداخلي", lastUpdate: "6 أغسطس 2026" }),
      requirement({ id: "5-23-1-r3", number: "03", title: "التعاون مع جهات ومراكز ومختبرات الابتكار", applicationRequirement: "التعاون مع جهات ومراكز ومختبرات البحث والتطوير والابتكار الوطنية أو الدولية للاستفادة من الخبرات والممكنات وتطبيق الحلول الابتكارية.", tasks: ["تحديد جهة التعاون ونطاقه", "توثيق مدة الاتفاقية ومخرجاتها", "متابعة حالة الاتفاقية"], evidence: [{ title: "اتفاقية تعاون معتمدة مع جهة أو مركز أو مختبر ابتكار", reviewStatus: "NOT_REVIEWED" }], status: "IN_PROGRESS", owner: "إدارة الشراكات", lastUpdate: "4 أغسطس 2026" }),
    ],
  },
  {
    code: "5.23.2", slug: "methodologies", href: "/activities", name: "منهجيات الابتكار",
    goal: "تبني منهجيات ومفاهيم الابتكار لتطوير واستدامة بيئة الابتكار وإنتاج خدمات ومنتجات وحلول ابتكارية بمشاركة فئات المستفيدين والمتخصصين.",
    readiness: 50, missingEvidence: 4, actionRequired: 3, lastUpdate: "7 أغسطس 2026",
    requirements: [
      requirement({ id: "5-23-2-r1", number: "01", title: "إعداد الخطة السنوية المتكاملة للأنشطة الابتكارية", applicationRequirement: "إعداد خطة سنوية متكاملة للأنشطة الابتكارية تتضمن الأهداف والمخرجات المتوقعة وآلية المتابعة والتقييم لكل نشاط بما يضمن استدامة الابتكار في الجهة.", tasks: ["تحديد الأهداف والأنشطة", "تحديد المخرجات المتوقعة والجدول والمسؤولين", "تحديد آلية المتابعة والتقييم لكل نشاط"], evidence: [{ title: "الخطة السنوية المتكاملة للأنشطة الابتكارية", reviewStatus: "HUMAN_REVIEWED" }], status: "COMPLETED", owner: "محرر الابتكار الداخلي", lastUpdate: "7 أغسطس 2026" }),
      requirement({ id: "5-23-2-r2", number: "02", title: "تطبيق منهجيات الابتكار", applicationRequirement: "تبني وتفعيل منهجيات الابتكار من قبل الموظفين، مثل التفكير التصميمي والعصف الذهني، لمعالجة التحديات وتوليد الأفكار وتوثيق المنهجيات والمشاركين والتحديات والحلول والنماذج الأولية والمشروعات والمؤشرات والأثر.", tasks: ["توثيق المنهجيات المستخدمة وطريقة تطبيقها على مخرج واحد على الأقل", "توثيق المشاركين", "تحديث سجل التحديات والحلول المقترحة", "توثيق النماذج الأولية ومراحلها ونتائجها", "ربط المشروعات الناتجة ومؤشرات أدائها وأثرها"], evidence: [{ title: "وثائق تطبيق منهجيات الابتكار", reviewStatus: "READY_FOR_REVIEW" }, { title: "توثيق جلستين للعصف الذهني على الأقل", reviewStatus: "NOT_REVIEWED" }], status: "AWAITING_EVIDENCE", owner: "فريق المنهجيات", lastUpdate: "5 أغسطس 2026" }),
      requirement({ id: "5-23-2-r3", number: "03", title: "تطبيق الابتكار المفتوح وإشراك المستفيدين", applicationRequirement: "تبني الابتكار المفتوح وإشراك فئات المستفيدين من خلال الهاكاثونات والمسابقات وورش العمل المتخصصة، وتوثيق الفعاليات والتحديات والحلول والمشاركين والنماذج والشهادات والمشروعات والأثر.", tasks: ["توثيق الهاكاثونات والمسابقات وورش العمل", "توثيق التحديات والحلول وثلاث عينات على الأقل لكل فعالية", "حصر أعداد وفئات المشاركين والمشروعات الفائزة", "إرفاق نماذج الشهادات", "توثيق النماذج الأولية والمشروعات المنفذة وأثرها"], evidence: [{ title: "وثائق تطبيق منهجية الابتكار المفتوح وفق متطلبات التطبيق", reviewStatus: "HAS_NOTES" }], status: "IN_PROGRESS", owner: "مدير البرامج والفعاليات", lastUpdate: "3 أغسطس 2026" }),
      requirement({ id: "5-23-2-r4", number: "04", title: "تفعيل التعاون مع الجهات المتخصصة", applicationRequirement: "تفعيل التعاون مع الجهات والمراكز والشركات المتخصصة، وعقد اجتماعات دورية وتحديد مخرجات التعاون وتوثيقها وإعداد تقارير دورية ودراستها وإصدار القرارات والإجراءات التصحيحية.", tasks: ["عقد اجتماعات ربع سنوية لمتابعة الاتفاقيات", "توثيق الدراسات ونقل المعرفة والنماذج الأولية وإثباتات المفهوم", "إعداد تقارير تقدم دورية", "دراسة التقارير وإصدار القرارات والإجراءات التصحيحية"], evidence: [{ title: "وثائق محدثة تثبت تفعيل اتفاقيات التعاون مع الجهات المتخصصة", reviewStatus: "NOT_REVIEWED" }], status: "NOT_STARTED", owner: "إدارة الشراكات", lastUpdate: "لم يبدأ" }),
    ],
  },
  {
    code: "5.23.3", slug: "governance", href: "/governance", name: "حوكمة وتفعيل الابتكار",
    goal: "توفير إطار وآلية لحوكمة الابتكار في التحول الرقمي، ومتابعة المبادرات وتحقيق المستهدفات واستدامة المنتجات والحلول وحفظ حقوق الجهة والملكية الفكرية.",
    readiness: 40, missingEvidence: 5, actionRequired: 4, lastUpdate: "6 أغسطس 2026",
    requirements: [
      requirement({ id: "5-23-3-r1", number: "01", title: "تشكيل وحدة أو لجنة للابتكار", applicationRequirement: "تشكيل وحدة إدارية أو لجنة لتعزيز الابتكار وتبنيه، مع تحديد الأدوار والمسؤوليات.", tasks: ["توثيق قرار التشكيل", "تحديد الأعضاء", "تحديد الأدوار والمسؤوليات"], evidence: [{ title: "الهيكل التنظيمي الموضح للوحدة أو اللجنة وأدوارها ومسؤولياتها", reviewStatus: "HUMAN_REVIEWED" }], status: "COMPLETED", owner: "مدير النظام", lastUpdate: "6 أغسطس 2026" }),
      requirement({ id: "5-23-3-r2", number: "02", title: "تفعيل الوحدة أو اللجنة واعتماد العمليات والإجراءات", applicationRequirement: "تفعيل الوحدة أو اللجنة واعتماد العمليات والإجراءات بالتنسيق مع الإدارات واللجان ذات العلاقة، بما يشمل السياسات ومراجعة الأفكار والمشروعات وبطاقات المبادرات وتقارير الأداء والقرارات والإجراءات التصحيحية.", tasks: ["اعتماد العمليات والإجراءات والسياسات الداعمة", "توثيق مراجعة الأفكار والمشروعات قبل التنفيذ", "إعداد بطاقات المبادرات والمشروعات", "إعداد ودراسة تقارير الأداء وإصدار القرارات التصحيحية"], evidence: [{ title: "وثائق محدثة تثبت تفعيل الوحدة أو اللجنة", reviewStatus: "READY_FOR_REVIEW" }], status: "AWAITING_EVIDENCE", owner: "أمين لجنة الابتكار", lastUpdate: "5 أغسطس 2026" }),
      requirement({ id: "5-23-3-r3", number: "03", title: "نشر ثقافة الابتكار", applicationRequirement: "تنظيم أنشطة وفعاليات لنشر ثقافة الابتكار من خلال التدريب والتوعية ونقل المعرفة.", tasks: ["تسجيل الأنشطة التدريبية والتوعوية والمعرفية", "توثيق النتائج والمشاركين", "إعداد تقارير الإنجاز"], evidence: [{ title: "تقارير إنجاز حديثة لثلاثة أنشطة أو فعاليات على الأقل", reviewStatus: "HAS_NOTES" }], status: "IN_PROGRESS", owner: "إدارة التواصل الداخلي", lastUpdate: "2 أغسطس 2026" }),
      requirement({ id: "5-23-3-r4", number: "04", title: "تطوير آلية إدارة الابتكار الرقمي", applicationRequirement: "تطوير آلية لإدارة الابتكار الرقمي تغطي الرحلة والإجراءات كاملة من الفكرة والتصميم إلى التطوير والتنفيذ.", tasks: ["توثيق استقبال الفكرة", "توثيق التصميم والتطوير", "توثيق التنفيذ والمتابعة"], evidence: [{ title: "إطار أو آلية معتمدة لإدارة الابتكار الرقمي", reviewStatus: "NOT_REVIEWED" }], status: "IN_PROGRESS", owner: "مكتب إدارة الابتكار", lastUpdate: "1 أغسطس 2026" }),
      requirement({ id: "5-23-3-r5", number: "05", title: "استقبال المقترحات والتغذية الراجعة", applicationRequirement: "توفير آليات لاستقبال المقترحات الابتكارية والتغذية الراجعة على الحلول الابتكارية المطورة.", tasks: ["تحديد قنوات استقبال المقترحات", "توثيق التغذية الراجعة من فئات المستفيدين", "متابعة المقترحات والملاحظات"], evidence: [{ title: "لقطات حديثة تثبت أتمتة استقبال المقترحات والتغذية الراجعة", reviewStatus: "NOT_REVIEWED" }], status: "NOT_STARTED", owner: "إدارة تجربة المستفيد", lastUpdate: "لم يبدأ" }),
    ],
  },
  { code: "5.24.1", slug: "solutions", href: "/solutions", name: "حصر الحلول الابتكارية", goal: "إنشاء سجل مؤسسي موحد للحلول الابتكارية يربط الحل بمصدره والجهة المالكة والهدف الاستراتيجي ومستوى النضج وجاهزية الأدلة.", readiness: 72, missingEvidence: 3, actionRequired: 2, lastUpdate: "8 أغسطس 2026", requirements: [], productFields: ["اسم الحل", "المصدر", "الجهة المالكة", "الهدف الاستراتيجي", "التكلفة", "المدة", "الفئات المستهدفة", "التقنيات", "مرحلة النضج", "حالة الحل", "جاهزية الأدلة", "الوثائق المرتبطة"], boundaryNote: "لم تحدد المراجع متطلبات تطبيق أو أدلة رسمية تفصيلية لهذه الوحدة؛ تعرض الصفحة فقط حقول المنتج الواردة في المرجع." },
  { code: "5.24.2", slug: "impact", href: "/impact", name: "قياس أثر الحلول", goal: "قياس أثر الحلول الابتكارية وربط نتائج القياس بالحل وبأدلة التنفيذ والأثر.", readiness: 35, missingEvidence: 4, actionRequired: 3, lastUpdate: "5 أغسطس 2026", requirements: [], productFields: ["الحل المرتبط", "بيانات التنفيذ", "الأثر المالي", "الأثر التشغيلي", "أثر المستفيدين", "نتائج القياس", "وثائق الإثبات", "حالة القياس"], boundaryNote: "لم تحدد المراجع متطلبات تطبيق أو أدلة رسمية تفصيلية لهذه الوحدة؛ تعرض الصفحة فقط حقول القياس الواردة في المرجع." },
] as const;

export function getDgaUnitByPath(path: string) { return DGA_UNITS.find((unit) => path === unit.href || path.startsWith(`${unit.href}/requirements/`)); }
export function getDgaRequirement(unit: DgaUnitDefinition, requirementId?: string) { return requirementId ? unit.requirements.find((item) => item.id === requirementId) : undefined; }
export const DGA_TOTALS = { readiness: Math.round(DGA_UNITS.reduce((sum, unit) => sum + unit.readiness, 0) / DGA_UNITS.length), completed: DGA_UNITS.flatMap((unit) => unit.requirements).filter((item) => item.status === "COMPLETED").length, requirements: DGA_UNITS.reduce((sum, unit) => sum + unit.requirements.length, 0), missingEvidence: DGA_UNITS.reduce((sum, unit) => sum + unit.missingEvidence, 0), actionRequired: DGA_UNITS.reduce((sum, unit) => sum + unit.actionRequired, 0) };
