export type WorkspaceFieldType = "text" | "textarea" | "date" | "number";
export interface WorkspaceField { key: string; label: string; type?: WorkspaceFieldType; required?: boolean }
export interface WorkspaceSection { key: string; title: string; repeatable?: boolean; minItems?: number; fields: readonly WorkspaceField[] }
export interface WorkspaceEvidenceRule { key: string; title: string; minCount: number }
export interface RequirementWorkspaceConfig { requirementId: string; code: string; explanation: string; sections: readonly WorkspaceSection[]; evidence: readonly WorkspaceEvidenceRule[] }

const f = (key: string, label: string, type: WorkspaceFieldType = "text", required = true): WorkspaceField => ({ key, label, type, required });
const e = (key: string, title: string, minCount = 1): WorkspaceEvidenceRule => ({ key, title, minCount });

export const REQUIREMENT_WORKSPACES: readonly RequirementWorkspaceConfig[] = [
  { requirementId:"5-23-1-r1", code:"5.23.1.1", explanation:"وثّق مجالات الابتكار وأهدافه الاستراتيجية ومؤشراته كسجلات مستقلة، وبيّن ارتباطها بأهداف الجهة.", sections:[
    {key:"innovationAreas",title:"مجالات الابتكار",repeatable:true,minItems:1,fields:[f("name","اسم المجال"),f("description","الوصف","textarea"),f("rationale","سبب الاختيار","textarea"),f("strategicPriorityLink","الارتباط بالأولويات الاستراتيجية","textarea"),f("ownerEntity","الجهة المالكة"),f("participatingDepartments","الإدارات المشاركة","textarea",false)]},
    {key:"strategicGoals",title:"الأهداف الاستراتيجية للبحث والابتكار",repeatable:true,minItems:1,fields:[f("name","اسم الهدف"),f("description","الوصف","textarea"),f("entityGoalLink","الارتباط بهدف استراتيجي للجهة","textarea"),f("digitalTransformationLink","الارتباط بهدف في استراتيجية التحول الرقمي","textarea"),f("owner","المالك"),f("startDate","تاريخ البداية","date"),f("endDate","تاريخ النهاية","date",false)]},
    {key:"kpis",title:"المؤشرات KPIs",repeatable:true,minItems:1,fields:[f("name","اسم المؤشر"),f("definition","تعريف المؤشر","textarea"),f("calculationMethod","طريقة الحساب","textarea"),f("baseline","Baseline"),f("target","Target"),f("measurementFrequency","دورية القياس"),f("dataSource","مصدر البيانات"),f("owner","مالك المؤشر")]},
    {key:"alignment",title:"المواءمة مع أهداف الجهة",fields:[f("entityAlignment","الارتباط بأهداف الجهة","textarea")]},
  ], evidence:[e("DIGITAL_TRANSFORMATION_STRATEGY","استراتيجية التحول الرقمي المتضمنة للبحث والتطوير والابتكار")] },
  { requirementId:"5-23-1-r2", code:"5.23.1.2", explanation:"وثّق المبادرات والمشروعات المؤسسية الداعمة لاتجاه الابتكار، واربطها بأهداف ومؤشرات المتطلب 01 دون تكرار البيانات المؤسسية.", sections:[
    {key:"initiatives",title:"بيانات المبادرات والمشروعات",repeatable:true,minItems:1,fields:[f("name","اسم المبادرة/المشروع"),f("description","وصف المبادرة","textarea"),f("owningDepartment","الإدارة المالكة"),f("owner","المسؤول"),f("status","الحالة"),f("startDate","تاريخ البداية","date"),f("targetDate","تاريخ النهاية / الموعد المستهدف","date"),f("lastUpdate","آخر تحديث","date")]},
    {key:"strategicAlignment",title:"المواءمة الاستراتيجية",repeatable:true,minItems:1,fields:[f("initiativeName","المبادرة/المشروع"),f("strategicObjective","الهدف الاستراتيجي المرتبط"),f("alignmentReason","سبب الارتباط","textarea")]},
    {key:"initiativeKpis",title:"مؤشرات أداء المبادرات",repeatable:true,minItems:1,fields:[f("initiativeName","المبادرة/المشروع"),f("kpiName","مؤشر الأداء المرتبط"),f("initiativeTarget","مستهدف المبادرة"),f("owner","المسؤول عن القياس")]},
  ], evidence:[e("INITIATIVE_PROJECT_KPI_DOCUMENTS","وثائق المبادرات والمشروعات ومؤشرات الأداء")] },
  { requirementId:"5-23-1-r3", code:"5.23.1.3", explanation:"وثّق جهة التعاون ونطاقه ومدته ومسؤوله ومخرجاته وحالة الاتفاقية.", sections:[{key:"cooperations",title:"سجلات التعاون",repeatable:true,minItems:1,fields:[f("entity","الجهة المتعاونة"),f("scope","نوع/نطاق التعاون","textarea"),f("startDate","تاريخ البداية","date"),f("endDate","تاريخ النهاية","date",false),f("owner","المسؤول"),f("outputs","المخرجات","textarea"),f("agreementStatus","حالة الاتفاقية")]}], evidence:[e("APPROVED_COOPERATION_AGREEMENT","اتفاقية تعاون معتمدة")] },
  { requirementId:"5-23-2-r1", code:"5.23.2.1", explanation:"أنشئ الخطة السنوية للأنشطة والفعاليات مع أهداف ومخرجات وفئة مستهدفة وميزانية وجدول ومسؤول وآلية متابعة لكل نشاط.", sections:[{key:"activities",title:"أنشطة الخطة السنوية",repeatable:true,minItems:1,fields:[f("activity","النشاط/الفعالية"),f("objectives","الأهداف","textarea"),f("outputs","المخرجات المتوقعة","textarea"),f("targetAudience","الفئة المستهدفة"),f("budget","الميزانية","text",false),f("timeline","الجدول الزمني"),f("owner","المسؤول"),f("evaluation","آلية المتابعة والتقييم","textarea")]}], evidence:[e("ANNUAL_INNOVATION_PLAN","الخطة السنوية المتكاملة للفعاليات الابتكارية")] },
  { requirementId:"5-23-2-r2", code:"5.23.2.2", explanation:"وثّق تطبيق منهجيات الابتكار ومخرجاتها، بما في ذلك جلستا عصف ذهني على الأقل.", sections:[{key:"application",title:"تطبيق المنهجية",fields:[f("methodology","المنهجية المستخدمة"),f("application","كيفية التطبيق","textarea"),f("participants","المشاركون","textarea"),f("challenges","التحديات المحددة","textarea"),f("solutions","الحلول المقترحة","textarea"),f("prototypes","النماذج الأولية","textarea"),f("prototypeStages","مراحل تطوير النماذج ونتائجها","textarea"),f("projects","المشروعات الناتجة","textarea"),f("kpis","مؤشرات الأداء","textarea"),f("impact","الأثر","textarea")]},{key:"brainstormingSessions",title:"جلسات ومنهجيات الابتكار",repeatable:true,minItems:2,fields:[f("date","تاريخ الجلسة","date"),f("topic","التحدي/الموضوع"),f("methodology","المنهجية المستخدمة"),f("owningDepartment","الإدارة المالكة للتحدي"),f("facilitator","الميسر"),f("participants","المشاركون","textarea"),f("outputs","الأفكار والحلول الناتجة","textarea"),f("decisions","القرارات","textarea",false)]}], evidence:[e("INNOVATION_METHODOLOGY_DOCUMENTS","وثائق تثبت تطبيق أطر ومنهجيات الابتكار")] },
  { requirementId:"5-23-2-r3", code:"5.23.2.3", explanation:"وثّق فعالية الابتكار المفتوح والمشاركين والتحديات والحلول والنماذج والمشروعات والأثر مع عينات التوثيق.", sections:[{key:"events",title:"فعاليات الابتكار المفتوح",repeatable:true,minItems:1,fields:[f("eventType","نوع الفعالية (هاكاثون/مسابقة/ورشة)"),f("eventInfo","معلومات الفعالية","textarea"),f("challenges","التحديات","textarea"),f("solutions","الحلول المقترحة","textarea"),f("participantCount","عدد المشاركين","number"),f("participantCategories","فئات المشاركين","textarea"),f("winners","المشروعات الفائزة","textarea"),f("certificateSamples","عينات الشهادات","textarea"),f("prototypes","النماذج الأولية وتطويرها ونتائجها","textarea"),f("implementedProjects","المشروعات المنفذة","textarea"),f("impact","الأثر","textarea")]}], evidence:[e("OPEN_INNOVATION_DOCUMENTS","وثائق محدثة تثبت تطبيق الابتكار المفتوح")] },
  { requirementId:"5-23-2-r4", code:"5.23.2.4", explanation:"اربط الاتفاقية ووثّق الاجتماعات الربع سنوية ومخرجات التعاون والدراسات ونقل المعرفة والنماذج/PoC وتقارير التقدم والقرارات والإجراءات التصحيحية.", sections:[{key:"activation",title:"تفعيل التعاون",fields:[f("agreement","اتفاقية التعاون المرتبطة"),f("partnerType","نوع الجهة المتعاونة"),f("outputs","مخرجات التعاون المتفق عليها","textarea"),f("studies","الدراسات","textarea",false),f("knowledgeTransfer","نقل المعرفة","textarea",false),f("prototypePoc","النماذج الأولية/Prototype/PoC","textarea",false),f("progressReports","تقارير التقدم","textarea"),f("decisions","القرارات","textarea"),f("correctiveActions","الإجراءات التصحيحية","textarea")]},{key:"meetings",title:"اجتماعات المتابعة الربع سنوية",repeatable:true,minItems:4,fields:[f("date","تاريخ الاجتماع","date"),f("minutes","محضر الاجتماع","textarea"),f("outputs","المخرجات","textarea")]}], evidence:[e("COOPERATION_ACTIVATION_DOCUMENTS","وثائق تثبت التفعيل الفعلي لاتفاقيات التعاون")] },
  { requirementId:"5-23-3-r1", code:"5.23.3.1", explanation:"وثّق تشكيل وحدة أو لجنة الابتكار وأعضاءها وأدوارها ومسؤولياتها وموقعها التنظيمي وصلاحياتها واجتماعاتها.", sections:[{key:"formation",title:"بيانات الوحدة/اللجنة",fields:[f("name","اسم الوحدة/اللجنة"),f("organizationalPlacement","الموقع التنظيمي","textarea"),f("formationDecision","قرار التشكيل","textarea"),f("authorities","الصلاحيات","textarea")]},{key:"members",title:"الأعضاء والأدوار",repeatable:true,minItems:1,fields:[f("member","اسم العضو"),f("role","الدور"),f("responsibilities","المسؤوليات","textarea")]},{key:"committeeMeetings",title:"اجتماعات اللجنة ومحاضرها",repeatable:true,minItems:1,fields:[f("date","تاريخ الاجتماع","date"),f("minutes","المحضر","textarea"),f("decisions","القرارات","textarea",false)]}], evidence:[e("APPROVED_COMMITTEE_STRUCTURE","هيكل تنظيمي/لجنة معتمد يوضح الأدوار والمسؤوليات")] },
  { requirementId:"5-23-3-r2", code:"5.23.3.2", explanation:"وثّق تفعيل الوحدة أو اللجنة عبر الإجراءات والسياسات والنماذج والإصدارات وسجلات المراجعة والتقارير والقرارات التصحيحية.", sections:[{key:"activation",title:"التفعيل والحوكمة",fields:[f("procedures","الإجراءات/العمليات","textarea"),f("policies","السياسات الداعمة","textarea"),f("templates","النماذج","textarea",false),f("versions","الإصدارات","textarea",false),f("reviewRecords","سجلات مراجعة الأفكار/المشروعات","textarea"),f("projectCards","بطاقات المبادرات/المشروعات","textarea"),f("performanceReports","تقارير الأداء الدورية","textarea"),f("decisions","القرارات","textarea"),f("correctiveActions","الإجراءات التصحيحية","textarea")]}], evidence:[e("COMMITTEE_ACTIVATION_DOCUMENTS","وثائق محدثة تثبت تفعيل الوحدة/اللجنة")] },
  { requirementId:"5-23-3-r3", code:"5.23.3.3", explanation:"سجّل أنشطة نشر ثقافة الابتكار وتقييمها وارفع تقارير إنجاز حديثة لثلاثة أنشطة على الأقل.", sections:[{key:"cultureActivities",title:"أنشطة ثقافة الابتكار",repeatable:true,minItems:3,fields:[f("name","اسم النشاط"),f("type","نوع النشاط"),f("date","التاريخ","date"),f("audience","الفئة المستهدفة"),f("attendance","الحضور/المشاركون","number"),f("objective","الهدف","textarea"),f("evaluation","التقييم","textarea",false),f("result","النتيجة/المخرج","textarea")]}], evidence:[e("CULTURE_ACTIVITY_REPORTS","تقارير إنجاز حديثة للأنشطة",3)] },
  { requirementId:"5-23-3-r4", code:"5.23.3.4", explanation:"وثّق الآلية المعتمدة لإدارة الابتكار الرقمي ودورة حياتها من الفكرة والتصميم إلى التطوير ثم التنفيذ، وسجّل تقدّم كل مبادرة عبر مراحل الرحلة.", sections:[{key:"mechanism",title:"الآلية ودورة الحياة",fields:[f("framework","الآلية/الإطار المعتمد","textarea"),f("ideaDesign","الفكرة والتصميم","textarea"),f("development","التطوير","textarea"),f("implementation","التنفيذ","textarea")]},{key:"lifecycleStages",title:"سجل مراحل رحلة الابتكار",repeatable:true,minItems:1,fields:[f("initiative","المبادرة/الحل"),f("stage","المرحلة الحالية (تحدٍ / فكرة / فرز / تقييم / دراسة جدوى / اعتماد / Prototype / PoC / Pilot / تنفيذ / قياس أثر / توسع واستدامة)"),f("date","تاريخ آخر تحديث للمرحلة","date"),f("owner","المالك"),f("notes","ملاحظات المرحلة","textarea",false)]}], evidence:[e("DIGITAL_INNOVATION_MECHANISM","إطار أو آلية معتمدة لإدارة الابتكار الرقمي")] },
  { requirementId:"5-23-3-r5", code:"5.23.3.5", explanation:"وثّق آلية الاستقبال الآلي للمقترحات والتغذية الراجعة على الحلول المطورة ومصادرها وفئاتها.", sections:[{key:"mechanism",title:"قنوات الاستقبال",fields:[f("proposalReceiving","استقبال المقترحات","textarea"),f("feedbackReceiving","استقبال التغذية الراجعة على الحلول المطورة","textarea"),f("sourceAudience","المصدر/الفئة","textarea",false)]}], evidence:[e("AUTOMATED_PROPOSAL_SCREENSHOTS","لقطات حديثة تثبت الاستقبال الآلي للمقترحات والتغذية الراجعة")] },
] as const;

export function getWorkspaceConfig(requirementId: string) { return REQUIREMENT_WORKSPACES.find((item) => item.requirementId === requirementId); }
export function getRequirementByCode(code: string) { return REQUIREMENT_WORKSPACES.find((item) => item.code === code); }
