export type WorkspaceFieldType = "text" | "textarea" | "date" | "number" | "select";
export interface WorkspaceField { key: string; label: string; type?: WorkspaceFieldType; required?: boolean; options?: readonly string[] }
export interface WorkspaceSection { key: string; title: string; repeatable?: boolean; minItems?: number; contributionOnly?:boolean; fields: readonly WorkspaceField[] }
export interface WorkspaceEvidenceRule { key: string; title: string; minCount: number }
export interface RequirementWorkspaceConfig { requirementId: string; code: string; explanation: string; sections: readonly WorkspaceSection[]; evidence: readonly WorkspaceEvidenceRule[] }

const f = (key: string, label: string, type: WorkspaceFieldType = "text", required = true): WorkspaceField => ({ key, label, type, required });
const e = (key: string, title: string, minCount = 1): WorkspaceEvidenceRule => ({ key, title, minCount });
const openSection=(key:string,title:string,fields:readonly WorkspaceField[]):WorkspaceSection=>({key,title,repeatable:true,minItems:1,fields,contributionOnly:true});
const OPEN_INNOVATION_CONTRIBUTION_SECTIONS:readonly WorkspaceSection[]=[
  openSection("timeline","الجدول والجلسات",[f("name","اسم السجل"),f("type","النوع"),f("date","التاريخ/الوقت"),f("responsible","المسؤول"),f("status","الحالة"),f("followUp","إجراء المتابعة","textarea",false)]),
  openSection("challenges","التحديات",[f("title","عنوان التحدي"),f("description","الوصف","textarea"),f("owner","المالك"),f("entity","الإدارة/الجهة"),f("category","التصنيف"),f("status","الحالة")]),
  openSection("participants","سجل المشاركين",[f("name","اسم المشارك"),f("category","الفئة"),f("organization","الجهة"),f("teamId","الفريق","text",false),f("status","الحالة"),f("attendance","الحضور")]),
  openSection("teams","الفرق",[f("name","اسم الفريق"),f("lead","قائد الفريق"),f("challengeId","التحدي"),f("solutionId","الحل","text",false),f("status","الحالة")]),
  openSection("solutions","الحلول والمشاركات",[f("name","اسم الحل"),f("challengeId","التحدي"),f("teamId","الفريق"),f("summary","الملخص","textarea"),f("submittedAt","تاريخ التسليم"),f("status","الحالة")]),
  openSection("judging","التحكيم",[f("solutionId","الحل"),f("round","الجولة"),f("criteria","المعايير"),f("score","النتيجة"),f("comments","الملاحظات","textarea",false),f("ranking","الترتيب")]),
  openSection("winners","الفائزون",[f("solutionId","الحل"),f("category","فئة الفوز"),f("ranking","الترتيب"),f("decision","القرار")]),
  openSection("prototypes","النماذج الأولية",[f("name","اسم النموذج"),f("solutionId","الحل المصدر"),f("version","الإصدار"),f("stage","المرحلة"),f("result","النتيجة","textarea")]),
  openSection("projects","المشاريع الناتجة",[f("solutionId","الحل المصدر"),f("name","اسم المشروع"),f("owner","المالك"),f("department","الإدارة"),f("implementationState","حالة التنفيذ"),f("status","الحالة")]),
  openSection("impact","معلومات الأثر",[f("projectId","المشروع"),f("beneficiaries","المستفيدون"),f("outcome","النتيجة","textarea"),f("kpi","المؤشر"),f("measurement","القياس")]),
  openSection("files","ملفات العمل والشهادات",[f("title","اسم الملف"),f("category","الفئة"),f("fileName","اسم الملف المرفوع"),f("reviewState","حالة المراجعة")]),
  openSection("evidence","تجهيز الإثبات",[f("title","وصف الدليل"),f("relatedRecord","السجل المرتبط"),f("notes","ملاحظات التجهيز","textarea")]),
  openSection("closure","توثيق الإغلاق",[f("summary","ملخص الإغلاق","textarea"),f("openItems","العناصر المتبقية","textarea",false),f("status","الحالة")]),
];
const COOPERATION_ACTIVATION_CONTRIBUTION_SECTIONS:readonly WorkspaceSection[]=[
  {...openSection("meetings","إعداد الاجتماعات والمحاضر",[f("title","عنوان الاجتماع"),f("quarter","الربع"),f("date","التاريخ","date"),f("minutes","المحضر","textarea"),f("status","الحالة")]),minItems:4},
  openSection("commitments","متابعة الالتزامات",[f("title","الالتزام"),f("source","المصدر"),f("owner","المسؤول"),f("dueDate","الموعد","date"),f("status","الحالة")]),
  openSection("outputs","توثيق المخرجات",[f("name","المخرج"),f("type","النوع"),f("description","الوصف","textarea"),f("owner","المالك"),f("status","الحالة")]),
  openSection("reports","إعداد التقرير الدوري",[f("title","التقرير"),f("period","الفترة"),f("responsible","المسؤول"),f("reviewStatus","المراجعة"),f("approvalStatus","الاعتماد")]),
  openSection("correctiveActions","تحديث الإجراءات التصحيحية",[f("issue","الفجوة"),f("action","الإجراء","textarea"),f("responsible","المسؤول"),f("dueDate","الموعد","date"),f("status","الحالة")]),
  openSection("evidence","تجهيز دليل التفعيل",[f("title","وصف الدليل"),f("relatedRecord","السجل المرتبط"),f("notes","ملاحظات","textarea")]),
];

export const REQUIREMENT_WORKSPACES: readonly RequirementWorkspaceConfig[] = [
  { requirementId:"5-23-1-r1", code:"5.23.1.1", explanation:"وثّق مجالات الابتكار وأهدافه الاستراتيجية ومؤشراته كسجلات مستقلة، وبيّن ارتباطها بأهداف الجهة.", sections:[
    {key:"innovationAreas",title:"مجالات الابتكار",repeatable:true,minItems:1,fields:[f("name","اسم المجال"),f("description","الوصف","textarea"),f("rationale","سبب الاختيار","textarea"),f("strategicPriorityLink","الارتباط بالأولويات الاستراتيجية","textarea"),f("ownerEntity","الجهة المالكة"),f("participatingDepartments","الإدارات المشاركة","textarea",false)]},
    {key:"strategicGoals",title:"الأهداف الاستراتيجية للبحث والابتكار",repeatable:true,minItems:1,fields:[f("name","اسم الهدف"),f("description","الوصف","textarea"),f("entityGoalLink","الارتباط بهدف استراتيجي للجهة","textarea"),f("digitalTransformationLink","الارتباط بهدف في استراتيجية التحول الرقمي","textarea"),f("owner","المالك"),f("startDate","تاريخ البداية","date"),f("endDate","تاريخ النهاية","date",false)]},
    {key:"kpis",title:"المؤشرات KPIs",repeatable:true,minItems:1,fields:[f("name","اسم المؤشر"),f("definition","تعريف المؤشر","textarea"),f("calculationMethod","طريقة الحساب","textarea"),f("baseline","Baseline"),f("target","Target"),f("measurementFrequency","دورية القياس"),f("dataSource","مصدر البيانات"),f("owner","مالك المؤشر")]},
    {key:"alignment",title:"المواءمة مع أهداف الجهة",fields:[f("entityAlignment","الارتباط بأهداف الجهة","textarea")]},
  ], evidence:[e("DIGITAL_TRANSFORMATION_STRATEGY","استراتيجية التحول الرقمي المتضمنة للبحث والتطوير والابتكار")] },
  { requirementId:"5-23-1-r2", code:"5.23.1.2", explanation:"وثّق المبادرات والمشروعات المؤسسية الداعمة لاتجاه الابتكار، واربطها بأهداف ومؤشرات المتطلب 01 دون تكرار البيانات المؤسسية.", sections:[
    {key:"initiatives",title:"بيانات المبادرات والمشروعات",repeatable:true,minItems:1,fields:[f("name","اسم المبادرة/المشروع"),f("description","وصف المبادرة","textarea"),f("owningDepartment","الإدارة المالكة"),f("owner","المسؤول"),f("status","الحالة"),f("startDate","تاريخ البداية","date"),f("targetDate","تاريخ النهاية / الموعد المستهدف","date"),f("lastUpdate","آخر تحديث","date")]},
    {key:"strategicAlignment",title:"المواءمة الاستراتيجية",repeatable:true,minItems:1,fields:[f("initiativeName","المبادرة/المشروع"),f("strategicObjective","الهدف الاستراتيجي المرتبط"),f("alignmentReason","سبب الارتباط","textarea")]},
    {key:"initiativeKpis",title:"مؤشرات أداء المبادرات",repeatable:true,minItems:1,fields:[f("initiativeName","المبادرة/المشروع"),f("kpiName","مؤشر الأداء المرتبط"),f("initiativeTarget","مستهدف المبادرة"),f("owner","المسؤول عن القياس")]},
  ], evidence:[e("INITIATIVE_PROJECT_KPI_DOCUMENTS","وثائق المبادرات والمشروعات ومؤشرات الأداء")] },
  { requirementId:"5-23-1-r3", code:"5.23.1.3", explanation:"أنشئ سجل تعاون مؤسسي يوضح الجهة الشريكة ونطاق التعاون وملكيته ومدته، ثم اربطه باتفاقية التعاون وإثباتها دون اعتبار رفع الملف اعتمادًا رسميًا.", sections:[
    {key:"cooperations",title:"علاقات التعاون",repeatable:true,minItems:1,fields:[f("partnerName","اسم الجهة المتعاونة"),f("partnerType","نوع الجهة"),{...f("locationType","محلية / دولية","select"),options:["محلية","دولية"]},f("country","الدولة","text",false),f("description","وصف مختصر","textarea"),f("cooperationField","مجال التعاون"),f("objective","هدف التعاون","textarea"),f("scope","نطاق التعاون","textarea"),f("innovationRelation","علاقته بالبحث والتطوير والابتكار","textarea"),f("owningDepartment","الإدارة المالكة"),f("internalOwner","المسؤول الداخلي"),f("supportingDepartment","جهة/إدارة داعمة","text",false),f("startDate","تاريخ البداية","date"),f("endDate","تاريخ النهاية","date",false),f("status","حالة التعاون"),f("notes","ملاحظات","textarea",false)]},
    {key:"partnerContacts",title:"جهات الاتصال والمسؤولون",repeatable:true,minItems:1,fields:[f("cooperationName","سجل التعاون"),f("name","الاسم"),f("title","المسمى الوظيفي"),f("departmentName","الإدارة / القسم"),f("organization","الجهة"),f("email","البريد الإلكتروني"),f("phone","رقم التواصل","text",false),f("role","دوره في علاقة التعاون"),{...f("isPrimary","جهة الاتصال الرئيسية","select"),options:["نعم","لا"]},f("notes","ملاحظات","textarea",false),{...f("status","حالة جهة الاتصال","select"),options:["نشط","مؤرشف"]}]},
    {key:"agreements",title:"اتفاقية التعاون",repeatable:true,minItems:1,fields:[f("cooperationName","سجل التعاون"),f("title","اسم / عنوان الاتفاقية"),f("referenceNumber","الرقم المرجعي","text",false),f("parties","الأطراف"),f("startDate","تاريخ البداية","date"),f("endDate","تاريخ النهاية","date",false),f("scope","نطاق الاتفاقية","textarea"),f("internalOwner","المالك الداخلي"),f("status","حالة الاتفاقية"),f("currentVersion","الإصدار الحالي")]},
    {key:"cooperationOutputs",title:"مخرجات التعاون",repeatable:true,minItems:1,fields:[f("cooperationName","سجل التعاون"),f("outputType","نوع المخرج"),f("expectedOutput","المخرج المتوقع","textarea"),f("actualOutput","المخرج الفعلي","textarea",false),f("owner","المسؤول"),f("status","الحالة")]},
  ], evidence:[e("APPROVED_COOPERATION_AGREEMENT","اتفاقية تعاون معتمدة مع جهة/مركز/مختبر بحث وتطوير وابتكار")] },
  { requirementId:"5-23-2-r1", code:"5.23.2.1", explanation:"أنشئ الخطة السنوية للأنشطة والفعاليات مع أهداف ومخرجات وفئة مستهدفة وميزانية وجدول ومسؤول وآلية متابعة لكل نشاط.", sections:[{key:"activities",title:"أنشطة الخطة السنوية",repeatable:true,minItems:1,fields:[f("activity","النشاط/الفعالية"),f("objectives","الأهداف","textarea"),f("outputs","المخرجات المتوقعة","textarea"),f("targetAudience","الفئة المستهدفة"),f("budget","الميزانية","text",false),f("timeline","الجدول الزمني"),f("owner","المسؤول"),f("evaluation","آلية المتابعة والتقييم","textarea")]}], evidence:[e("ANNUAL_INNOVATION_PLAN","الخطة السنوية المتكاملة للفعاليات الابتكارية")] },
  { requirementId:"5-23-2-r2", code:"5.23.2.2", explanation:"وثّق تطبيق منهجيات الابتكار ومخرجاتها، بما في ذلك جلستا عصف ذهني على الأقل.", sections:[{key:"application",title:"تطبيق المنهجية",fields:[f("methodology","المنهجية المستخدمة"),f("application","كيفية التطبيق","textarea"),f("participants","المشاركون","textarea"),f("challenges","التحديات المحددة","textarea"),f("solutions","الحلول المقترحة","textarea"),f("prototypes","النماذج الأولية","textarea"),f("prototypeStages","مراحل تطوير النماذج ونتائجها","textarea"),f("projects","المشروعات الناتجة","textarea"),f("kpis","مؤشرات الأداء","textarea"),f("impact","الأثر","textarea")]},{key:"brainstormingSessions",title:"جلسات ومنهجيات الابتكار",repeatable:true,minItems:2,fields:[f("date","تاريخ الجلسة","date"),f("topic","التحدي/الموضوع"),f("methodology","المنهجية المستخدمة"),f("owningDepartment","الإدارة المالكة للتحدي"),f("facilitator","الميسر"),f("participants","المشاركون","textarea"),f("outputs","الأفكار والحلول الناتجة","textarea"),f("decisions","القرارات","textarea",false)]}], evidence:[e("INNOVATION_METHODOLOGY_DOCUMENTS","وثائق تثبت تطبيق أطر ومنهجيات الابتكار")] },
  { requirementId:"5-23-2-r3", code:"5.23.2.3", explanation:"أدر فعاليات الابتكار المفتوح كسجلات تشغيلية مستقلة ومترابطة، ووثّق التحديات والمشاركين والحلول والتحكيم والنماذج والمشروعات والأثر وعينات التوثيق.", sections:[{key:"openInnovationEvents",title:"فعاليات الابتكار المفتوح",repeatable:true,minItems:1,fields:[f("name","اسم الفعالية"),f("type","نوع الفعالية"),f("objective","الهدف","textarea"),f("owner","المالك"),f("department","الإدارة المسؤولة"),f("startDate","تاريخ البداية","date"),f("endDate","تاريخ النهاية","date")]},...OPEN_INNOVATION_CONTRIBUTION_SECTIONS], evidence:[e("OPEN_INNOVATION_DOCUMENTS","وثائق محدثة تثبت تطبيق الابتكار المفتوح")] },
  { requirementId:"5-23-2-r4", code:"5.23.2.4", explanation:"اربط علاقة التعاون والاتفاقية القائمة من 5.23.1، ثم أدر خطة التفعيل والاجتماعات الربع سنوية والالتزامات والمخرجات والتقارير والقرارات والإجراءات التصحيحية لإثبات التفعيل الفعلي.", sections:[{key:"cooperationActivations",title:"مساحات تفعيل التعاون",repeatable:true,minItems:1,fields:[f("cooperationName","علاقة التعاون"),f("agreementTitle","الاتفاقية"),f("owner","المالك"),f("department","الإدارة"),f("status","حالة التفعيل")]},...COOPERATION_ACTIVATION_CONTRIBUTION_SECTIONS], evidence:[e("COOPERATION_ACTIVATION_DOCUMENTS","وثائق تثبت التفعيل الفعلي لاتفاقيات التعاون")] },
  { requirementId:"5-23-3-r1", code:"5.23.3.1", explanation:"شكّل وحدة إدارية أو لجنة (أو أكثر) لتعزيز الابتكار وتبنيه، ووثّق أعضاءها وفئاتهم وأدوارهم ومسؤولياتهم وموقعها التنظيمي وقرار تشكيلها. هذا المتطلب هو مصدر الحقيقة الوحيد لبيانات الوحدة/اللجنة؛ لا يُعاد إنشاؤها في المتطلب 02.", sections:[{key:"structures",title:"وحدات/لجان الابتكار",repeatable:true,minItems:1,fields:[
    f("name","اسم الوحدة/اللجنة"),
    {...f("type","النوع","select"),options:["وحدة","لجنة"]},
    f("purpose","الغرض","textarea"),
    f("mandateDescription","وصف الاختصاص","textarea"),
    f("relatedDepartmentName","الجهة/الإدارة المرتبطة"),
    f("chairName","الرئيس/المسؤول"),
    f("formationDate","تاريخ التشكيل","date"),
    {...f("status","الحالة","select"),options:["مُقترَحة","نشطة","منحلّة"]},
    f("secretaryName","أمين اللجنة","text",false),
    f("operationStartDate","تاريخ بداية العمل","date",false),
    f("meetingFrequency","دورية الاجتماعات","text",false),
    f("notes","ملاحظات","textarea",false),
    f("decisionNumber","رقم قرار التشكيل","text",false),
    f("decisionDate","تاريخ القرار","date",false),
    f("decisionApprovingAuthority","جهة الاعتماد","text",false),
    f("decisionEffectiveDate","تاريخ السريان","date",false),
    f("decisionNotes","ملاحظات القرار","textarea",false),
  ]}], evidence:[e("APPROVED_COMMITTEE_STRUCTURE","هيكل تنظيمي/لجنة معتمد يوضح الأدوار والمسؤوليات")] },
  { requirementId:"5-23-3-r2", code:"5.23.3.2", explanation:"وثّق تفعيل الوحدة أو اللجنة عبر الإجراءات والسياسات والنماذج والإصدارات وسجلات المراجعة والتقارير والقرارات التصحيحية.", sections:[{key:"activation",title:"التفعيل والحوكمة",fields:[f("procedures","الإجراءات/العمليات","textarea"),f("policies","السياسات الداعمة","textarea"),f("templates","النماذج","textarea",false),f("versions","الإصدارات","textarea",false),f("reviewRecords","سجلات مراجعة الأفكار/المشروعات","textarea"),f("projectCards","بطاقات المبادرات/المشروعات","textarea"),f("performanceReports","تقارير الأداء الدورية","textarea"),f("decisions","القرارات","textarea"),f("correctiveActions","الإجراءات التصحيحية","textarea")]}], evidence:[e("COMMITTEE_ACTIVATION_DOCUMENTS","وثائق محدثة تثبت تفعيل الوحدة/اللجنة")] },
  { requirementId:"5-23-3-r3", code:"5.23.3.3", explanation:"سجّل أنشطة نشر ثقافة الابتكار وتقييمها وارفع تقارير إنجاز حديثة لثلاثة أنشطة على الأقل.", sections:[{key:"cultureActivities",title:"أنشطة ثقافة الابتكار",repeatable:true,minItems:3,fields:[f("name","اسم النشاط"),f("type","نوع النشاط"),f("date","التاريخ","date"),f("audience","الفئة المستهدفة"),f("attendance","الحضور/المشاركون","number"),f("objective","الهدف","textarea"),f("evaluation","التقييم","textarea",false),f("result","النتيجة/المخرج","textarea")]}], evidence:[e("CULTURE_ACTIVITY_REPORTS","تقارير إنجاز حديثة للأنشطة",3)] },
  { requirementId:"5-23-3-r4", code:"5.23.3.4", explanation:"وثّق الآلية المعتمدة لإدارة الابتكار الرقمي ودورة حياتها من الفكرة والتصميم إلى التطوير ثم التنفيذ، وسجّل تقدّم كل مبادرة عبر مراحل الرحلة.", sections:[{key:"mechanism",title:"الآلية ودورة الحياة",fields:[f("framework","الآلية/الإطار المعتمد","textarea"),f("ideaDesign","الفكرة والتصميم","textarea"),f("development","التطوير","textarea"),f("implementation","التنفيذ","textarea")]},{key:"lifecycleStages",title:"سجل مراحل رحلة الابتكار",repeatable:true,minItems:1,fields:[f("initiative","المبادرة/الحل"),f("stage","المرحلة الحالية (تحدٍ / فكرة / فرز / تقييم / دراسة جدوى / اعتماد / Prototype / PoC / Pilot / تنفيذ / قياس أثر / توسع واستدامة)"),f("date","تاريخ آخر تحديث للمرحلة","date"),f("owner","المالك"),f("notes","ملاحظات المرحلة","textarea",false)]}], evidence:[e("DIGITAL_INNOVATION_MECHANISM","إطار أو آلية معتمدة لإدارة الابتكار الرقمي")] },
  { requirementId:"5-23-3-r5", code:"5.23.3.5", explanation:"وثّق آلية الاستقبال الآلي للمقترحات والتغذية الراجعة على الحلول المطورة ومصادرها وفئاتها.", sections:[{key:"mechanism",title:"قنوات الاستقبال",fields:[f("proposalReceiving","استقبال المقترحات","textarea"),f("feedbackReceiving","استقبال التغذية الراجعة على الحلول المطورة","textarea"),f("sourceAudience","المصدر/الفئة","textarea",false)]}], evidence:[e("AUTOMATED_PROPOSAL_SCREENSHOTS","لقطات حديثة تثبت الاستقبال الآلي للمقترحات والتغذية الراجعة")] },
] as const;

export function getWorkspaceConfig(requirementId: string) { return REQUIREMENT_WORKSPACES.find((item) => item.requirementId === requirementId); }
export function getRequirementByCode(code: string) { return REQUIREMENT_WORKSPACES.find((item) => item.code === code); }
